// frontend/hfs-frontend-vuetify/src/admin/pages/AdmPage.vue
<script lang="ts">
import { ref, onMounted, onBeforeMount, shallowRef } from 'vue';
import AdmPageService from '../../admin/service/AdmPageService';
import { AdmPage, cleanAdmPage, emptyAdmPage } from '../api/AdmPage';
import { ReportParamForm, emptyReportParamForm } from '../../base/models/ReportParamsForm';
import { ItypeReport, PDFReport, SelectItemGroup } from '../../base/services/ReportService';
import { SnackbarMessage, emptySnackbarMessage } from '../../base/models/SnackbarMessage';
import { AdmProfile } from '../api/AdmProfile';
import AdmProfileService from '../service/AdmProfileService';

export default {
    setup() {
        const snackbar = ref<SnackbarMessage>(emptySnackbarMessage);

        const listaAdmPage = ref<AdmPage[]>([]);
        const admPageDialog = shallowRef(false)
        const deleteAdmPageDialog = ref(false);
        const deleteAdmPagesDialog = ref(false);
        const admPage = ref(emptyAdmPage);
        const selectedAdmPages = ref<number[]>([]);
        const submitted = ref(false);

        const admPageService = new AdmPageService();
        const admProfileService = new AdmProfileService();
        
        const selectedTypeReport = ref<ItypeReport>();
        const selectedForceDownload = ref(true);
        const reportParamForm = ref<ReportParamForm>(emptyReportParamForm);

        //const exportColumns = ref([]);

        const itemsPerPage = ref(10);
        const columns = ref();        
        const loading = ref(true);
        const totalItems = ref(0);
        const search = ref('');

        const sourceProfiles = ref<AdmProfile[]>([]);
        const targetProfiles = ref<AdmProfile[]>([]);

        onBeforeMount(() => {
            columns.value = [
                { key: 'id', title: 'Id', sortable: true, align: 'start' },
                { key: 'url', title: 'Página', sortable: true, align: 'start' },
                { key: 'description', title: 'Descrição', sortable: true, align: 'start' },
                { key: 'pageProfiles', title: 'Perfil(s) da página', sortable: true, align: 'start' },
                { key: 'actions', title: "Ações", sortable: false }
            ];            
        });

        onMounted(() => {
            loadItems();

            selectedTypeReport.value = PDFReport.value;
        });

        const loadItems = () => {
            loading.value = true;
            admPageService.findAll().then(data => {
                listaAdmPage.value = data;
                totalItems.value = listaAdmPage.value.length;
                loading.value = false;
            });
        }

        const snackBar = (msg: string, duration: number) => {
            snackbar.value.open = true;
            snackbar.value.message = msg;
            snackbar.value.timeout = duration;
        }

        const loadAdmProfiles = (admPage: AdmPage | null): void => {
            targetProfiles.value = [];

            if (admPage == null) {

                admProfileService.findAll().then(profiles => {
                    sourceProfiles.value = profiles;
                });

            } else {      
            
                if (admPage.id != null) {
                    admProfileService.findProfilesByPage(admPage).then(data => {
                    targetProfiles.value = data;

                        admProfileService.findAll().then(profiles => {
                            sourceProfiles.value = profiles.filter(profile => 
                                !targetProfiles.value.find(target => target.id === profile.id)
                            );
                        });

                    });
                }

            }            
        }

        const mostrarListar = () => {
            if (admPageDialog.value)
                return { display: 'none' };
            else
                return { display: '' };
        }

        const mostrarEditar = () => {
            if (admPageDialog.value)
                return { display: '' };
            else
                return { display: 'none' };
        }

        const onClean = () => {
            admPage.value = cleanAdmPage;
            loadAdmProfiles(null);
        }
                
        const onInsert = () => {
            admPage.value = emptyAdmPage;
            submitted.value = false;
            admPageDialog.value = true;
            loadAdmProfiles(null);
        };

        const onEdit = (param: AdmPage) => {
            admPage.value = { ...param };
            admPageDialog.value = true;
            loadAdmProfiles(admPage.value);
        };

        const hideDialog = () => {
            admPageDialog.value = false;
            submitted.value = false;
        };

        const onSave = () => {
            submitted.value = true;
            admPage.value.admIdProfiles = [];
            targetProfiles.value.forEach(item => {
                admPage.value.admIdProfiles.push(item.id)
            });

            if (admPage.value.description && admPage.value.description.trim()) {
                if (admPage.value.id) {
                    admPageService.update(admPage.value).then((obj: AdmPage) => {
                        admPage.value = obj;

                        if (admPage.value.id){
                            const index = admPageService.findIndexById(listaAdmPage.value, admPage.value.id);
                            listaAdmPage.value[index] = admPage.value;

                            admPageDialog.value = false;
                            admPage.value = emptyAdmPage;

                            snackBar('Página Atualizada', 3000);
                        }
                    });            
                } else {
                    admPageService.insert(admPage.value).then((obj: AdmPage) => {
                        admPage.value = obj;

                        listaAdmPage.value.push(admPage.value);
                        admPageDialog.value = false;
                        admPage.value = emptyAdmPage;

                        snackBar('Página Criada', 3000);
                    });            
                }

            }
        };

        const deleteSelected = () => {
            deleteAdmPagesDialog.value = true;
        }

        const onDelete = (param: AdmPage) => {
            deleteAdmPageDialog.value = true;
            admPage.value = { ...param };
        } 

        const confirmDeleteSelected = () => {            
            deleteAdmPagesDialog.value = false;
            
            let selecionados: AdmPage[] = [];
            listaAdmPage.value.forEach((item: AdmPage) => {
                selectedAdmPages.value.forEach((id: number) => {
                    if (item.id === id){
                        selecionados.push(item);
                    }
                });        
            });

            if (selecionados.length > 0){
                listaAdmPage.value = listaAdmPage.value.filter(
                    (val: AdmPage) => !selecionados.includes(val));

                    selecionados.forEach((item: AdmPage, index: number) => {
                    if (item.id){
                        admPageService.delete(item.id).then(() => {

                            if (selecionados.length == (index+1)){
                                snackBar('Parâmetros excluídos', 3000);
                                selectedAdmPages.value = [];
                            }

                        });
                    }
                });

            }
        }

        const confirmDelete = () => {
            deleteAdmPageDialog.value = false;
            if (admPage.value.id){
                admPageService.delete(admPage.value.id).then(() => {
                    listaAdmPage.value = listaAdmPage.value.filter((val: AdmPage) => val.id !== admPage.value.id);
                    admPage.value = emptyAdmPage;        
                    snackBar('Página excluída', 3000);
                });
            }    
        }

        const onTypeReportChange = (param: { pTypeReport: SelectItemGroup }) => {            
            if (param.pTypeReport.value){
                selectedTypeReport.value = param.pTypeReport.value;
                reportParamForm.value = { reportType: param.pTypeReport.value.type, forceDownload: selectedForceDownload.value };
            }        
        }

        const onForceDownloadChange = (param: { forceDownload: boolean }) => {
            selectedForceDownload.value = param.forceDownload;
            if (selectedTypeReport.value){
                reportParamForm.value = { reportType: selectedTypeReport.value.type, forceDownload: param.forceDownload };
            }
        }

        const onExport = () => {
            admPageService.report(reportParamForm.value).then(() => {
                snackBar('Página exportada', 3000);
            });            
        }

        return { listaAdmPage, admPage, submitted, onClean, mostrarListar, mostrarEditar,
            selectedAdmPages, deleteSelected, admPageDialog, hideDialog,
            deleteAdmPageDialog, confirmDelete, deleteAdmPagesDialog,
            onInsert, onEdit, onDelete, onSave, onExport, onTypeReportChange, onForceDownloadChange,
            confirmDeleteSelected, itemsPerPage, columns, loading, totalItems, search,
            snackbar, sourceProfiles, targetProfiles }
    }
}        
</script>

<template>
    <div class="grid">
        <div class="col-12">

            <v-snackbar v-model="snackbar.open" :timeout="snackbar.timeout" location="top">
                {{ snackbar.message }}
                <template v-slot:actions>
                    <v-btn color="red" density="compact" icon="close" @click="snackbar.open = false"></v-btn>
                </template>
            </v-snackbar>

            <div class="card px-6 py-6" :style="mostrarListar()">
                <v-card-item>
                    <v-card-title>Página</v-card-title>
                </v-card-item>
                <v-card-text>
                    <ReportPanel @changeTypeReport="onTypeReportChange" @changeForceDownload="onForceDownloadChange"></ReportPanel>
                </v-card-text>

                <v-toolbar>
                    <v-btn prepend-icon="add" @click="onInsert" variant="elevated" color="green" :style="{ marginRight: '10px' }">Adicionar</v-btn>
                    <v-btn prepend-icon="delete" @click="deleteSelected" variant="elevated" color="red"
                        :disabled="!selectedAdmPages || !selectedAdmPages.length" :style="{ marginRight: '10px' }">Excluir</v-btn>
                        
                    <span class="spacer"></span>

                    <v-btn prepend-icon="upload" @click="onExport" variant="elevated" color="indigo-darken-3">Exportar</v-btn>    
                </v-toolbar>
                
                <v-data-table
                    v-model="selectedAdmPages"
                    v-model:items-per-page="itemsPerPage"
                    :headers="columns"
                    :items="listaAdmPage"
                    :items-length="totalItems"
                    :loading="loading"
                    :search="search"
                    item-value="id"
                    show-select
                    :sort-by="[{ key: 'id', order: 'asc' }]">

                    <template v-slot:item.actions="{ item }">
                        <v-btn variant="plain">
                            <v-icon icon="more_vert"></v-icon>
                            <v-menu activator="parent">
                                <v-list>
                                    <v-list-item>
                                        <v-list-item-title @click="onEdit(item)" style="cursor: pointer;">Editar</v-list-item-title>
                                        <v-list-item-title @click="onDelete(item)" style="cursor: pointer;">Excluir</v-list-item-title>
                                    </v-list-item>
                                </v-list>
                            </v-menu>
                        
                        </v-btn>
                    </template>
                    
                </v-data-table>
            </div>    

            <div :style="mostrarEditar()">
                <v-card title="Detalhes da página">
                    <v-toolbar>
                        <v-spacer></v-spacer>
                        <v-btn prepend-icon="cancel" color="secondary" :style="{ marginRight: '10px' }" @click="hideDialog" variant="elevated">Cancelar</v-btn>
                        <v-btn prepend-icon="star" color="primary" :style="{ marginRight: '10px' }" @click="onClean" variant="elevated">Limpar</v-btn>
                        <v-btn prepend-icon="check" color="primary" @click="onSave" variant="elevated">Salvar</v-btn>
                    </v-toolbar>

                    <v-card-text>
                        <v-row>
                            <v-text-field label="Página" v-model="admPage.url" required
                                :class="{ 'text-red': submitted && !admPage.url }">
                            </v-text-field>
                        </v-row>
                        <v-row>
                            <small class="text-red" v-if="submitted && !admPage.url">A página é obrigatória.</small>
                        </v-row>
                        <v-row>
                            <v-text-field label="Descrição" v-model="admPage.description" required
                                :class="{ 'text-red': submitted && !admPage.description }">
                            </v-text-field>                                
                        </v-row>
                        <v-row>
                            <small class="text-red" v-if="submitted && !admPage.description">A descrição é obrigatória.</small>
                        </v-row>
                        <v-row>
                            <label>Perfil(s) da página:</label>
                            <PickList :source="sourceProfiles" :target="targetProfiles"></PickList>
                        </v-row>
                    </v-card-text>
                </v-card>
            </div>

            <v-dialog v-model="deleteAdmPageDialog" max-width="450" persistent>
                <v-card prepend-icon="warning" title="Confirme">
                    <v-card-text>
                        <span v-if="admPage">Tem certeza de que deseja excluir <b>{{ admPage.description }}</b>?</span>
                    </v-card-text>                        
                    <template v-slot:actions>
                        <v-spacer></v-spacer>
                        <v-btn prepend-icon="cancel" color="secondary" :style="{ marginRight: '10px' }" 
                            @click="deleteAdmPageDialog = false" variant="elevated">Não</v-btn>
                        <v-btn prepend-icon="check" color="primary" @click="confirmDelete" variant="elevated">Sim</v-btn>
                    </template>
                </v-card>
            </v-dialog>

            <v-dialog v-model="deleteAdmPagesDialog" max-width="450" persistent>
                <v-card prepend-icon="warning" title="Confirme">
                    <v-card-text>
                        <span v-if="admPage">Tem certeza de que deseja excluir as categorias de parâmetros selecionadas?</span>
                    </v-card-text>                        
                    <template v-slot:actions>
                        <v-spacer></v-spacer>
                        <v-btn prepend-icon="cancel" color="secondary" :style="{ marginRight: '10px' }" 
                            @click="deleteAdmPagesDialog = false" variant="elevated">Não</v-btn>
                        <v-btn prepend-icon="check" color="primary" @click="confirmDeleteSelected" variant="elevated">Sim</v-btn>
                    </template>
                </v-card>
            </v-dialog>

        </div>
    </div>
</template>

<style>
.spacer {
    flex: 1 1 auto;
}
</style>

// frontend/hfs-frontend-jest/src/app/admin/pages/adm-page/adm-page.component.ts
import { Component, OnInit } from '@angular/core';
import { MessageService, MenuItem } from 'primeng/api';
import { ExportService } from '../../../base/services/export.service';
import { ReportParamForm } from 'src/app/base/models/ReportParamsForm';
import { ItypeReport } from 'src/app/base/services/ReportService';
import { AdmPageService } from '../../service/AdmPageService';
import { AdmPage, cleanAdmPage } from '../../api/AdmPage';
import { AdmProfile } from '../../api/AdmProfile';
import { AdmProfileService } from '../../service/AdmProfileService';
import { Menu } from 'primeng/menu';
import { Table } from 'primeng/table';

@Component({
  templateUrl: './adm-page.component.html',
  providers: [MessageService, AdmPageService]
})
export class AdmPageComponent implements OnInit {

  admPageDialog: boolean;

  listaAdmPage: AdmPage[] = [];

  admPage: AdmPage = {};

  selectedAdmPage: AdmPage[] = [];

  submitted: boolean;

  cols: any[];

  exportColumns: any[];

  reportParamForm: ReportParamForm;

  deleteAdmPageDialog: boolean = false;

  deleteAdmPagesDialog: boolean = false;

  itemsMenuLinha: MenuItem[];  

  sourceProfiles: AdmProfile[];
  targetProfiles: AdmProfile[];

  constructor(private messageService: MessageService,
    private admPageService: AdmPageService,
    private admProfileService: AdmProfileService,
    private exportService: ExportService) {
      this.reportParamForm = {
        reportType: 'PDF',
        forceDownload: true
      };

      this.itemsMenuLinha = [{ label: "Editar" }, { label: "Excluir" }];
  }

  toggleMenu(menu: Menu, event: any, rowData: AdmPage) {
    this.itemsMenuLinha = [];

    this.itemsMenuLinha.push({
      label: 'Editar',
      command: (event: any) => {
        this.onEdit(rowData);
      }
    });

    this.itemsMenuLinha.push({
      label: 'Excluir',
      command: (event: any) => {
        this.onDelete(rowData);
      }
    });

    menu.toggle(event);
  }

  ngOnInit(): void {
    this.admPageService
      .findAll()
      .then(data => this.listaAdmPage = data);

    this.cols = [
      { field: 'id', header: 'Id' },
      { field: 'url', header: 'Página' },
      { field: 'description', header: 'Descrição' },
      { field: 'pageProfiles', header: 'Perfil(s) da página' }
    ];

    this.exportColumns = this.cols.map(col => ({title: col.header, dataKey: col.field}));

  }

  private loadAdmProfiles(admPage: AdmPage): void {
    this.targetProfiles = [];

    if (admPage == null) {

      this.admProfileService.findAll().then(profiles => {
        this.sourceProfiles = profiles;
      });

    } else {      
      
      if (this.admPage.id != null) {
        this.admProfileService.findProfilesByPage(admPage).then(data => {
          this.targetProfiles = data;
  
          this.admProfileService.findAll().then(profiles => {
            this.sourceProfiles = profiles.filter(profile => 
              !this.targetProfiles.find(target => target.id === profile.id)
            );
          });
  
        });
      }

    }
  }

  mostrarListar() {
    if (this.admPageDialog)
        return {display:'none'};
    else
        return {display:''};
  }

  mostrarEditar() {
      if (this.admPageDialog)
          return {display:''};
      else
          return {display:'none'};
  }

  onClean() {
    this.admPage = cleanAdmPage;
    this.loadAdmProfiles(null);
  }

  onSave() {
    this.submitted = true;
    this.admPage.admIdProfiles = [];
    this.targetProfiles.forEach(item => {
      this.admPage.admIdProfiles.push(item.id)
    });

    if (this.admPage.description.trim()) {
        if (this.admPage.id) {
          this.admPageService.update(this.admPage).then((obj: AdmPage) => {
            this.admPage = obj;

            this.listaAdmPage[
              this.admPageService.findIndexById(this.listaAdmPage, this.admPage.id)] = this.admPage;
            this.messageService.add({ severity: 'success', summary: 'Sucesso', detail: 'Página Atualizada', life: 3000 });
          });
        } else {
          this.admPageService.insert(this.admPage).then((obj: AdmPage) => {
            this.admPage = obj;

            this.listaAdmPage.push(this.admPage);
            this.messageService.add({ severity: 'success', summary: 'Sucesso', detail: 'Página Criada', life: 3000 });
          });
        }

        this.listaAdmPage = [...this.listaAdmPage];
        this.admPageDialog = false;
        this.admPage = {};
    }
  }

  onChangedTypeReport(typeReport: ItypeReport) {
    this.reportParamForm.reportType = typeReport.type;
  }

  onChangedForceDownload(forceDownload: boolean) {
    this.reportParamForm.forceDownload = forceDownload;
  }

  onExport() {
    this.admPageService.report(this.reportParamForm).then(() => {
      this.messageService.add({severity: 'info', summary: 'Página Exportada', detail: 'Página Exportada', life: 1000});
    });
  }

  onInsert() {
    this.admPage = {};
    this.submitted = false;
    this.admPageDialog = true;
    this.loadAdmProfiles(null);
  }

  onEdit(admPage: AdmPage) {
    this.admPage = { ...admPage };
    this.admPageDialog = true;
    this.loadAdmProfiles(admPage);
  }

  hideDialog() {
    this.admPageDialog = false;
    this.submitted = false;
  }

  deleteSelected() {
    this.deleteAdmPagesDialog = true;
  }

  onDelete(admPage: AdmPage) {
    this.deleteAdmPageDialog = true;
    this.admPage = { ...admPage };
  } 

  confirmDeleteSelected() {    
    this.deleteAdmPagesDialog = false;
    this.listaAdmPage = this.listaAdmPage.filter(val => !this.selectedAdmPage.includes(val));

    let excluiu = false;
    this.selectedAdmPage.forEach((item) => {
      this.admPageService.delete(item.id).then(obj => {
        excluiu = true;
      });
    });

    if (excluiu) {
      this.messageService.add({ severity: 'success', summary: 'Sucesso', detail: 'Páginas excluídas', life: 3000 });
      this.selectedAdmPage = [];  
    }
  }

  confirmDelete() {
    this.deleteAdmPageDialog = false;
    this.admPageService.delete(this.admPage.id).then(obj => {
      this.listaAdmPage = this.listaAdmPage.filter(val => val.id !== this.admPage.id);
      this.admPage = {};        
      this.messageService.add({ severity: 'success', summary: 'Sucesso', detail: 'Página excluída', life: 3000 });
    });
  }

  onGlobalFilter(table: Table, event: Event) {
    table.filterGlobal((event.target as HTMLInputElement).value, 'contains');
  }
  
  exportPdf() {
    const head: string[] = [];
    const data: any[] = [];

    this.exportColumns.forEach(item => head.push(item.title));
    this.listaAdmPage.forEach(item => data.push(
      [item.id, item.url, item.description, item.pageProfiles]
    ));

    this.exportService.exportPdf(head, data, 'paginas.pdf');
  }

  exportExcel() {
    this.exportService.exportExcel(this.listaAdmPage, 'paginas');
  }

}

<div class="grid">
    <div class="col-12">

        <div class="card px-6 py-6" [style]="mostrarListar()">
            <p-toast></p-toast>
            <p-panel header="Página" styleClass="p-mb-2">
                <app-report-panel (typeReportChange)="onChangedTypeReport($event)" (forceDownloadChange)="onChangedForceDownload($event)"></app-report-panel>
            </p-panel>            
            <p-toolbar styleClass="mb-4">
                <ng-template pTemplate="left">
                    <div class="my-2">
                        <button pButton pRipple label="Adicionar" icon="pi pi-plus" class="p-button-success mr-2" (click)="onInsert()"></button>
                        <button pButton pRipple label="Excluir" icon="pi pi-trash" class="p-button-danger" (click)="deleteSelected()" 
                        [disabled]="!selectedAdmPage || !selectedAdmPage.length"></button>
                    </div>
                </ng-template>

                <ng-template pTemplate="right">
                    <button pButton pRipple label="Exportar" icon="pi pi-upload" class="p-button-help" (click)="onExport()"></button>
                </ng-template>
            </p-toolbar>

            <p-menu #popupMenu [model]="itemsMenuLinha" [popup]="true"></p-menu>

            <p-table #dt [value]="listaAdmPage" [columns]="cols" responsiveLayout="scroll" [rows]="10" 
                [globalFilterFields]="['url']" paginatorPosition="both"
                [paginator]="true" [rowsPerPageOptions]="[10,30,50,100,150,200]" [showCurrentPageReport]="true" 
                currentPageReportTemplate="Mostrando {first} até {last} de {totalRecords} entradas" 
                [(selection)]="selectedAdmPage" selectionMode="multiple" [rowHover]="true" dataKey="id">
                <ng-template pTemplate="caption">
                    <div class="flex flex-column md:flex-row md:justify-content-between md:align-items-center">
                        <h5 class="m-0">Gerenciar parâmetros</h5>
                        <span class="block mt-2 md:mt-0 p-input-icon-left">
                            <i class="pi pi-search"></i>
                            <input pInputText type="text" (input)="onGlobalFilter(dt, $event)" placeholder="Procurar..."  class="w-full sm:w-auto"/>
                        </span>
                    </div>
                </ng-template>
                <ng-template pTemplate="header">
                    <tr>
                        <th style="width: 3rem">
                            <p-tableHeaderCheckbox></p-tableHeaderCheckbox>
                        </th>                        
                        <th pSortableColumn="id">Id <p-sortIcon field="id"></p-sortIcon></th>
                        <th pSortableColumn="url">Página <p-sortIcon field="url"></p-sortIcon></th>
                        <th pSortableColumn="description">Descrição <p-sortIcon field="description"></p-sortIcon></th>
                        <th pSortableColumn="pageProfiles">Perfil(s) da página <p-sortIcon field="pageProfiles"></p-sortIcon></th>
                        <th></th>
                    </tr>
                </ng-template>
                <ng-template pTemplate="body" let-admPage>
                    <tr>
                        <td>
                            <p-tableCheckbox [value]="admPage"></p-tableCheckbox>
                        </td>
                        <td style="width:5%; min-width:5rem;"><span class="p-column-title">Id</span>
                            {{admPage.id}}
                        </td>
                        <td style="min-width:10rem;">
                            <span class="p-column-title">Página</span>
                            {{admPage.url}}
                        </td>
                        <td style="min-width:8rem;">
                            <span class="p-column-title">Descrição</span>
                            {{admPage.description}}
                        </td>
                        <td style="min-width:8rem;">
                            <span class="p-column-title">Perfil(s) da página</span>
                            {{admPage.pageProfiles}}
                        </td>
                        <td style="width: 10px;">
                            <div class="flex">                                
                                <a *ngIf="itemsMenuLinha" (click)="toggleMenu(popupMenu, $event, admPage)" style="cursor: pointer;">
                                    <i class="pi pi-ellipsis-v"></i>
                                </a>
                            </div>
                        </td>
                    </tr>
                </ng-template>
                <ng-template pTemplate="summary">
                    <div class="p-d-flex p-ai-center p-jc-between">
                        No total existem {{listaAdmPage ? listaAdmPage.length : 0 }} paginas.
                    </div>
                </ng-template>            
            </p-table>
        </div>        

        <div [style]="mostrarEditar()">

            <p-panel header="Detalhes da página" styleClass="p-mb-2">
                <p-toast></p-toast>
                <p-toolbar styleClass="mb-4">
                    <ng-template pTemplate="left">
                    </ng-template>
                    <ng-template pTemplate="right">
                        <div class="my-2">
                            <button pButton pRipple label="Cancelar" icon="pi pi-times" class="p-button-secondary mr-2" (click)="hideDialog()"></button>
                            <button pButton pRipple label="Limpar" icon="pi pi-star-o" class="p-button-primary mr-2" (click)="onClean()"></button>
                            <button pButton pRipple label="Salvar" icon="pi pi-check" class="p-button-success" (click)="onSave()"></button>        
                        </div>
                    </ng-template>
                </p-toolbar>
    
                <div class="card p-fluid">
                    <div class="field">
                        <label for="url">Página:</label>
                        <input type="text" pInputText id="url" [(ngModel)]="admPage.url" required 
                            [ngClass]="{'ng-invalid ng-dirty' : submitted && !admPage.url}" />
                        <small class="ng-dirty ng-invalid" *ngIf="submitted && !admPage.url">A página é obrigatória.</small>
                    </div>
                    <div class="field">
                        <label for="description">Descrição</label>
                        <input type="text" pInputText id="description" [(ngModel)]="admPage.description" required
                            [ngClass]="{'ng-invalid ng-dirty' : submitted && !admPage.description}" />
                        <small class="ng-dirty ng-invalid" *ngIf="submitted && !admPage.description">A descrição é obrigatória.</small>
                    </div>
                    <div class="field">
                        <label for="pageProfiles">Perfil(s) da página:</label>
            
                        <p-pickList id="pageProfiles" 
                            [source]="sourceProfiles" [target]="targetProfiles" sourceHeader="Disponível" targetHeader="Selecionada" [dragdrop]="true"
                            [responsive]="true" [sourceStyle]="{'height':'30rem'}" [targetStyle]="{'height':'30rem'}" filterBy="description"
                            sourceFilterPlaceholder="Pesquisar por descrição" targetFilterPlaceholder="Pesquisar por descrição">
                            <ng-template let-profile pTemplate="item">
                                <div class="profile-item">
                                    <div>{{profile.description}}</div>
                                </div>
                            </ng-template>
                        </p-pickList>
                    </div>
                </div>
            </p-panel>              

        </div>        

        <p-dialog [(visible)]="deleteAdmPageDialog" header="Confirme" [modal]="true" [style]="{width:'450px'}">
            <div class="flex align-items-center justify-content-center">
                <i class="pi pi-exclamation-triangle mr-3" style="font-size: 2rem"></i>
                <span *ngIf="admPage">Tem certeza de que deseja excluir <b>{{admPage.description}}</b>?</span>
            </div>
            <ng-template pTemplate="footer">
                <button pButton pRipple icon="pi pi-times" class="p-button-text" label="Não" (click)="deleteAdmPageDialog = false"></button>
                <button pButton pRipple icon="pi pi-check" class="p-button-text" label="Sim" (click)="confirmDelete()"></button>
            </ng-template>
        </p-dialog>

        <p-dialog [(visible)]="deleteAdmPagesDialog" header="Confirme" [modal]="true" [style]="{width:'450px'}">
            <div class="flex align-items-center justify-content-center">
                <i class="pi pi-exclamation-triangle mr-3" style="font-size: 2rem"></i>
                <span>Tem certeza de que deseja excluir as páginas selecionados?</span>
            </div>
            <ng-template pTemplate="footer">
                <button pButton pRipple icon="pi pi-times" class="p-button-text" label="Não" (click)="deleteAdmPagesDialog = false"></button>
                <button pButton pRipple icon="pi pi-check" class="p-button-text" label="Sim" (click)="confirmDeleteSelected()"></button>
            </ng-template>
        </p-dialog>

    </div>
</div>
