// frontend/hfs-frontend-vue/src/admin/pages/AdmProfile.vue
<script lang="ts">
import { FilterMatchMode } from 'primevue/api';
import { ref, onMounted, onBeforeMount } from 'vue';
import { useToast } from 'primevue/usetoast';
import AdmProfileService from '../../admin/service/AdmProfileService';
import { ExportService } from '../../base/services/ExportService';
import { AdmProfile, cleanAdmProfile, emptyAdmProfile } from '../api/AdmProfile';
import { ReportParamForm, emptyReportParamForm } from '../../base/models/ReportParamsForm';
import { ItypeReport, PDFReport, SelectItemGroup } from '../../base/services/ReportService';
import { MenuItem } from '../../base/models/MenuItem';
import { AdmPage } from '../api/AdmPage';
import AdmPageService from '../service/AdmPageService';

export default {
    setup() {
        const toast = useToast();

        const listaAdmProfile = ref<AdmProfile[]>([]);
        const admProfileDialog = ref(false);
        const deleteAdmProfileDialog = ref(false);
        const deleteAdmProfilesDialog = ref(false);
        const admProfile = ref(emptyAdmProfile);
        const selectedAdmProfiles = ref();
        const dt = ref(null);
        const filters = ref({});
        const cols = ref();
        const exportColumns = ref([]);
        const submitted = ref(false);

        const admProfileService = new AdmProfileService();
        const admPageService = new AdmPageService();
        const exportService = new ExportService();

        const selectedTypeReport = ref<ItypeReport>();
        const selectedForceDownload = ref(true);
        const reportParamForm = ref<ReportParamForm>(emptyReportParamForm);

        const popupMenu = ref();
        const itemsMenuLinha = ref<MenuItem[]>([]);

        const profilePages = ref<AdmPage[][]>();

        onBeforeMount(() => {
            initFilters();
        });

        onMounted(() => {
            admProfileService.findAll().then((data) => (listaAdmProfile.value = data));

            selectedTypeReport.value = PDFReport.value;

            itemsMenuLinha.value = [{ label: "Editar" }, { label: "Excluir" }];

            cols.value = [
                { field: 'id', header: 'Id' },
                { field: 'description', header: 'Descrição' },
                { field: 'profilePages', header: 'Páginas(s) do perfil' }
            ];

            exportColumns.value = cols.value.map((col: { header: any; field: any; }) => ({title: col.header, dataKey: col.field}));

        });

        const toggleMenu = (event: any, rowData: AdmProfile) => {
            itemsMenuLinha.value = [];

            itemsMenuLinha.value.push({
                label: 'Editar',
                command: (event: any) => {
                    onEdit(rowData);
                }
            });

            itemsMenuLinha.value.push({
                label: 'Excluir',
                command: (event: any) => {
                    onDelete(rowData);
                }
            });
            
            popupMenu.value.toggle(event);
        }

        const loadAdmPages = () => {
            let sourcePages: AdmPage[] = [];
            let targetPages: AdmPage[] = [];
            
            if (admProfile.value.id != null) {
                targetPages = [...admProfile.value.admPages];
            }

            admPageService.findAll().then(pages => {
                sourcePages = pages.filter(page => !targetPages.find(target => target.id === page.id));

                profilePages.value = [sourcePages, targetPages];
            });
        }        

        const mostrarListar = () => {
            if (admProfileDialog.value)
                return { display: 'none' };
            else
                return { display: '' };
        }

        const mostrarEditar = () => {
            if (admProfileDialog.value)
                return { display: '' };
            else
                return { display: 'none' };
        }

        const onClean = () => {
            admProfile.value = cleanAdmProfile;
            loadAdmPages();
        }

        const onInsert = () => {
            admProfile.value = emptyAdmProfile;
            submitted.value = false;
            admProfileDialog.value = true;
            loadAdmPages();
        };

        const onEdit = (param: AdmProfile) => {
            admProfile.value = { ...param };
            admProfileDialog.value = true;
            loadAdmPages();
        };

        const hideDialog = () => {
            admProfileDialog.value = false;
            submitted.value = false;
        };

        const onSave = () => {
            submitted.value = true;
            admProfile.value.admPages = [];
            profilePages.value?.forEach((value: AdmPage[]) => {
                let sourcePages: AdmPage[] = value;

                sourcePages.forEach((value: AdmPage) => {
                    let targetPages: AdmPage = value;
                    admProfile.value.admPages.push(targetPages);
                });
            });

            if (admProfile.value.description && admProfile.value.description.trim()) {
                if (admProfile.value.id) {
                    admProfileService.update(admProfile.value).then((obj: AdmProfile) => {
                        admProfile.value = obj;

                        const index = admProfileService.findIndexById(listaAdmProfile.value, admProfile.value.id);
                        listaAdmProfile.value[index] = admProfile.value;

                        toast.add({severity:'success', summary: 'Successful', detail: 'Perfil Atualizada', life: 3000});
                    });            
                } else {
                    admProfileService.insert(admProfile.value).then((obj: AdmProfile) => {
                        admProfile.value = obj;

                        listaAdmProfile.value.push(admProfile.value);
                        toast.add({ severity: 'success', summary: 'Successful', detail: 'Perfil Criada', life: 3000 });
                    });            
                }

                admProfileDialog.value = false;
                admProfile.value = emptyAdmProfile;
            }
        };

        const deleteSelected = () => {
            deleteAdmProfilesDialog.value = true;
        }

        const onDelete = (param: AdmProfile) => {
            deleteAdmProfileDialog.value = true;
            admProfile.value = { ...param };
        } 

        const confirmDeleteSelected = () => {
            deleteAdmProfilesDialog.value = false;
            listaAdmProfile.value = listaAdmProfile.value.filter((val: AdmProfile) => !selectedAdmProfiles.value.includes(val));

            let excluiu = false;
            selectedAdmProfiles.value.forEach((item: AdmProfile) => {
                admProfileService.delete(item.id).then(obj => {
                    excluiu = true;
                });
            });

            if (excluiu) {
                toast.add({ severity: 'success', summary: 'Sucesso', detail: 'Perfis excluídos', life: 3000 });
                selectedAdmProfiles.value = [];
            }
        }

        const confirmDelete = () => {
            deleteAdmProfileDialog.value = false;
            admProfileService.delete(admProfile.value.id).then(obj => {
                listaAdmProfile.value = listaAdmProfile.value.filter((val: AdmProfile) => val.id !== admProfile.value.id);
                admProfile.value = emptyAdmProfile;        
                toast.add({ severity: 'success', summary: 'Sucesso', detail: 'Perfil excluído', life: 3000 });
            });
        }

        const onTypeReportChange = (param: { pTypeReport: SelectItemGroup }) => {
            if (param.pTypeReport.value){
                selectedTypeReport.value = param.pTypeReport.value;
                reportParamForm.value = { reportType: param.pTypeReport.value.type, forceDownload: selectedForceDownload.value };
            }        
        }

        const onForceDownloadChange = (param: { forceDownload: boolean }) => {
            selectedForceDownload.value = param.forceDownload;
            if (selectedTypeReport.value){
                reportParamForm.value = { reportType: selectedTypeReport.value.type, forceDownload: param.forceDownload };
            }
        }

        const onExport = () => {
            admProfileService.report(reportParamForm.value).then(() => {
                toast.add({ severity: 'info', summary: 'Perfil exportada', 
                    detail: 'Perfil exportada', life: 3000 });
            });
        }

        const initFilters = () => {
            filters.value = {
                global: { value: null, matchMode: FilterMatchMode.CONTAINS }
            };
        };

        const exportPdf = () => {
            const head: string[] = [];
            const data: any[] = [];

            exportColumns.value.forEach((item: { title: string; }) => head.push(item.title));
            listaAdmProfile.value.forEach((item: AdmProfile) => data.push(
                [item.id, item.description, item.profilePages]
            ));

            exportService.exportPdf(head, data, 'perfis.pdf');
        }

        const exportExcel = () => {
            exportService.exportExcel(listaAdmProfile.value, 'perfis');
        }


        return { listaAdmProfile, admProfile, filters, submitted, itemsMenuLinha, toggleMenu, popupMenu,
            selectedAdmProfiles, deleteSelected, admProfileDialog, hideDialog, mostrarListar, mostrarEditar, onClean,
            deleteAdmProfileDialog, confirmDelete, deleteAdmProfilesDialog, profilePages,
            onInsert, onEdit, onDelete, onSave, onExport, onTypeReportChange, onForceDownloadChange,
            confirmDeleteSelected }
    }
}        
</script>

<template>
    <div class="grid">
        <div class="col-12">
            <div class="card px-6 py-6" :style="mostrarListar()">
                <!-- <Toast /> -->
                <Panel header="Perfil" class="p-mb-2">
                    <ReportPanel @changeTypeReport="onTypeReportChange" @changeForceDownload="onForceDownloadChange"></ReportPanel>
                </Panel>                
                <Toolbar class="mb-4">
                    <template v-slot:start>
                        <div class="my-2">
                            <Button label="Adicionar" icon="pi pi-plus" class="p-button-success mr-2" @click="onInsert" />
                            <Button label="Excluir" icon="pi pi-trash" class="p-button-danger" @click="deleteSelected" 
                                :disabled="!selectedAdmProfiles || !selectedAdmProfiles.length" />
                        </div>
                    </template>

                    <template v-slot:end>
                        <Button label="Exportar" icon="pi pi-upload" class="p-button-help" @click="onExport" />
                    </template>
                </Toolbar>

                <Menu ref="popupMenu" id="popup_menu" :model="itemsMenuLinha" :popup="true" />

                <DataTable
                    ref="dt" paginatorPosition="both"
                    :value="listaAdmProfile"
                    v-model:selection="selectedAdmProfiles"
                    dataKey="id"
                    :paginator="true"
                    :rows="10"
                    :filters="filters"
                    paginatorTemplate="FirstPageLink PrevPageLink PageLinks NextPageLink LastPageLink CurrentPageReport RowsPerPageDropdown"
                    :rowsPerPageOptions="[10,30,50,100,150,200]" emptyMessage="Nenhum registro encontrado."
                    currentPageReportTemplate="Mostrando {first} até {last} de {totalRecords} entradas"
                    responsiveLayout="scroll"
                >
                    <template #header>
                        <div class="flex flex-column md:flex-row md:justify-content-between md:align-items-center">
                            <h5 class="m-0">Gerenciar páginas</h5>
                            <span class="block mt-2 md:mt-0 p-input-icon-left">
                                <i class="pi pi-search" />
                                <InputText v-model="filters['global'].value" placeholder="Procurar..." />
                            </span>
                        </div>
                    </template>

                    <Column selectionMode="multiple" headerStyle="width: 3rem"></Column>
                    <Column field="id" header="Id" :sortable="true" headerStyle="width:5%; min-width:5rem;">
                        <template #body="slotProps">
                            <span class="p-column-title">Id</span>
                            {{ slotProps.data.id }}
                        </template>
                    </Column>
                    <Column field="description" header="Descrição" :sortable="true" headerStyle="min-width:8rem;">
                        <template #body="slotProps">
                            <span class="p-column-title">Descrição</span>
                            {{ slotProps.data.description }}
                        </template>
                    </Column>
                    <Column field="profilePages" header="Páginas(s) do perfil" :sortable="true" headerStyle="min-width:8rem;">
                        <template #body="slotProps">
                            <span class="p-column-title">Páginas(s) do perfil</span>
                            {{ slotProps.data.profilePages }}
                        </template>
                    </Column>
                    <Column headerStyle="min-width:10rem;">
                        <template #body="slotProps">
                            <div class="flex">
                                <Button link icon="pi pi-ellipsis-v" @click="toggleMenu($event, slotProps.data)" 
                                    aria-haspopup="true" aria-controls="popup_menu" />
                            </div>
                        </template>
                    </Column>

                    <template #footer>
                        <div class="p-d-flex p-ai-center p-jc-between">
                            No total existem {{listaAdmProfile ? listaAdmProfile.length : 0 }} perfis.
                        </div>
                    </template>

                </DataTable>
            </div>

            <div :style="mostrarEditar()">
                <!-- <Toast /> -->
                <Panel header="Detalhes do perfil" class="p-mb-2">
                    <Toolbar class="mb-4">
                        <template v-slot:start>
                        </template>
                        <template v-slot:end>
                            <div class="my-2">
                                <Button label="Cancelar" icon="pi pi-times" class="p-button-secondary mr-2" @click="hideDialog"></button>
                                <Button label="Limpar" icon="pi pi-star-o" class="p-button-primary mr-2" @click="onClean"></button>
                                <Button label="Salvar" icon="pi pi-check" class="p-button-success" @click="onSave"></button>        
                            </div>
                        </template>
                    </Toolbar>         
                    <div class="card p-fluid">
                        <div class="field">
                            <label for="description">Descrição</label>
                            <InputText id="description" v-model="admProfile.description" required="true"
                                :class="{ 'p-invalid': submitted && !admProfile.description }" />
                            <small class="p-invalid" v-if="submitted && !admProfile.description">A descrição é obrigatória.</small>
                        </div>
                        <div class="field">
                            <label for="profilePages">Página(s):</label>
                            <PickList v-model="profilePages" dataKey="id">
                                <template #sourceheader>Disponível</template>
                                <template #targetheader>Selecionada</template>
                                <template #item="slotProps">
                                    <div>
                                        {{slotProps.item.description}}
                                    </div>
                                </template>
                            </PickList>                                
                        </div>
                    </div>               
                </Panel>                
            </div>

            <Dialog v-model:visible="deleteAdmProfileDialog" :style="{ width: '450px' }" header="Confirme" :modal="true">
                <div class="flex align-items-center justify-content-center">
                    <i class="pi pi-exclamation-triangle mr-3" style="font-size: 2rem" />
                    <span v-if="admProfile">Tem certeza de que deseja excluir <b>{{ admProfile.description }}</b>?</span>
                </div>
                <template #footer>
                    <Button label="Não" icon="pi pi-times" class="p-button-text" @click="deleteAdmProfileDialog = false" />
                    <Button label="Sim" icon="pi pi-check" class="p-button-text" @click="confirmDelete" />
                </template>
            </Dialog>

            <Dialog v-model:visible="deleteAdmProfilesDialog" :style="{ width: '450px' }" header="Confirme" :modal="true">
                <div class="flex align-items-center justify-content-center">
                    <i class="pi pi-exclamation-triangle mr-3" style="font-size: 2rem" />
                    <span v-if="admProfile">Tem certeza de que deseja excluir as categorias de parâmetros selecionadas?</span>
                </div>
                <template #footer>
                    <Button label="Não" icon="pi pi-times" class="p-button-text" @click="deleteAdmProfilesDialog = false" />
                    <Button label="Sim" icon="pi pi-check" class="p-button-text" @click="confirmDeleteSelected" />
                </template>
            </Dialog>
        </div>
    </div>
</template>

// frontend/hfs-frontend-react-next/app/(main)/admin/admProfile/page.tsx
/* eslint-disable @next/next/no-img-element */
'use client';
import { Button } from 'primereact/button';
import { Column } from 'primereact/column';
import { DataTable } from 'primereact/datatable';
import { Dialog } from 'primereact/dialog';
import { InputText } from 'primereact/inputtext';
import { Toast } from 'primereact/toast';
import { Toolbar } from 'primereact/toolbar';
import { classNames } from 'primereact/utils';
import React, { useEffect, useRef, useState } from 'react';
import AdmProfileService from '../service/AdmProfileService';
import { AdmProfile, cleanAdmProfile, emptyAdmProfile } from '../api/AdmProfile';
import { ReportParamForm, emptyReportParamForm } from '../../base/models/ReportParamsForm';
import { ItypeReport, PDFReport } from '../../base/services/ReportService';
import { Panel } from 'primereact/panel';
import ReportPanelComponent from '../../base/components/ReportPanel';
import { Menu } from 'primereact/menu';
import { MenuItem } from 'primereact/menuitem';
import { ExportService } from '../../base/services/ExportService';
import { PickList } from 'primereact/picklist';
import { AdmPage } from '../api/AdmPage';
import AdmPageService from '../service/AdmPageService';
import { CheckboxChangeEvent } from 'primereact/checkbox';

const AdmProfilePage = () => {

    const [admProfileService,] = useState<AdmProfileService>(new AdmProfileService());
    const admPageService = new AdmPageService();
    const exportService = new ExportService();

    const [listaAdmProfile, setListaAdmProfile] = useState<AdmProfile[]>([]);
    const [admProfileDialog, setAdmProfileDialog] = useState<boolean>(false);
    const [deleteAdmProfileDialog, setDeleteAdmProfileDialog] = useState<boolean>(false);
    const [deleteAdmProfilesDialog, setDeleteAdmProfilesDialog] = useState<boolean>(false);
    const [admProfile, setAdmProfile] = useState<AdmProfile>(emptyAdmProfile); 
    const [selectedAdmProfiles, setSelectedAdmProfiles] = useState<AdmProfile[]>([]);

    const [submitted, setSubmitted] = useState(false);
    const [cols, setCols] = useState<any[]>([]);
    const [exportColumns, setExportColumns] = useState<any[]>([]);
    const [globalFilter, setGlobalFilter] = useState('');
    const toast = useRef<Toast>(null);
    const dt = useRef<DataTable<any>>(null);

    const [selectedTypeReport, setSelectedTypeReport] = useState<ItypeReport>(PDFReport);
    const [selectedForceDownload, setSelectedForceDownload] = useState(true);
    const [reportParamForm, setReportParamForm] = useState<ReportParamForm>(emptyReportParamForm);    

    const [itemsMenuLinha, setItemsMenuLinha] = useState<MenuItem[]>([]);
    const popupMenu = useRef<Menu>(null);

    const [sourcePages, setSourcePages] = useState<AdmPage[]>([]);
    const [targetPages, setTargetPages] = useState<AdmPage[]>([]);

    useEffect(() => {  
        admProfileService.findAll().then(item => setListaAdmProfile(item));

        setItemsMenuLinha([{ label: "Editar" }, { label: "Excluir" }]);

        setCols([
            { field: 'id', header: 'Id' },
            { field: 'description', header: 'Descrição' },
            { field: 'profilePages', header: 'Páginas(s) do perfil' }
        ]);
            
        setExportColumns(cols.map(col => ({title: col.header, dataKey: col.field})));
      
    }, [admProfileService, cols]);

    const toggleMenu = (menu: React.RefObject<Menu>, event: any, rowData: AdmProfile) => {
        setItemsMenuLinha([]);

        let _itemsMenuLinha: MenuItem[] = [];

        _itemsMenuLinha.push({
            label: 'Editar',
            command: () => {
                onEdit(rowData);
            }
        });

        _itemsMenuLinha.push({
            label: 'Excluir',
            command: () => {
                onDelete(rowData);
            }
        });

        setItemsMenuLinha(_itemsMenuLinha);

        if (menu.current){
            menu.current.toggle(event);
        }  
    }
    
    const loadAdmPages = (profile: AdmProfile) => {
        let _targetPages: AdmPage[] = [];

        if (profile.id != null) {
            _targetPages = profile.admPages;
            setTargetPages(_targetPages);
        }
        admPageService.findAll().then(pages => {
            setSourcePages(pages.filter(page => !_targetPages.find(target => target.id === page.id)));
        });
    }

    const mostrarListar = () => {
        if (admProfileDialog)
            return { display: 'none' };
        else
            return { display: '' };
    }

    const mostrarEditar = () => {
        if (admProfileDialog)
            return { display: '' };
        else
            return { display: 'none' };
    }

    const onClean = () => {
        setAdmProfile(cleanAdmProfile);
        loadAdmPages(cleanAdmProfile);
    }

    const onInsert = () => {
        setAdmProfile(emptyAdmProfile);
        setSubmitted(false);      
        setAdmProfileDialog(true);
        loadAdmPages(emptyAdmProfile);
    }
    
    const onEdit = (admProfile: AdmProfile) => {
        setAdmProfile({ ...admProfile });
        setAdmProfileDialog(true);
        loadAdmPages(admProfile);
    }
    
    const hideDialog = () => {
        setAdmProfileDialog(false);
        setSubmitted(false);
    }

    const hideDeleteAdmProfileDialog = () => {
        setDeleteAdmProfileDialog(false);
    };

    const hideDeleteAdmProfilesDialog = () => {
        setDeleteAdmProfilesDialog(false);
    };

    const onSave = () => {
        setSubmitted(true);
        admProfile.admPages = [];
        targetPages.forEach(item => {
            admProfile.admPages.push(item)
        });
            
        if (admProfile.description.trim()) {
            let _listaAdmProfile = [...listaAdmProfile];
            let _admProfile = {...admProfile};

            if (admProfile.id) {
                admProfileService.update(admProfile).then((obj: AdmProfile) => {
                    _admProfile = obj;
                    
                    if (admProfile.id) {
                        const index = admProfileService.findIndexById(listaAdmProfile, admProfile.id);
                        _listaAdmProfile[index] = _admProfile;
    
                        setListaAdmProfile(_listaAdmProfile);
                        toast.current?.show({ severity: 'success', summary: 'Sucesso', detail: 'Perfil Atualizado', life: 3000 });    
                    }
                });
            } else {
                admProfileService.insert(admProfile).then((obj: AdmProfile) => {
                    _admProfile = obj;
                    _listaAdmProfile.push(_admProfile);
                    setListaAdmProfile(_listaAdmProfile);
                    toast.current?.show({ severity: 'success', summary: 'Sucesso', detail: 'Perfil Criada', life: 3000 });
                });
            }
            
            setAdmProfileDialog(false);
            setAdmProfile(emptyAdmProfile);            
        }
    }
        
    const deleteSelected = () => {
        setDeleteAdmProfilesDialog(true);
    }
  
    const onDelete = (admProfile: AdmProfile) => {
        setDeleteAdmProfileDialog(true);
        setAdmProfile({ ...admProfile });
    } 
  
    const confirmDeleteSelected = () => {
        setDeleteAdmProfilesDialog(false);
        setListaAdmProfile(listaAdmProfile.filter(val => !selectedAdmProfiles.includes(val)));
  
        let excluiu = false;
        selectedAdmProfiles.forEach((item) => {
            if (item.id) {
                admProfileService.delete(item.id).then(obj => {
                    excluiu = true;
                });    
            }
        });
    
        if (excluiu) {
            toast.current?.show({ severity: 'success', summary: 'Sucesso', detail: 'Perfis excluídos', life: 3000 });
            setSelectedAdmProfiles([]);
        }
    }
  
    const confirmDelete = () => {
        setDeleteAdmProfileDialog(false);
        if (admProfile.id){
            admProfileService.delete(admProfile.id).then(obj => {
                setListaAdmProfile(listaAdmProfile.filter(val => val.id !== admProfile.id));
                setAdmProfile(emptyAdmProfile); 
                toast.current?.show({ severity: 'success', summary: 'Sucesso', detail: 'Perfil excluído', life: 3000 });
            });    
        }
    }
  
    const onChangedTypeReport = (typeReport: ItypeReport) => {
        setSelectedTypeReport(typeReport);
        setReportParamForm({ reportType: typeReport.type, 
          forceDownload: selectedForceDownload });
    }
    
    const onChangedForceDownload = (event: CheckboxChangeEvent) => {
        const forceDownload = event.checked;
        if (forceDownload){
            setSelectedForceDownload(forceDownload);
            setReportParamForm({ reportType: selectedTypeReport.type, 
              forceDownload: forceDownload });    
        }
    }
    
    const onExport = () => {
        admProfileService.report(reportParamForm).then(() => {
          toast.current?.show({ severity: 'info', summary: 'Perfil exportado', 
            detail: 'Perfil exportado', life: 3000 });
        });
    }

    const exportPdf = () => {
        const head: string[] = [];
        const data: any[] = [];
    
        exportColumns.forEach(item => head.push(item.title));
        listaAdmProfile.forEach((item: AdmProfile) => data.push(
            [item.id, item.description, item.profilePages]
        ));
    
        exportService.exportPdf(head, data, 'Parametros.pdf');
      }
    
    const exportExcel = () => {
        exportService.exportExcel(listaAdmProfile, 'Parâmetros');
    }

    const onDescriptionInputChange = (e: React.FormEvent<HTMLInputElement>) => {
        const val = (e.target && e.currentTarget.value) || '';
        let _admProfile = { ...admProfile };
        _admProfile.description = val;

        setAdmProfile(_admProfile);
    };

    const leftToolbarTemplate = () => {
        return (
            <React.Fragment>
                <div className="my-2">
                    <Button label="Adicionar" icon="pi pi-plus" severity="success" className=" mr-2" onClick={onInsert} />
                    <Button label="Excluir" icon="pi pi-trash" severity="danger" onClick={deleteSelected} 
                        disabled={!selectedAdmProfiles || !(selectedAdmProfiles as any).length} />
                </div>
            </React.Fragment>
        );
    };

    const rightToolbarTemplate = () => {
        return (
            <React.Fragment>
                <Button label="Exportar" icon="pi pi-upload" className="p-button-help" onClick={onExport} />
            </React.Fragment>
        );
    };

    const leftEditToolbarTemplate = () => {
        return (
            <React.Fragment>
            </React.Fragment>
        );
    };

    const rightEditToolbarTemplate = () => {
        return (
            <React.Fragment>
                <Button label="Cancelar" icon="pi pi-times" className="p-button-secondary mr-2" onClick={hideDialog} />
                <Button label="Limpar" icon="pi pi-star-o" className="p-button-primary mr-2" onClick={onClean} />
                <Button label="Salvar" icon="pi pi-check" className="p-button-success" onClick={onSave} />
            </React.Fragment>
        );
    };


    const tabelaHeader = (
        <div className="flex flex-column md:flex-row md:justify-content-between md:align-items-center">
            <h5 className="m-0">Gerenciar perfis</h5>
            <span className="block mt-2 md:mt-0 p-input-icon-left">
                <i className="pi pi-search" />
                <InputText type="search" onInput={(e) => setGlobalFilter(e.currentTarget.value)} placeholder="Procurar..." />
            </span>
        </div>
    );

    const tabelaFooter = (
        <div className="p-d-flex p-ai-center p-jc-between">
            No total existem {listaAdmProfile ? listaAdmProfile.length : 0 } perfis.
        </div>
    );

    const idBodyTemplate = (rowData: AdmProfile) => {
        return (
            <>
                <span className="p-column-title">Id</span>
                {rowData.id}
            </>
        );
    };    

    const profilePagesBodyTemplate = (rowData: AdmProfile) => {
        return (
            <>
                <span className="p-column-title">Páginas(s) do perfil</span>
                {rowData.profilePages}
            </>
        );
    };    

    const descriptionBodyTemplate = (rowData: AdmProfile) => {
        return (
            <>
                <span className="p-column-title">Descrição</span>
                {rowData.description}
            </>
        );
    };    

    const actionBodyTemplate = (rowData: AdmProfile) => {
        if (rowData){            
            return (
                <>
                    <div className="flex">                        
                        <Button link icon="pi pi-ellipsis-v" onClick={(event) => toggleMenu(popupMenu, event, rowData)} style={{ cursor: 'pointer' }} 
                            aria-controls="popup_menu" aria-haspopup />                            
                    </div>
                </>
            );
        }
    };

    const onProfilePagesChange = (event: { 
        source: React.SetStateAction<AdmPage[]>; 
        target: React.SetStateAction<AdmPage[]>; }) => {
        setSourcePages(event.source);
        setTargetPages(event.target);
    }    

    const itemTemplate = (item: AdmPage) => {
        return (
          <div>
              {item.description}
          </div>
        );
    }
        
    const deleteAdmProfileDialogFooter = (
        <>
            <Button label="Não" icon="pi pi-times" text onClick={hideDeleteAdmProfileDialog} />
            <Button label="sim" icon="pi pi-check" text onClick={confirmDelete} />
        </>
    );
    
    const deleteAdmProfilesDialogFooter = (
        <>
            <Button label="Não" icon="pi pi-times" text onClick={hideDeleteAdmProfilesDialog} />
            <Button label="Sim" icon="pi pi-check" text onClick={confirmDeleteSelected} />
        </>
    );

    return (
        <div className="grid crud-demo">
            <div className="col-12">
                <div className="card px-6 py-6" style={mostrarListar()}>
                    <Toast ref={toast} />
                    <Panel header="Perfil" className="p-mb-2">
                        <ReportPanelComponent typeReportChange={e => onChangedTypeReport(e.value)}
                            forceDownloadChange={e => onChangedForceDownload(e)}
                        ></ReportPanelComponent>
                    </Panel>

                    <Toolbar className="mb-4" start={leftToolbarTemplate} end={rightToolbarTemplate}></Toolbar>

                    <Menu model={itemsMenuLinha} popup ref={popupMenu} id="popup_menu" popupAlignment="right" />

                    <DataTable ref={dt} value={listaAdmProfile} selection={selectedAdmProfiles} paginatorPosition="both"
                        onSelectionChange={(e) => setSelectedAdmProfiles(e.value as any)}
                        dataKey="id" paginator rows={10} rowsPerPageOptions={[10,30,50,100,150,200]} className="datatable-responsive"
                        paginatorTemplate="FirstPageLink PrevPageLink PageLinks NextPageLink LastPageLink CurrentPageReport RowsPerPageDropdown"
                        currentPageReportTemplate="Mostrando {first} até {last} de {totalRecords} entradas" 
                        globalFilter={globalFilter} emptyMessage="Nenhum registro encontrado."
                        header={tabelaHeader} footer={tabelaFooter} responsiveLayout="scroll"
                    >
                        <Column selectionMode="multiple" headerStyle={{ width: '4rem' }}></Column>
                        <Column field="id" header="Id" sortable headerStyle={{ width: '5%', minWidth: '5rem' }} body={idBodyTemplate}></Column>
                        <Column field="description" header="Descrição" sortable headerStyle={{ minWidth: '8rem' }} body={descriptionBodyTemplate}></Column>
                        <Column field="profilePages" header="Páginas(s) do perfil" sortable headerStyle={{ minWidth: '8rem' }} body={profilePagesBodyTemplate}></Column>                        
                        <Column body={actionBodyTemplate} headerStyle={{ minWidth: '10rem' }}></Column>
                    </DataTable>
                </div>

                <div className="card px-6 py-6" style={mostrarEditar()}>
                    <Toast ref={toast} />
                    <Panel header="Detalhes do perfil" className="p-mb-2">
                        <Toolbar className="mb-4" start={leftEditToolbarTemplate} end={rightEditToolbarTemplate}></Toolbar>
                    </Panel>
                    <div className="card p-fluid">
                        <div className="field">
                            <label htmlFor="description">Descrição</label>
                            <InputText id="description" value={admProfile.description} onChange={(e) => onDescriptionInputChange(e)} required
                                className={classNames({'p-invalid': submitted && !admProfile.description})}
                            />
                            {submitted && !admProfile.description && <small className="p-invalid">A descrição é obrigatória.</small>}
                        </div>
                        <div className="field">
                            <label htmlFor="profilePages">Página(s):</label>
                            <PickList source={sourcePages} target={targetPages} itemTemplate={itemTemplate}
                                sourceHeader="Disponível" targetHeader="Selecionada"
                                sourceStyle={{height:'30rem'}} targetStyle={{height:'30rem'}} onChange={onProfilePagesChange}>
                            </PickList>                            
                        </div>    
                    </div>
                </div>                

                <Dialog visible={deleteAdmProfileDialog} style={{ width: '450px' }} header="Confirm" modal 
                    footer={deleteAdmProfileDialogFooter} onHide={hideDeleteAdmProfileDialog}>
                    <div className="flex align-items-center justify-content-center">
                        <i className="pi pi-exclamation-triangle mr-3" style={{ fontSize: '2rem' }} />
                        {admProfile && (
                            <span>
                                Tem certeza de que deseja excluir <b>{admProfile.description}</b>?
                            </span>
                        )}
                    </div>
                </Dialog>

                <Dialog visible={deleteAdmProfilesDialog} style={{ width: '450px' }} header="Confirm" modal 
                    footer={deleteAdmProfilesDialogFooter} onHide={hideDeleteAdmProfilesDialog}>
                    <div className="flex align-items-center justify-content-center">
                        <i className="pi pi-exclamation-triangle mr-3" style={{ fontSize: '2rem' }} />
                        {admProfile && <span>Tem certeza de que deseja excluir as categorias de parâmetros selecionadas?</span>}
                    </div>
                </Dialog>

            </div>
        </div>
    );
};

export default AdmProfilePage;
