// frontend/hfs-frontend-vuetify/src/hfsfullstack/pages/Funcionario.vue
<script lang="ts">
import { ref, onMounted, onBeforeMount, shallowRef, watch } from 'vue';
import { ReportParamForm, emptyReportParamForm } from '../../base/models/ReportParamsForm';
import { ItypeReport, PDFReport, SelectItemGroup } from '../../base/services/ReportService';
import { SnackbarMessage, emptySnackbarMessage } from '../../base/models/SnackbarMessage';
import { Funcionario, cleanFuncionario, emptyFuncionario } from '../api/funcionario';
import FuncionarioService from '../service/FuncionarioService';
import { ExportService } from '../../base/services/ExportService';
import { DataTableFilterMeta, LazyTableParam, emptyLazyTableParam } from '../../base/models/LazyTableParam';
import { PaginationDTO } from '../../base/models/PaginationDTO';

export default {
    setup() {
        const snackbar = ref<SnackbarMessage>(emptySnackbarMessage);

        const listaFuncionario = ref<Funcionario[]>([]);
        const funcionarioDialog = shallowRef(false)
        const deleteFuncionarioDialog = ref(false);
        const deleteFuncionariosDialog = ref(false);
        const funcionario = ref(emptyFuncionario);
        const selectedFuncionarios = ref<number[]>([]);
        const submitted = ref(false);

        const funcionarioService = new FuncionarioService();
        const exportService = new ExportService();
        //const baseUtilService = new BaseUtilService();

        const selectedTypeReport = ref<ItypeReport>();
        const selectedForceDownload = ref(true);
        const reportParamForm = ref<ReportParamForm>(emptyReportParamForm);

        const itemsPerPage = ref(10);
        const columns = ref();        
        const exportColumns = ref([]);
        const loading = ref(true);
        const totalItems = ref(0);
        const search = ref('');
        const form = ref();
        const nomePesquisa = ref('')

        const filters = ref<DataTableFilterMeta>({
            global: { value: '', matchMode: 'contains' },
            'nome': {value: '', matchMode: 'startsWith'},
        });        

        const lazyParams = ref<LazyTableParam>(emptyLazyTableParam);

        onBeforeMount(() => {
            columns.value = [
                { key: 'actions', title: "Ações", sortable: false, minWidth: '5rem' },
                { key: 'id', title: 'Código', sortable: true, align: 'start', minWidth: '5rem' },
                { key: 'nome', title: 'Nome', sortable: true, align: 'start', minWidth: '30rem' },
                { key: 'cpfFormatado', title: 'Cpf', sortable: true, align: 'start', minWidth: '10rem' },
                { key: 'email', title: 'Email', sortable: true, align: 'start', minWidth: '10rem' },
                { key: 'telefone', title: 'Telefone', sortable: true, align: 'start', minWidth: '10rem' },
                { key: 'celular', title: 'Celular', sortable: true, align: 'start', minWidth: '20rem' },
                { key: 'setor', title: 'Setor', sortable: true, align: 'start', minWidth: '10rem' },
                { key: 'codCargo', title: 'CodCargo', type: 'number', sortable: true, align: 'start', minWidth: '10rem' },
                { key: 'cargo', title: 'Cargo', sortable: true, align: 'start', minWidth: '20rem' },
                { key: 'dataAdmissaoFormatada', title: 'Data Admissão', sortable: true, align: 'start', minWidth: '10rem' },
                { key: 'dataSaidaFormatada', title: 'Data Saída', sortable: true, align: 'start', minWidth: '10rem' },
                { key: 'ativo', title: 'Ativo', minWidth: '10rem' }
            ];
        });

        onMounted(() => {
            selectedTypeReport.value = PDFReport.value;
            exportColumns.value = columns.value.map((col: { header: any; field: any; }) => ({title: col.header, dataKey: col.field}));
        });

        const loadFuncionarios = ({ page, itemsPerPage, sortBy }) => { 
            loading.value = true;

            let sortField: string | null = null;
            let sortOrder: number | null = null;

            if (sortBy.length > 0) {
                sortField = sortBy[0].key;
                sortOrder = sortBy[0].order === 'asc' ? 1 : 0;
            }

            lazyParams.value = {
                first: page,
                rows: itemsPerPage,
                sortField: sortField,
                sortOrder: sortOrder,
                filters: { 'nome': {value: nomePesquisa, matchMode: 'startsWith'} }
            };

            funcionarioService.findAllPaginated(lazyParams.value).then((data: PaginationDTO) => {
                listaFuncionario.value = data.content;
                totalItems.value = data.totalElements;
                loading.value = false;
            });
        }      
        
        watch(nomePesquisa, () => {
            search.value = String(Date.now())
        })

        const snackBar = (msg: string, duration: number) => {
            snackbar.value.open = true;
            snackbar.value.message = msg;
            snackbar.value.timeout = duration;
        }

        const mostrarListar = () => {
            if (funcionarioDialog.value)
                return { display: 'none' };
            else
                return { display: '' };
        }

        const mostrarEditar = () => {
            if (funcionarioDialog.value)
                return { display: '' };
            else
                return { display: 'none' };
        }

        const onInsert = () => {
            funcionario.value = emptyFuncionario;
            submitted.value = false;
            funcionarioDialog.value = true;
        };

        const onEdit = (param: Funcionario) => {
            funcionario.value = { ...param };
            funcionarioDialog.value = true;
        };

        const hideDialog = () => {
            funcionarioDialog.value = false;
            submitted.value = false;
        };

        const onClean = () => {
            funcionario.value = cleanFuncionario;
        }

        const onSave = () => {
            submitted.value = true;
            /*
            if (funcionario.cpfFormatado){
                funcionario.cpf = baseUtilService.cpfFormatadoParaCpf(funcionario.cpfFormatado);
            }
            if (funcionario.dataAdmissaoFormatada){
                funcionario.dataAdmissao = baseUtilService.dataStringToDate(funcionario.dataAdmissaoFormatada);
            }
            if (funcionario.dataSaidaFormatada){
                funcionario.dataSaida = baseUtilService.dataStringToDate(funcionario.dataSaidaFormatada);
            } 
            */       

            if (funcionario.value.nome && funcionario.value.nome.trim()) {
                if (funcionario.value.id) {
                    funcionarioService.update(funcionario.value).then((obj: Funcionario) => {
                        funcionario.value = obj;

                        if (funcionario.value.id){
                            const index = funcionarioService.findIndexById(listaFuncionario.value, funcionario.value.id);
                            listaFuncionario.value[index] = funcionario.value;
                            snackBar('Funcionário Atualizado', 3000);
                        }
                    });            
                } else {
                    funcionarioService.insert(funcionario.value).then((obj: Funcionario) => {
                        funcionario.value = obj;

                        listaFuncionario.value.push(funcionario.value);
                        snackBar('Funcionário Criado', 3000);
                    });            
                }

                funcionarioDialog.value = false;
                funcionario.value = emptyFuncionario;
            }
        };

        const deleteSelected = () => {
            deleteFuncionariosDialog.value = true;
        }

        const onDelete = (param: Funcionario) => {
            deleteFuncionarioDialog.value = true;
            funcionario.value = { ...param };
        } 

        const confirmDeleteSelected = () => {            
            deleteFuncionariosDialog.value = false;
            
            let selecionados: Funcionario[] = [];
            listaFuncionario.value.forEach((item: Funcionario) => {
                selectedFuncionarios.value.forEach((id: number) => {
                    if (item.id === id){
                        selecionados.push(item);
                    }
                });        
            });

            if (selecionados.length > 0){
                listaFuncionario.value = listaFuncionario.value.filter(
                    (val: Funcionario) => !selecionados.includes(val));

                    selecionados.forEach((item: Funcionario, index: number) => {
                    if (item.id){
                        funcionarioService.delete(item.id).then(() => {

                            if (selecionados.length == (index+1)){
                                snackBar('Funcionários excluídos', 3000);
                                selectedFuncionarios.value = [];
                            }

                        });
                    }
                });

            }
        }

        const confirmDelete = () => {
            deleteFuncionarioDialog.value = false;
            if (funcionario.value.id){
                funcionarioService.delete(funcionario.value.id).then(() => {
                    listaFuncionario.value = listaFuncionario.value.filter((val: Funcionario) => val.id !== funcionario.value.id);
                    funcionario.value = emptyFuncionario;        
                    snackBar('Funcionário excluído', 3000);
                });
            }    
        }

        const onTypeReportChange = (param: { pTypeReport: SelectItemGroup }) => {            
            if (param.pTypeReport.value){
                selectedTypeReport.value = param.pTypeReport.value;
                reportParamForm.value = { reportType: param.pTypeReport.value.type, forceDownload: selectedForceDownload.value };
            }        
        }

        const onForceDownloadChange = (param: { forceDownload: boolean }) => {
            selectedForceDownload.value = param.forceDownload;
            if (selectedTypeReport.value){
                reportParamForm.value = { reportType: selectedTypeReport.value.type, forceDownload: param.forceDownload };
            }
        }

        const onExport = () => {
            funcionarioService.report(reportParamForm.value).then(() => {
                snackBar('Funcionário exportado', 3000);
            });            
        }

        const exportPdf = () => {
            const head: string[] = [];
            const data: any[] = [];

            exportColumns.value.forEach(item => head.push(item.title));
            listaFuncionario.value.forEach(item => data.push(
                [item.id, item.nome, item.cpfFormatado, item.email, item.telefone, item.celular, 
                item.setor, item.codCargo, item.cargo, item.dataAdmissaoFormatada, item.dataSaidaFormatada, item.ativo]
            ));

            exportService.exportPdf(head, data, 'funcionarios.pdf');
        }
        
        const exportExcel = () => {
            exportService.exportExcel(listaFuncionario.value, 'funcionarios');
        }    

        return { listaFuncionario, funcionario, submitted, mostrarListar, mostrarEditar, loadFuncionarios,
            selectedFuncionarios, deleteSelected, funcionarioDialog, hideDialog, onClean, nomePesquisa,
            deleteFuncionarioDialog, confirmDelete, deleteFuncionariosDialog, exportExcel, exportPdf,
            onInsert, onEdit, onDelete, onSave, onExport, onTypeReportChange, onForceDownloadChange,
            confirmDeleteSelected, itemsPerPage, columns, loading, totalItems, search, snackbar }
    }
}        
</script>

<template>
    <div class="grid">
        <div class="col-12">
            <v-snackbar v-model="snackbar.open" :timeout="snackbar.timeout" location="top">
                {{ snackbar.message }}
                <template v-slot:actions>
                    <v-btn color="red" density="compact" icon="close" @click="snackbar.open = false"></v-btn>
                </template>
            </v-snackbar>

            <div class="card px-6 py-6" :style="mostrarListar()">
                <v-card-item>
                    <v-card-title>Funcionário</v-card-title>
                </v-card-item>
                <v-card-text>
                    <ReportPanel @changeTypeReport="onTypeReportChange" @changeForceDownload="onForceDownloadChange"></ReportPanel>
                </v-card-text>

                <v-toolbar>
                    <v-btn prepend-icon="add" @click="onInsert" variant="elevated" color="green" :style="{ marginRight: '10px' }">Adicionar</v-btn>
                    <v-btn prepend-icon="delete" @click="deleteSelected" variant="elevated" color="red"
                        :disabled="!selectedFuncionarios || !selectedFuncionarios.length" :style="{ marginRight: '10px' }">Excluir</v-btn>
                        
                    <span class="spacer"></span>
                        
                    <v-btn icon="description" @click="exportExcel" variant="elevated"></v-btn>
                    <v-btn icon="picture_as_pdf" @click="exportPdf" variant="elevated"></v-btn>

                    <span class="spacer"></span>

                    <v-btn prepend-icon="upload" @click="onExport" variant="elevated" color="indigo-darken-3">Exportar</v-btn>
                </v-toolbar>

                <v-toolbar>
                    <span class="spacer"></span>
                    <v-text-field v-model="nomePesquisa" class="ma-2" density="compact" 
                        placeholder="Pesquisar nome..." hide-details style="max-width: 300px">
                    </v-text-field>
                </v-toolbar>

                <v-data-table-server
                    v-model="selectedFuncionarios"
                    v-model:items-per-page="itemsPerPage"
                    :headers="columns"
                    :items="listaFuncionario"
                    :items-length="totalItems"
                    :loading="loading"
                    loading-text="Carregando, por favor espere"
                    :search="search"
                    item-value="id"
                    show-select
                    @update:options="loadFuncionarios"
                    :sort-by="[{ key: 'id', order: 'asc' }]">

                    <template v-slot:item.actions="{ item }">
                        <v-icon class="me-2" size="small" @click="onEdit(item)">edit</v-icon>
                        <v-icon size="small" @click="onDelete(item)">delete</v-icon>
                    </template>
                    
                </v-data-table-server>
            </div>    

            <div :style="mostrarEditar()">
                <v-card-item>
                    <v-card-title>Funcionário</v-card-title>
                </v-card-item>
                <v-card-text>
                    <v-toolbar>
                        <v-spacer></v-spacer>
                        <v-btn prepend-icon="cancel" color="secondary" :style="{ marginRight: '10px' }" @click="hideDialog" variant="elevated">Cancelar</v-btn>
                        <v-btn prepend-icon="star" color="secondary" :style="{ marginRight: '10px' }" @click="onClean" variant="elevated">Limpar</v-btn>
                        <v-btn prepend-icon="check" color="primary" @click="onSave" variant="elevated">Salvar</v-btn>
                    </v-toolbar>                

                    <v-form ref="form">
                        <v-container>
                            <v-row>
                                <v-col cols="12">
                                    <v-text-field label="Descrição" v-model="funcionario.nome" required autofocus
                                        :class="{ 'text-red': submitted && !funcionario.nome }">
                                    </v-text-field>
                                </v-col>
                            </v-row>
                            <v-row v-if="submitted && !funcionario.nome">
                                <v-col cols="12">
                                    <small class="text-red" v-if="submitted && !funcionario.nome">O nome é obrigatório.</small>
                                </v-col>                                    
                            </v-row>
                            <v-row>
                                <v-col cols="12">
                                    <v-text-field label="Email" v-model="funcionario.email"></v-text-field>
                                </v-col>                                
                            </v-row>
                            <v-row>
                                <v-col cols="6" md="6">
                                    <v-text-field label="Cpf" v-model="funcionario.cpfFormatado" required
                                        :class="{ 'text-red': submitted && !funcionario.cpfFormatado }">
                                    </v-text-field>
                                    <small class="text-red" v-if="submitted && !funcionario.cpfFormatado">O Cpf é obrigatório.</small>
                                </v-col>
                                <v-col cols="6" md="6">
                                    <v-text-field label="Telefone" v-model="funcionario.telefone"></v-text-field>
                                </v-col>
                            </v-row>
                            <v-row>
                                <v-col cols="6" md="6">
                                    <v-text-field label="Celular" v-model="funcionario.celular"></v-text-field>
                                </v-col>
                                <v-col cols="6" md="6">
                                    <v-text-field label="Setor" v-model="funcionario.setor"></v-text-field>
                                </v-col>
                            </v-row>
                            <v-row>
                                <v-col cols="6" md="6">
                                    <v-text-field type="number" label="CodCargo" v-model="funcionario.codCargo"></v-text-field>
                                </v-col>
                                <v-col cols="6" md="6">
                                    <v-text-field label="Cargo" v-model="funcionario.cargo"></v-text-field>
                                </v-col>
                            </v-row>
                            <v-row>
                                <v-col cols="6" md="6">
                                    <v-text-field type="date" label="Data Admissão" v-model="funcionario.dataAdmissao"></v-text-field>
                                </v-col>
                                <v-col cols="6" md="6">
                                    <v-text-field type="date" label="Data Saída" v-model="funcionario.dataSaida"></v-text-field>
                                </v-col>
                            </v-row>
                            <v-row>
                                <v-checkbox v-model="funcionario.ativo" label="Ativo"></v-checkbox>
                            </v-row>                            
                        </v-container>
                    </v-form>
                </v-card-text>
            </div>
        
            <v-dialog v-model="deleteFuncionarioDialog" max-width="450" persistent>
                <v-card prepend-icon="warning" title="Confirme">
                    <v-card-text>
                        <span v-if="funcionario">Tem certeza de que deseja excluir <b>{{ funcionario.nome }}</b>?</span>
                    </v-card-text>                        
                    <template v-slot:actions>
                        <v-spacer></v-spacer>
                        <v-btn prepend-icon="cancel" color="secondary" :style="{ marginRight: '10px' }" 
                            @click="deleteFuncionarioDialog = false" variant="elevated">Não</v-btn>
                        <v-btn prepend-icon="check" color="primary" @click="confirmDelete" variant="elevated">Sim</v-btn>
                    </template>
                </v-card>
            </v-dialog>

            <v-dialog v-model="deleteFuncionariosDialog" max-width="450" persistent>
                <v-card prepend-icon="warning" title="Confirme">
                    <v-card-text>
                        <span v-if="funcionario">Tem certeza de que deseja excluir os funcionários selecionados?</span>
                    </v-card-text>                        
                    <template v-slot:actions>
                        <v-spacer></v-spacer>
                        <v-btn prepend-icon="cancel" color="secondary" :style="{ marginRight: '10px' }" 
                            @click="deleteFuncionariosDialog = false" variant="elevated">Não</v-btn>
                        <v-btn prepend-icon="check" color="primary" @click="confirmDeleteSelected" variant="elevated">Sim</v-btn>
                    </template>
                </v-card>
            </v-dialog>

        </div>
    </div>
</template>

<style>
.spacer {
    flex: 1 1 auto;
}
</style>import { Funcionario, emptyFuncionario } from '../api/funcionario';
import FuncionarioService from '../service/FuncionarioService';import { Funcionario, emptyFuncionario } from '../api/funcionario';
import FuncionarioService from '../service/FuncionarioService';

// frontend/hfs-frontend-jest/src/app/hfsfullstack/pages/funcionario/funcionario.component.ts
import { Component, OnInit } from '@angular/core';
import { MessageService } from 'primeng/api';
import { Funcionario, cleanFuncionario } from '../../api/funcionario';
import { FuncionarioService } from '../../service/funcionario.service';
import { LazyLoadEvent } from 'primeng/api';
import { ItypeReport } from '../../../base/services/ReportService';
import { ReportParamForm } from '../../../base/models/ReportParamsForm';
import { ExportService } from '../../../base/services/export.service';
import { BaseUtilService } from '../../../base/util/base-util.service';

@Component({
    templateUrl: './funcionario.component.html',
    providers: [MessageService, ExportService, FuncionarioService, BaseUtilService]
})
export class FuncionarioComponent implements OnInit {

    funcionarioDialog: boolean = false;

    deleteFuncionarioDialog: boolean = false;

    deleteFuncionariosDialog: boolean = false;

    listaFuncionario: Funcionario[] = [];

    funcionario: Funcionario = {};

    selectedFuncionario: Funcionario[] = [];

    submitted: boolean = false;

    cols: any[];

    exportColumns: any[];
  
    reportParamForm: ReportParamForm;
  
    rowsPerPageOptions = [5, 10, 30, 50, 100, 150, 200];

    totalRecords!: number;

    loading: boolean = false;

    selectAll: boolean = false;

    constructor(private funcionarioService: FuncionarioService, 
        private messageService: MessageService,
        private exportService: ExportService,
        private baseUtilService: BaseUtilService) { }

    ngOnInit() {
        this.cols = [
            { field: 'id', header: 'Código' },
            { field: 'nome', header: 'Nome' },
            { field: 'cpfFormatado', header: 'Cpf' },
            { field: 'email', header: 'Email' },
            { field: 'telefone', header: 'Telefone' },
            { field: 'celular', header: 'Celular' },
            { field: 'setor', header: 'Setor' },
            { field: 'codCargo', header: 'CodCargo' },
            { field: 'cargo', header: 'Cargo' },
            { field: 'dataAdmissaoFormatada', header: 'Data Admissão' },
            { field: 'dataSaidaFormatada', header: 'Data Saída' },
            { field: 'ativo', header: 'Ativo' }
        ];

        this.exportColumns = this.cols.map(col => ({title: col.header, dataKey: col.field}));

        this.loading = true;
    }

    loadFuncionarios(event: LazyLoadEvent) {        
        this.loading = true;

        let nome: string = "";
        let page: number = 0;

        page = event.first / event.rows;
        
        if(event.sortField === undefined){
            event.sortField = 'id';
        }

        if (event.filters['nome'] !== undefined){
            nome = event.filters['nome'].value;
        }

        this.funcionarioService.findAllPaginated(nome,
            page, event.rows, event.sortField,
            event.sortOrder === 1 ? 'asc' : 'desc'
        ).then((data) => {
            this.listaFuncionario = data['content'];
            this.totalRecords = data['totalElements'];
            this.loading = false;
        });

    }        

    onSelectionChange(value = []) {
        this.selectAll = value.length === this.totalRecords;
        this.selectedFuncionario = value;
    }

    onSelectAllChange(event: any) {
        const checked = event.checked;

        if (checked) {
            this.funcionarioService.findAll().then((res) => {
                this.selectedFuncionario = res;
                this.selectAll = true;
            });
        } else {
            this.selectedFuncionario = [];
            this.selectAll = false;
        }
    }

    mostrarListar() {
        if (this.funcionarioDialog)
            return {display:'none'};
        else
            return {display:''};
    }

    mostrarEditar() {
        if (this.funcionarioDialog)
            return {display:''};
        else
            return {display:'none'};
    }
    
    onClean() {
        this.funcionario = cleanFuncionario;
    }

    onSave() {
        this.submitted = true;
        this.funcionario.cpf = this.baseUtilService.cpfFormatadoParaCpf(this.funcionario.cpfFormatado);
        this.funcionario.dataAdmissao = this.baseUtilService.dataStringToDate(this.funcionario.dataAdmissaoFormatada);
        this.funcionario.dataSaida = this.baseUtilService.dataStringToDate(this.funcionario.dataSaidaFormatada);

        if (this.funcionario.nome.trim()) {
            if (this.funcionario.id) {
                this.funcionarioService.update(this.funcionario).then((obj: Funcionario) => {
                this.funcionario = obj;

                this.listaFuncionario[
                    this.funcionarioService.findIndexById(this.listaFuncionario, this.funcionario.id)] = this.funcionario;
                this.messageService.add({ severity: 'success', summary: 'Sucesso', detail: 'Funcionário Atualizado', life: 3000 });
                });
            } else {
                this.funcionarioService.insert(this.funcionario).then((obj: Funcionario) => {
                this.funcionario = obj;

                this.listaFuncionario.push(this.funcionario);
                this.messageService.add({ severity: 'success', summary: 'Sucesso', detail: 'Funcionário Criado', life: 3000 });
                });
            }

            this.listaFuncionario = [...this.listaFuncionario];
            this.funcionarioDialog = false;
            this.funcionario = {};
        }
    }

    onChangedTypeReport(typeReport: ItypeReport) {
        this.reportParamForm.reportType = typeReport.type;
    }

    onChangedForceDownload(forceDownload: boolean) {
        this.reportParamForm.forceDownload = forceDownload;
    }

    onExport() {
        this.funcionarioService.report(this.reportParamForm).then(() => {
            this.messageService.add({severity: 'info', summary: 'Funcionário Exportado', detail: 'Funcionário Exportado', life: 1000});
        });
    }

    onInsert() {
        this.funcionario = {};
        this.submitted = false;
        this.funcionarioDialog = true;
    }

    onEdit(funcionario: Funcionario) {
        this.funcionario = { ...funcionario };
        this.funcionarioDialog = true;
    }
    
    hideDialog() {
        this.funcionarioDialog = false;
        this.submitted = false;
    }

    deleteSelected() {
        this.deleteFuncionariosDialog = true;
    }

    onDelete(funcionario: Funcionario) {
        this.deleteFuncionarioDialog = true;
        this.funcionario = { ...funcionario };
    }

    confirmDeleteSelected() {    
        this.deleteFuncionariosDialog = false;
        this.listaFuncionario = this.listaFuncionario.filter(val => !this.selectedFuncionario.includes(val));

        let excluiu = false;
        this.selectedFuncionario.forEach((item) => {
            this.funcionarioService.delete(item.id).then(obj => {
                excluiu = true;
            });
        });

        if (excluiu) {
            this.messageService.add({ severity: 'success', summary: 'Sucesso', detail: 'Funcionários excluídos', life: 3000 });
            this.selectedFuncionario = [];  
        }
    }

    confirmDelete() {
        this.deleteFuncionarioDialog = false;
        this.funcionarioService.delete(this.funcionario.id).then(obj => {
          this.listaFuncionario = this.listaFuncionario.filter(val => val.id !== this.funcionario.id);
          this.funcionario = {};        
          this.messageService.add({ severity: 'success', summary: 'Sucesso', detail: 'Página excluída', life: 3000 });
        });
    }
          
    exportPdf() {
        const head: string[] = [];
        const data: any[] = [];

        this.exportColumns.forEach(item => head.push(item.title));
        this.listaFuncionario.forEach(item => data.push(
            [item.id, item.nome, item.cpfFormatado, item.email, item.telefone, item.celular, 
            item.setor, item.codCargo, item.cargo, item.dataAdmissaoFormatada, item.dataSaidaFormatada, item.ativo]
        ));

        this.exportService.exportPdf(head, data, 'funcionarios.pdf');
    }
    
    exportExcel() {
        this.exportService.exportExcel(this.listaFuncionario, 'funcionarios');
    }    
    

}

<div class="grid">
    <div class="col-12">
        <div class="card px-6 py-6" [style]="mostrarListar()">
            <p-toast></p-toast>
            <p-toolbar styleClass="mb-4">
                <ng-template pTemplate="left">
                    <div class="my-2">
                        <button pButton pRipple label="Adicionar" icon="pi pi-plus" class="p-button-success mr-2" (click)="onInsert()"></button>
                        <button pButton pRipple label="Excluir" icon="pi pi-trash" class="p-button-danger" (click)="deleteSelected()" 
                        [disabled]="!selectedFuncionario || !selectedFuncionario.length"></button>
                    </div>
                </ng-template>
            </p-toolbar>

            <p-table #dt [value]="listaFuncionario" [columns]="cols" responsiveLayout="scroll" [rows]="10" 
                [globalFilterFields]="['nome']" paginatorPosition="top"
                [paginator]="true" [rowsPerPageOptions]="[10,20,30,100,200,500]" [showCurrentPageReport]="true" 
                currentPageReportTemplate="Mostrando {first} até {last} de {totalRecords} entradas" 
                [(selection)]="selectedFuncionario" selectionMode="multiple" [rowHover]="true" dataKey="id"                
                (selectionChange)="onSelectionChange($event)" [selectAll]="selectAll" (selectAllChange)="onSelectAllChange($event)"                
                [lazy]="true" (onLazyLoad)="loadFuncionarios($event)" [loading]="loading" [totalRecords]="totalRecords">
                <ng-template pTemplate="caption">
                    <div class="flex flex-column md:flex-row md:justify-content-between md:align-items-center">
                        <h5 class="m-0">Funcionários</h5>

                        <div class="flex">
                            <button type="button" pButton pRipple icon="pi pi-file" (click)="dt.exportCSV()" class="mr-2" pTooltip="CSV" tooltipPosition="bottom"></button>
                            <button type="button" pButton pRipple icon="pi pi-file-excel" (click)="exportExcel()" class="p-button-success mr-2" pTooltip="XLS" tooltipPosition="bottom"></button>
                            <button type="button" pButton pRipple icon="pi pi-file-pdf" (click)="exportPdf()" class="p-button-warning mr-2" pTooltip="PDF" tooltipPosition="bottom"></button>
                            <button type="button" pButton pRipple icon="pi pi-filter" (click)="dt.exportCSV({ selectionOnly: true })" class="p-button-info mr-2" pTooltip="Somente Seleção" tooltipPosition="bottom"></button>
                        </div>                        

                    </div>
                </ng-template>
                <ng-template pTemplate="header">
                    <tr>
                        <th style="width: 3rem">
                        </th>                        
                        <th></th>
                        <th pSortableColumn="id">Id <p-sortIcon field="id"></p-sortIcon></th>
                        <th pSortableColumn="nome">Nome <p-sortIcon field="nome"></p-sortIcon></th>
                        <th pSortableColumn="cpf">Cpf <p-sortIcon field="cpfFormatado"></p-sortIcon></th>
                        <th pSortableColumn="email">Email <p-sortIcon field="email"></p-sortIcon></th>
                        <th pSortableColumn="telefone">Telefone <p-sortIcon field="telefone"></p-sortIcon></th>
                        <th pSortableColumn="celular">Celular <p-sortIcon field="celular"></p-sortIcon></th>
                        <th pSortableColumn="setor">Setor <p-sortIcon field="setor"></p-sortIcon></th>
                        <th pSortableColumn="codCargo">CodCargo <p-sortIcon field="codCargo"></p-sortIcon></th>
                        <th pSortableColumn="cargo">Cargo <p-sortIcon field="cargo"></p-sortIcon></th>
                        <th pSortableColumn="dataAdmissao">Data Admissão <p-sortIcon field="dataAdmissaoFormatada"></p-sortIcon></th>
                        <th pSortableColumn="dataSaida">Data Saída <p-sortIcon field="dataSaidaFormatada"></p-sortIcon></th>
                        <th pSortableColumn="ativo">Ativo <p-sortIcon field="ativo"></p-sortIcon></th>                        
                    </tr>
                    <tr>
                        <th style="width: 3rem">
                            <p-tableHeaderCheckbox></p-tableHeaderCheckbox>
                        </th>                        
                        <th></th>
                        <th></th>
                        <th><p-columnFilter type="text" field="nome"></p-columnFilter></th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                    </tr>
                </ng-template>
                <ng-template pTemplate="body" let-funcionario>
                    <tr>
                        <td>
                            <p-tableCheckbox [value]="funcionario"></p-tableCheckbox>
                        </td>
                        <td>
                            <div class="flex">
                                <button pButton pRipple icon="pi pi-pencil" class="p-button-rounded p-button-success mr-2" (click)="onEdit(funcionario)"></button>
                                <button pButton pRipple icon="pi pi-trash" class="p-button-rounded p-button-warning" (click)="onDelete(funcionario)"></button>
                            </div>
                        </td>
                        <td style="width:5%; min-width:5rem;"><span class="p-column-title">Id</span>
                            {{funcionario.id}}
                        </td>
                        <td style="min-width:20rem;">
                            <span class="p-column-title">Nome</span>
                            {{funcionario.nome}}
                        </td>
                        <td style="min-width:10rem;">
                            <span class="p-column-title">Cpf</span>
                            {{funcionario.cpfFormatado}}
                        </td>
                        <td style="width:14%; min-width:10rem;">
                            <span class="p-column-title">Email</span>
                            {{funcionario.email}}
                        </td>
                        <td style="width:14%; min-width:10rem;">
                            <span class="p-column-title">Telefone</span>
                            {{funcionario.telefone}}
                        </td>
                        <td style="width:14%; min-width:10rem;">
                            <span class="p-column-title">Celular</span>
                            {{funcionario.celular}}
                        </td>
                        <td style="width:14%; min-width:10rem;">
                            <span class="p-column-title">Setor</span>
                            {{funcionario.setor}}
                        </td>
                        <td style="width:14%; min-width:10rem;">
                            <span class="p-column-title">CodCargo</span>
                            {{funcionario.codCargo}}
                        </td>
                        <td style="min-width:20rem;">
                            <span class="p-column-title">Cargo</span>
                            {{funcionario.cargo}}
                        </td>
                        <td style="min-width:12rem;">
                            <span class="p-column-title">Data Admissão</span>
                            {{funcionario.dataAdmissaoFormatada}}
                        </td>
                        <td style="width:14%; min-width:10rem;">
                            <span class="p-column-title">Data Saída</span>
                            {{funcionario.dataSaidaFormatada}}
                        </td>
                        <td style="width:14%; min-width:10rem;">
                            <span class="p-column-title">Ativo</span>
                            {{funcionario.ativo}}
                        </td>
                    </tr>
                </ng-template>
            </p-table>
        </div>

        <div [style]="mostrarEditar()">

            <p-panel header="Detalhes do funcionário" styleClass="p-mb-2">
                <p-toast></p-toast>
                <p-toolbar styleClass="mb-4">
                    <ng-template pTemplate="left">
                    </ng-template>
                    <ng-template pTemplate="right">
                        <div class="my-2">
                            <button pButton pRipple label="Cancelar" icon="pi pi-times" class="p-button-secondary mr-2" (click)="hideDialog()"></button>
                            <button pButton pRipple label="Limpar" icon="pi pi-star-o" class="p-button-primary mr-2" (click)="onClean()"></button>
                            <button pButton pRipple label="Salvar" icon="pi pi-check" class="p-button-success" (click)="onSave()"></button>        
                        </div>
                    </ng-template>
                </p-toolbar>
    
                <div class="card p-fluid">
                    <div class="field">
                        <label for="nome">Nome</label>
                        <input type="text" pInputText id="nome" [(ngModel)]="funcionario.nome" required autofocus 
                            [ngClass]="{'ng-invalid ng-dirty' : submitted && !funcionario.nome}" />
                        <small class="ng-dirty ng-invalid" *ngIf="submitted && !funcionario.nome">Nome é obrigatório.</small>
                    </div>
                    <div class="field">
                        <label for="email">Email</label>
                        <input type="text" pInputText id="email" [(ngModel)]="funcionario.email" />
                    </div>
                    <div class="formgrid grid">
                        <div class="field col">
                            <label for="cpf">cpf</label>
                            <p-inputMask mask="999.999.999-99" id="cpf" [(ngModel)]="funcionario.cpfFormatado" required
                                [ngClass]="{'ng-invalid ng-dirty' : submitted && !funcionario.cpfFormatado}"></p-inputMask>
                            <small class="ng-dirty ng-invalid" *ngIf="submitted && !funcionario.cpfFormatado">CPF é obrigatório.</small>    
                        </div>
                        <div class="field col">
                            <label for="telefone">Telefone</label>
                            <input type="text" pInputText id="telefone" [(ngModel)]="funcionario.telefone" />
                        </div>
                    </div>
                    <div class="formgrid grid">
                        <div class="field col">
                            <label for="celular">Celular</label>
                            <input type="text" pInputText id="celular" [(ngModel)]="funcionario.celular" />
                        </div>
                        <div class="field col">
                            <label for="setor">Setor</label>
                            <input type="text" pInputText id="setor" [(ngModel)]="funcionario.setor" />
                        </div>
                    </div>
                    <div class="formgrid grid">
                        <div class="field col">
                            <label for="codCargo">CodCargo</label>
                            <p-inputNumber mode="decimal" [useGrouping]="false" id="codCargo" [(ngModel)]="funcionario.codCargo"></p-inputNumber>
                        </div>
                        <div class="field col">
                            <label for="cargo">Cargo</label>
                            <input type="text" pInputText id="cargo" [(ngModel)]="funcionario.cargo" />
                        </div>
                    </div>
                    <div class="formgrid grid">
                        <div class="field col">
                            <label for="dataAdmissao">Data Admissão</label>
                            <p-calendar id="dataAdmissao" [(ngModel)]="funcionario.dataAdmissaoFormatada" [showIcon]="true" 
                                dateFormat="dd/mm/yy" dataType="string"></p-calendar>
                        </div>
                        <div class="field col">
                            <label for="dataSaida">Data Saída</label>
                            <p-calendar id="dataSaida" [(ngModel)]="funcionario.dataSaidaFormatada" [showIcon]="true" 
                                dateFormat="dd/mm/yy" dataType="string"></p-calendar>
                        </div>
                    </div>    
                    <div class="flex align-items-center gap-1">                        
                        <p-checkbox value="Ativo" inputId="ativo" [binary]="true" [(ngModel)]="funcionario.ativo" />
                        <label for="ativo">Ativo</label>
                    </div>       
                </div>
            </p-panel>              

        </div>
  
        <p-dialog [(visible)]="deleteFuncionarioDialog" header="Confirme" [modal]="true" [style]="{width:'450px'}">
            <div class="flex align-items-center justify-content-center">
                <i class="pi pi-exclamation-triangle mr-3" style="font-size: 2rem"></i>
                <span *ngIf="funcionario">Tem certeza de que deseja excluir <b>{{funcionario.nome}}</b>?</span>
            </div>
            <ng-template pTemplate="footer">
                <button pButton pRipple icon="pi pi-times" class="p-button-text" label="Não" (click)="deleteFuncionarioDialog = false"></button>
                <button pButton pRipple icon="pi pi-check" class="p-button-text" label="Sim" (click)="confirmDelete()"></button>
            </ng-template>
        </p-dialog>

        <p-dialog [(visible)]="deleteFuncionariosDialog" header="Confirme" [modal]="true" [style]="{width:'450px'}">
            <div class="flex align-items-center justify-content-center">
                <i class="pi pi-exclamation-triangle mr-3" style="font-size: 2rem"></i>
                <span>Tem certeza de que deseja excluir os funcionários selecionados?</span>
            </div>
            <ng-template pTemplate="footer">
                <button pButton pRipple icon="pi pi-times" class="p-button-text" label="Não" (click)="deleteFuncionariosDialog = false"></button>
                <button pButton pRipple icon="pi pi-check" class="p-button-text" label="Sim" (click)="confirmDeleteSelected()"></button>
            </ng-template>
        </p-dialog>
    </div>
</div>
