// frontend/hfs-frontend-material/src/app/base/components/report-panel/report-panel.component.ts
import { Component, EventEmitter, OnInit, Output } from '@angular/core';
import { Subject } from 'rxjs';
import { ItypeReport, PDFReport, ReportService, SelectItemGroup } from '../../services/ReportService';
import { FormControl } from '@angular/forms';

@Component({
  selector: 'app-report-panel',
  templateUrl: './report-panel.component.html',
  styleUrls: ['./report-panel.component.css'],
  providers: [ReportService]
})
export class ReportPanelComponent implements OnInit {

  cmbTypeReport = new FormControl('');

  typeReport: SelectItemGroup[];

  selectedTypeReport: ItypeReport;

  selectedForceDownload: boolean;

  @Output() typeReportChange = new EventEmitter<ItypeReport>();
  typeReportChangedSource = new Subject<ItypeReport>();

  @Output() forceDownloadChange = new EventEmitter<boolean>();
  forceDownloadChangedSource = new Subject<boolean>();

  constructor(private reportService: ReportService) {
    this.typeReport = this.reportService.getTypeReport();
    this.selectedTypeReport = PDFReport;
    this.selectedForceDownload = true;
  }

  ngOnInit(): void {
    this.typeReportChangedSource.subscribe(item => this.typeReportChange.emit(item));
    this.forceDownloadChangedSource.subscribe(item => this.forceDownloadChange.emit(item));
  }

  ngOnDestroy() {
    this.typeReportChangedSource.unsubscribe();
    this.forceDownloadChangedSource.unsubscribe();
  }

}

<div class="p-fluid formgrid grid">    
    <div class="field col-6 md-6">
        <label for="cmbTypeReport"></label>
        <mat-form-field style="width: 400px;">
            <mat-label>Escolha o tipo de relatório:</mat-label>
            <mat-select [formControl]="cmbTypeReport" (onChange)="typeReportChangedSource.next($event.value)"
                [(value)]="selectedTypeReport">
                @for (group of typeReport; track group) {
                    <mat-optgroup [label]="group.label" style="font-weight: bold;">
                        @for (item of group.items; track item) {
                            <mat-option [value]="item.value">{{item.label}}</mat-option>
                        }
                    </mat-optgroup>
                }
            </mat-select>
        </mat-form-field>    
    </div>
    <!--
    <div class="field col-4 md-4">
        <label for="forceDownload" style="margin: 4px;">Forçar download:</label>
        <p-checkbox id="forceDownload" [(ngModel)]="selectedForceDownload" binary="true" inputId="forceDownload" 
            (onChange)="forceDownloadChangedSource.next($event.checked)"></p-checkbox>    
    </div>
    -->
</div>

// frontend/hfs-frontend-react-mui/src/base/components/ReportPanel.tsx
import React from "react";
import { PDFReport, ReportService, SelectItemGroup } from "../services/ReportService";
import InputLabel from '@mui/material/InputLabel';
import MenuItem from '@mui/material/MenuItem';
import FormControl from '@mui/material/FormControl';
import Select, { SelectChangeEvent } from '@mui/material/Select';
import ListSubheader from "@mui/material/ListSubheader";

interface ReportPanelProps {
  typeReportChange?(e: SelectChangeEvent): void,
  forceDownloadChange?(e: React.ChangeEvent<HTMLInputElement>): void
}

class ReportPanelComponent extends React.Component<ReportPanelProps,any> {

  private reportService: ReportService;  
  private lista: React.JSX.Element[] = [];

  constructor(props: ReportPanelProps) {
    super(props);
    this.reportService = new ReportService();

    this.state = {
      typeReport: this.reportService.getTypeReport(),
      selectedTypeReport: PDFReport,
      selectedForceDownload: true
    }

    this.state.typeReport.forEach((group: SelectItemGroup) => {
        this.lista.push(<ListSubheader key={group.id} style={{fontWeight: "bold"}}>{group.label}</ListSubheader>);        
        group.items?.forEach((item: SelectItemGroup) => {
          this.lista.push(<MenuItem key={item.id} value={item.value}>{item.label}</MenuItem>);  
        });
    });

  }

  private typeReportChange(e: SelectChangeEvent): void {
    this.setState({ selectedTypeReport: e.target.value });

    if (this.props.typeReportChange) {
      this.props.typeReportChange(e);
    }
  }
/*
  private forceDownloadChange(e: React.ChangeEvent<HTMLInputElement>): void {
    this.setState({ selectedForceDownload: e.target.checked });

    if (this.props.forceDownloadChange) {
      this.props.forceDownloadChange(e);
    }
  }
  */
  render() {
    return (
      <div className="p-fluid formgrid grid">
          <div className="field col-4 md-4">
            <FormControl sx={{ m: 1, minWidth: 400 }}>
              <InputLabel htmlFor="cmbTypeReport">Escolha o tipo de relatório:</InputLabel>
              <Select defaultValue="" id="cmbTypeReport" label="Grouping" onChange={e => this.typeReportChange(e)} >
                {this.lista}
              </Select>
            </FormControl>
          </div>
          {/*
          <div className="field col-4 md-4">
              <label htmlFor="forceDownload" style={{margin: '4px'}}>Forçar download:</label>
              <Checkbox id="forceDownload" onChange={e => this.forceDownloadChange(e)} 
                  checked={this.state.selectedForceDownload}></Checkbox>
          </div>
          */}
      </div>
    );
  }
}

export default ReportPanelComponent;
