// frontend/hfs-frontend-react/src/layout/AppTopbar.tsx
//import Link from 'next/link';
import { Link } from 'react-router-dom';
import { classNames } from 'primereact/utils';
import { forwardRef, useContext, useImperativeHandle, useRef } from 'react';
import { AppTopbarRef } from '../types';
import { LayoutContext } from './context/layoutcontext';
import keycloakService from '../main';
//import keycloakService from '../base/providers/KeycloakProvider';
//import { TokenStorageService } from '@/app/(main)/base/services/TokenStorageService';
//import { SessionStorageService } from '@/app/(main)/base/services/SessionStorageService';

const AppTopbar = forwardRef<AppTopbarRef>(() => {
    const { layoutState, onMenuToggle, showProfileSidebar } = useContext(LayoutContext);
    const menubuttonRef = useRef(null);
    const topbarmenuRef = useRef(null);
    const topbarmenubuttonRef = useRef(null);
    
    //const tokenStorage = new TokenStorageService();
    //const sessionStorageService = new SessionStorageService();


    useImperativeHandle(undefined, () => ({
        menubutton: menubuttonRef.current,
        topbarmenu: topbarmenuRef.current,
        topbarmenubutton: topbarmenubuttonRef.current
    }));

    const logout = async () => {
        //tokenStorage.clear();   
        //sessionStorageService.removePersistedObj('userAuthenticated');

        await keycloakService.logout();
    };

    return (
        <div className="layout-topbar">
            <Link to="/" className="layout-topbar-logo">
                <span>HFS FULLSTACK</span>
            </Link>
            <button ref={menubuttonRef} type="button" className="p-link layout-menu-button layout-topbar-button" onClick={onMenuToggle}>
                <i className="pi pi-bars" />
            </button>

            <button ref={topbarmenubuttonRef} type="button" className="p-link layout-topbar-menu-button layout-topbar-button" onClick={showProfileSidebar}>
                <i className="pi pi-ellipsis-v" />
            </button>

            <div ref={topbarmenuRef} className={classNames('layout-topbar-menu', { 'layout-topbar-menu-mobile-active': layoutState.profileSidebarVisible })}>
                <Link to="/system/usuario">
                    <button type="button" className="p-link layout-topbar-button">
                        <i className="pi pi-user"></i>
                        <span>Perfil</span>
                    </button>
                </Link>                    
                <Link to="/system/config">
                    <button type="button" className="p-link layout-topbar-button">
                        <i className="pi pi-cog"></i>
                        <span>Configurações</span>
                    </button>
                </Link>                    
                <button type="button" className="p-link layout-topbar-button" onClick={logout}>
                    <i className="pi pi-sign-out"></i>
                    <span>Sair</span>
                </button>
            </div>
             
        </div>
    );
});

AppTopbar.displayName = 'AppTopbar';

export default AppTopbar;

// frontend/hfs-frontend-jest/src/app/layout/app.topbar.component.ts
import { Component, ElementRef, ViewChild } from '@angular/core';
import { MenuItem } from 'primeng/api';
import { LayoutService } from "./service/app.layout.service";
import { KeycloakService } from 'keycloak-angular';
import { AuthService } from '../base/services/auth.service';

@Component({
    selector: 'app-topbar',
    templateUrl: './app.topbar.component.html'
})
export class AppTopBarComponent {

    items!: MenuItem[];

    @ViewChild('menubutton') menuButton!: ElementRef;

    @ViewChild('topbarmenubutton') topbarMenuButton!: ElementRef;

    @ViewChild('topbarmenu') menu!: ElementRef;

    constructor(public layoutService: LayoutService,
        private readonly keycloak: KeycloakService,
        private authService: AuthService) { }

    public logout() {
        this.authService.clear();
        this.keycloak.logout();
    }
}
 
<div class="layout-topbar">
    <a class="layout-topbar-logo" routerLink="">
        <!--
        <img src="assets/layout/images/{{layoutService.config().colorScheme === 'light' ? 'logo-dark' : 'logo-white'}}.svg" alt="logo">
        -->
        <span>HFS FULLSTACK</span>
    </a>

    <button #menubutton class="p-link layout-menu-button layout-topbar-button" (click)="layoutService.onMenuToggle()">
        <i class="pi pi-bars"></i>
    </button>

    <button #topbarmenubutton class="p-link layout-topbar-menu-button layout-topbar-button" (click)="layoutService.showProfileSidebar()">
        <i class="pi pi-ellipsis-v"></i>
    </button>
        
    <div #topbarmenu class="layout-topbar-menu" [ngClass]="{'layout-topbar-menu-mobile-active': layoutService.state.profileSidebarVisible}">
        <button class="p-link layout-topbar-button" [routerLink]="'/system/usuario'">
            <i class="pi pi-user"></i>
            <span>Perfil</span>
        </button>
        <button class="p-link layout-topbar-button" [routerLink]="'/system/config'">
            <i class="pi pi-cog"></i>
            <span>Configurações</span>
        </button>
        <button class="p-link layout-topbar-button" (click)="logout()">
            <i class="pi pi-sign-out"></i>
            <span>Sair</span>
        </button>
    </div>
</div>
