// frontend/hfs-frontend/src/app/admin/pages/adm-parameter-category/adm-parameter-category.component.ts
import { Component, OnInit } from '@angular/core';
import { MessageService } from 'primeng/api';
import { Table } from 'primeng/table';
import { ReportParamForm } from 'src/app/base/models/ReportParamsForm';
import { ItypeReport } from 'src/app/base/services/ReportService';
import { AdmParameterCategoryService } from '../../service/AdmParameterCategoryService';
import { AdmParameterCategory } from '../../api/AdmParameterCategory';
import { ErrorResponseDTO } from 'src/app/base/models/ErrorResponseDTO';

@Component({
  templateUrl: './adm-parameter-category.component.html',
  providers: [MessageService, AdmParameterCategoryService]
})
export class AdmParameterCategoryComponent implements OnInit {

  admParameterCategoryDialog: boolean;

  listaAdmParameterCategory: AdmParameterCategory[];

  admParameterCategory: AdmParameterCategory;

  selectedAdmParameterCategories: AdmParameterCategory[];

  submitted: boolean;

  cols: any[] = [];

  reportParamForm: ReportParamForm;

  deleteAdmParameterCategoryDialog: boolean = false;

  deleteAdmParameterCategoriesDialog: boolean = false;

  constructor(private admParameterCategoryService: AdmParameterCategoryService,
    private messageService: MessageService) {
      this.reportParamForm = {
        reportType: 'PDF',
        forceDownload: true
      };
    }

  ngOnInit(): void {
    this.admParameterCategoryService.findAll()
      .then(data => this.listaAdmParameterCategory = data);

    this.cols = [
      { field: 'id', header: 'Id' },
      { field: 'description', header: 'Descrição' },
      { field: 'order', header: 'Ordem' }
    ];

  }

  onChangedTypeReport(typeReport: ItypeReport) {
    this.reportParamForm.reportType = typeReport.type;
  }

  onChangedForceDownload(forceDownload: boolean) {
    this.reportParamForm.forceDownload = forceDownload;
  }

  onExport() {
    this.admParameterCategoryService.report(this.reportParamForm).then(() => {
      this.messageService.add({severity: 'info', summary: 'Categoria de parâmetro exportada', 
        detail: 'Categoria de parâmetro exportada', life: 1000});
    });
  }

  onInsert() {
    this.admParameterCategory = {};
    this.submitted = false;
    this.admParameterCategoryDialog = true;
  }

  onEdit(admParameterCategory: AdmParameterCategory) {
    this.admParameterCategory = { ...admParameterCategory };
    this.admParameterCategoryDialog = true;
  }

  hideDialog() {
    this.admParameterCategoryDialog = false;
    this.submitted = false;
  }

  onSave() {
    this.submitted = true;

    if (this.admParameterCategory.description.trim()) {
        if (this.admParameterCategory.id) {
          this.admParameterCategoryService.update(this.admParameterCategory).then((obj: AdmParameterCategory) => {
            this.admParameterCategory = obj;
            this.listaAdmParameterCategory[this.admParameterCategoryService
              .findIndexById(this.listaAdmParameterCategory, this.admParameterCategory.id)] = this.admParameterCategory;
            this.messageService.add({ severity: 'success', summary: 'Sucesso', detail: 'Categoria de parâmetro Atualizada', life: 3000 });
          });
        } else {
          this.admParameterCategoryService.insert(this.admParameterCategory).then((obj: AdmParameterCategory) => {
            this.admParameterCategory = obj;
            this.listaAdmParameterCategory.push(this.admParameterCategory);
            this.messageService.add({ severity: 'success', summary: 'Sucesso', detail: 'Categoria de parâmetro Criada', life: 3000 });
          });
        }

        this.listaAdmParameterCategory = [...this.listaAdmParameterCategory];
        this.admParameterCategoryDialog = false;
        this.admParameterCategory = {};
    }
  }

  deleteSelected() {
      this.deleteAdmParameterCategoriesDialog = true;
  }

  onDelete(admParameterCategory: AdmParameterCategory) {
      this.deleteAdmParameterCategoryDialog = true;
      this.admParameterCategory = { ...admParameterCategory };
  } 

  confirmDeleteSelected() {
      this.deleteAdmParameterCategoriesDialog = false;
      this.listaAdmParameterCategory = this.listaAdmParameterCategory.filter(val => !this.selectedAdmParameterCategories.includes(val));

      let excluiu = false;
      this.selectedAdmParameterCategories.forEach((item) => {
        this.admParameterCategoryService.delete(item.id).then(obj => {
          excluiu = true;
        });
      });
  
      if (excluiu) {
        this.messageService.add({ severity: 'success', summary: 'Sucesso', detail: 'Categorias de parâmetro excluídos', life: 3000 });
        this.selectedAdmParameterCategories = [];
      }
  }

  confirmDelete() {
    this.deleteAdmParameterCategoryDialog = false;
    this.admParameterCategoryService.delete(this.admParameterCategory.id).then(obj => {
      this.listaAdmParameterCategory = this.listaAdmParameterCategory.filter(val => val.id !== this.admParameterCategory.id);
      this.admParameterCategory = {};        
      this.messageService.add({ severity: 'success', summary: 'Sucesso', detail: 'Categoria de parâmetro excluído', life: 3000 });
    });
  }

  onGlobalFilter(table: Table, event: Event) {
    table.filterGlobal((event.target as HTMLInputElement).value, 'contains');
  }

}

<div class="grid">
    <div class="col-12">
        <div class="card px-6 py-6">
            <p-toast></p-toast>
            <p-panel header="Categoria de parâmetro de configuração" styleClass="p-mb-2">
                <app-report-panel (typeReportChange)="onChangedTypeReport($event)" (forceDownloadChange)="onChangedForceDownload($event)"></app-report-panel>
            </p-panel>            
            <p-toolbar styleClass="mb-4">
                <ng-template pTemplate="left">
                    <div class="my-2">
                        <button pButton pRipple label="Adicionar" icon="pi pi-plus" class="p-button-success mr-2" (click)="onInsert()"></button>
                        <button pButton pRipple label="Excluir" icon="pi pi-trash" class="p-button-danger" (click)="deleteSelected()" 
                        [disabled]="!selectedAdmParameterCategories || !selectedAdmParameterCategories.length"></button>
                    </div>
                </ng-template>

                <ng-template pTemplate="right">
                    <button pButton pRipple label="Exportar" icon="pi pi-upload" class="p-button-help" (click)="onExport()"></button>
                </ng-template>
            </p-toolbar>

            <p-table #dt [value]="listaAdmParameterCategory" [columns]="cols" responsiveLayout="scroll" [rows]="10" 
                [globalFilterFields]="['description']" paginatorPosition="both" emptyMessage="Nenhum registro encontrado."
                [paginator]="true" [rowsPerPageOptions]="[10,30,50,100,150,200]" [showCurrentPageReport]="true" 
                currentPageReportTemplate="Mostrando {first} até {last} de {totalRecords} entradas" 
                [(selection)]="selectedAdmParameterCategories" selectionMode="multiple" [rowHover]="true" dataKey="id">
                <ng-template pTemplate="caption">
                    <div class="flex flex-column md:flex-row md:justify-content-between md:align-items-center">
                        <h5 class="m-0">Gerenciar categorias de parâmetros</h5>
                        <span class="block mt-2 md:mt-0 p-input-icon-left">
                            <i class="pi pi-search"></i>
                            <input pInputText type="text" (input)="onGlobalFilter(dt, $event)" placeholder="Procurar..."  class="w-full sm:w-auto"/>
                        </span>
                    </div>
                </ng-template>
                <ng-template pTemplate="header">
                    <tr>
                        <th style="width: 3rem">
                            <p-tableHeaderCheckbox></p-tableHeaderCheckbox>
                        </th>                        
                        <th pSortableColumn="id" style="width: 120px;" >Id <p-sortIcon field="id"></p-sortIcon></th>
                        <th pSortableColumn="description">Descrição <p-sortIcon field="description"></p-sortIcon></th>
                        <th pSortableColumn="order">Ordem <p-sortIcon field="order"></p-sortIcon></th>            
                        <th></th>
                    </tr>
                </ng-template>
                <ng-template pTemplate="body" let-admParameterCategory>
                    <tr>
                        <td>
                            <p-tableCheckbox [value]="admParameterCategory"></p-tableCheckbox>
                        </td>
                        <td style="width:14%; min-width:10rem;"><span class="p-column-title">Id</span>
                            {{admParameterCategory.id}}
                        </td>
                        <td style="min-width:10rem;">
                            <span class="p-column-title">Descrição</span>
                            {{admParameterCategory.description}}
                        </td>
                        <td style="width:14%; min-width:8rem;">
                            <span class="p-column-title">Ordem</span>
                            {{admParameterCategory.order}}
                        </td>
                        <td style="width:10%; min-width:8rem;">
                            <div class="flex">
                                <button pButton pRipple icon="pi pi-pencil" class="p-button-rounded p-button-success mr-2" (click)="onEdit(admParameterCategory)"></button>
                                <button pButton pRipple icon="pi pi-trash" class="p-button-rounded p-button-warning" (click)="onDelete(admParameterCategory)"></button>
                            </div>
                        </td>
                    </tr>
                </ng-template>
                <ng-template pTemplate="summary">
                    <div class="p-d-flex p-ai-center p-jc-between">
                        No total existem {{listaAdmParameterCategory ? listaAdmParameterCategory.length : 0 }} categorias de parâmetros.
                    </div>
                </ng-template>            
            </p-table>
        </div>

        <p-dialog [(visible)]="admParameterCategoryDialog" [style]="{width: '450px'}" header="Detalhes da categoria de parâmetro" [modal]="true" styleClass="p-fluid">
            <ng-template pTemplate="content">
                <div class="field">
                    <label for="description">Descrição</label>
                    <textarea id="description" pInputTextarea [(ngModel)]="admParameterCategory.description" required autofocus rows="3" cols="20"
                    [ngClass]="{'ng-invalid ng-dirty' : submitted && !admParameterCategory.description}"></textarea>
                    <small class="ng-dirty ng-invalid" *ngIf="submitted && !admParameterCategory.description">A descrição é obrigatória.</small>
                </div>
                <div class="field">
                    <label for="order">Ordem</label>
                    <p-inputNumber id="order" [(ngModel)]="admParameterCategory.order" locale="pt-BR"></p-inputNumber>
                </div>
            </ng-template>
        
            <ng-template pTemplate="footer">
                <button pButton pRipple label="Cancelar" icon="pi pi-times" class="p-button-text" (click)="hideDialog()"></button>
                <button pButton pRipple label="Salvar" icon="pi pi-check" class="p-button-text" (click)="onSave()"></button>
            </ng-template>
        </p-dialog>

        <p-dialog [(visible)]="deleteAdmParameterCategoryDialog" header="Confirme" [modal]="true" [style]="{width:'450px'}">
            <div class="flex align-items-center justify-content-center">
                <i class="pi pi-exclamation-triangle mr-3" style="font-size: 2rem"></i>
                <span *ngIf="admParameterCategory">Tem certeza de que deseja excluir <b>{{admParameterCategory.description}}</b>?</span>
            </div>
            <ng-template pTemplate="footer">
                <button pButton pRipple icon="pi pi-times" class="p-button-text" label="Não" (click)="deleteAdmParameterCategoryDialog = false"></button>
                <button pButton pRipple icon="pi pi-check" class="p-button-text" label="Sim" (click)="confirmDelete()"></button>
            </ng-template>
        </p-dialog>

        <p-dialog [(visible)]="deleteAdmParameterCategoriesDialog" header="Confirme" [modal]="true" [style]="{width:'450px'}">
            <div class="flex align-items-center justify-content-center">
                <i class="pi pi-exclamation-triangle mr-3" style="font-size: 2rem"></i>
                <span>Tem certeza de que deseja excluir as categorias de parâmetros selecionadas?</span>
            </div>
            <ng-template pTemplate="footer">
                <button pButton pRipple icon="pi pi-times" class="p-button-text" label="Não" (click)="deleteAdmParameterCategoriesDialog = false"></button>
                <button pButton pRipple icon="pi pi-check" class="p-button-text" label="Sim" (click)="confirmDeleteSelected()"></button>
            </ng-template>
        </p-dialog>
    </div>
</div>

// frontend/hfs-frontend-vue/src/admin/pages/AdmParameterCategory.vue
<script lang="ts">
import { FilterMatchMode } from 'primevue/api';
import { ref, onMounted, onBeforeMount } from 'vue';
import { useToast } from 'primevue/usetoast';
import AdmParameterCategoryService from '../../admin/service/AdmParameterCategoryService';
import { AdmParameterCategory, emptyAdmParameterCategory } from '../api/AdmParameterCategory';
import { ReportParamForm, emptyReportParamForm } from '../../base/models/ReportParamsForm';
import { ItypeReport, PDFReport, SelectItemGroup } from '../../base/services/ReportService';

export default {
    setup() {
        const toast = useToast();

        const listaAdmParameterCategory = ref<AdmParameterCategory[]>([]);
        const admParameterCategoryDialog = ref(false);
        const deleteAdmParameterCategoryDialog = ref(false);
        const deleteAdmParameterCategorysDialog = ref(false);
        const admParameterCategory = ref(emptyAdmParameterCategory);
        const selectedAdmParameterCategorys = ref();
        const dt = ref(null);
        const filters = ref({});
        const submitted = ref(false);

        const admParameterCategoryService = new AdmParameterCategoryService();

        const selectedTypeReport = ref<ItypeReport>();
        const selectedForceDownload = ref(true);
        const reportParamForm = ref<ReportParamForm>(emptyReportParamForm);

        onBeforeMount(() => {
            initFilters();
        });

        onMounted(() => {
            admParameterCategoryService.findAll().then((data) => (listaAdmParameterCategory.value = data));

            selectedTypeReport.value = PDFReport.value;
        });

        const onInsert = () => {
            admParameterCategory.value = emptyAdmParameterCategory;
            submitted.value = false;
            admParameterCategoryDialog.value = true;
        };

        const onEdit = (param: AdmParameterCategory) => {
            admParameterCategory.value = { ...param };
            admParameterCategoryDialog.value = true;
        };

        const hideDialog = () => {
            admParameterCategoryDialog.value = false;
            submitted.value = false;
        };

        const onSave = () => {
            submitted.value = true;
            if (admParameterCategory.value.description && admParameterCategory.value.description.trim()) {
                if (admParameterCategory.value.id) {
                    admParameterCategoryService.update(admParameterCategory.value).then((obj: AdmParameterCategory) => {
                        admParameterCategory.value = obj;

                        if (admParameterCategory.value.id){
                            const index = admParameterCategoryService.findIndexById(listaAdmParameterCategory.value, admParameterCategory.value.id);
                            listaAdmParameterCategory.value[index] = admParameterCategory.value;
                            toast.add({severity:'success', summary: 'Successful', detail: 'Categoria de parâmetro Atualizada', life: 3000});
                        }
                    });            
                } else {
                    admParameterCategoryService.insert(admParameterCategory.value).then((obj: AdmParameterCategory) => {
                        admParameterCategory.value = obj;

                        listaAdmParameterCategory.value.push(admParameterCategory.value);
                        toast.add({ severity: 'success', summary: 'Successful', detail: 'Categoria de parâmetro Criada', life: 3000 });
                    });            
                }

                admParameterCategoryDialog.value = false;
                admParameterCategory.value = emptyAdmParameterCategory;
            }
        };

        const deleteSelected = () => {
            deleteAdmParameterCategorysDialog.value = true;
        }

        const onDelete = (param: AdmParameterCategory) => {
            deleteAdmParameterCategoryDialog.value = true;
            admParameterCategory.value = { ...param };
        } 

        const confirmDeleteSelected = () => {
            deleteAdmParameterCategorysDialog.value = false;
            listaAdmParameterCategory.value = listaAdmParameterCategory.value.filter((val: AdmParameterCategory) => !selectedAdmParameterCategorys.value.includes(val));

            let excluiu = false;
            selectedAdmParameterCategorys.value.forEach((item: AdmParameterCategory) => {
                if (item.id){
                    admParameterCategoryService.delete(item.id).then(() => {
                        excluiu = true;
                    });
                }
            });

            if (excluiu) {
                toast.add({ severity: 'success', summary: 'Sucesso', detail: 'Categorias de parâmetro excluídos', life: 3000 });
                selectedAdmParameterCategorys.value = [];
            }
        }

        const confirmDelete = () => {
            deleteAdmParameterCategoryDialog.value = false;
            if (admParameterCategory.value.id){
                admParameterCategoryService.delete(admParameterCategory.value.id).then(() => {
                    listaAdmParameterCategory.value = listaAdmParameterCategory.value.filter((val: AdmParameterCategory) => val.id !== admParameterCategory.value.id);
                    admParameterCategory.value = emptyAdmParameterCategory;        
                    toast.add({ severity: 'success', summary: 'Sucesso', detail: 'Categoria de parâmetro excluído', life: 3000 });
                });
            }    
        }

        const onTypeReportChange = (param: { pTypeReport: SelectItemGroup }) => {
            if (param.pTypeReport.value){
                selectedTypeReport.value = param.pTypeReport.value;
                reportParamForm.value = { reportType: param.pTypeReport.value.type, forceDownload: selectedForceDownload.value };
            }        
        }

        const onForceDownloadChange = (param: { forceDownload: boolean }) => {
            selectedForceDownload.value = param.forceDownload;
            if (selectedTypeReport.value){
                reportParamForm.value = { reportType: selectedTypeReport.value.type, forceDownload: param.forceDownload };
            }
        }

        const onExport = () => {
            admParameterCategoryService.report(reportParamForm.value).then(() => {
                toast.add({ severity: 'info', summary: 'Categoria de parâmetro exportada', 
                    detail: 'Categoria de parâmetro exportada', life: 3000 });
            });
        }

        const initFilters = () => {
            filters.value = {
                global: { value: null, matchMode: FilterMatchMode.CONTAINS }
            };
        };

        return { listaAdmParameterCategory, admParameterCategory, filters, submitted,
            selectedAdmParameterCategorys, deleteSelected, admParameterCategoryDialog, hideDialog,
            deleteAdmParameterCategoryDialog, confirmDelete, deleteAdmParameterCategorysDialog,
            onInsert, onEdit, onDelete, onSave, onExport, onTypeReportChange, onForceDownloadChange,
            confirmDeleteSelected }
    }
}        
</script>

<template>
    <div class="grid">
        <div class="col-12">
            <div class="card px-6 py-6">
                <!-- <Toast /> -->
                <Panel header="Categoria de parâmetro de configuração" class="p-mb-2">
                    <ReportPanel @changeTypeReport="onTypeReportChange" @changeForceDownload="onForceDownloadChange"></ReportPanel>
                </Panel>                
                <Toolbar class="mb-4">
                    <template v-slot:start>
                        <div class="my-2">
                            <Button label="Adicionar" icon="pi pi-plus" class="p-button-success mr-2" @click="onInsert" />
                            <Button label="Excluir" icon="pi pi-trash" class="p-button-danger" @click="deleteSelected" 
                                :disabled="!selectedAdmParameterCategorys || !selectedAdmParameterCategorys.length" />
                        </div>
                    </template>

                    <template v-slot:end>
                        <Button label="Exportar" icon="pi pi-upload" class="p-button-help" @click="onExport" />
                    </template>
                </Toolbar>

                <DataTable
                    ref="dt" paginatorPosition="both"
                    :value="listaAdmParameterCategory"
                    v-model:selection="selectedAdmParameterCategorys"
                    dataKey="id"
                    :paginator="true"
                    :rows="10"
                    :filters="filters"
                    paginatorTemplate="FirstPageLink PrevPageLink PageLinks NextPageLink LastPageLink CurrentPageReport RowsPerPageDropdown"
                    :rowsPerPageOptions="[10,30,50,100,150,200]" emptyMessage="Nenhum registro encontrado."
                    currentPageReportTemplate="Mostrando {first} até {last} de {totalRecords} entradas"
                    responsiveLayout="scroll"
                >
                    <template #header>
                        <div class="flex flex-column md:flex-row md:justify-content-between md:align-items-center">
                            <h5 class="m-0">Gerenciar categorias de parâmetros</h5>
                            <span class="block mt-2 md:mt-0 p-input-icon-left">
                                <i class="pi pi-search" />
                                <InputText v-model="filters['global'].value" placeholder="Procurar..." />
                            </span>
                        </div>
                    </template>

                    <Column selectionMode="multiple" headerStyle="width: 3rem"></Column>
                    <Column field="id" header="Id" :sortable="true" headerStyle="width:14%; min-width:10rem;">
                        <template #body="slotProps">
                            <span class="p-column-title">Id</span>
                            {{ slotProps.data.id }}
                        </template>
                    </Column>
                    <Column field="description" header="Descrição" :sortable="true" headerStyle="min-width:10rem;">
                        <template #body="slotProps">
                            <span class="p-column-title">Descrição</span>
                            {{ slotProps.data.description }}
                        </template>
                    </Column>
                    <Column field="order" header="Ordem" :sortable="true" headerStyle="width:14%; min-width:8rem;">
                        <template #body="slotProps">
                            <span class="p-column-title">Ordem</span>
                            {{ slotProps.data.order }}
                        </template>
                    </Column>
                    <Column headerStyle="min-width:10rem;">
                        <template #body="slotProps">
                            <Button icon="pi pi-pencil" class="p-button-rounded p-button-success mr-2" @click="onEdit(slotProps.data)" />
                            <Button icon="pi pi-trash" class="p-button-rounded p-button-warning mt-2" @click="onDelete(slotProps.data)" />
                        </template>
                    </Column>

                    <template #footer>
                        <div class="p-d-flex p-ai-center p-jc-between">
                            No total existem {{listaAdmParameterCategory ? listaAdmParameterCategory.length : 0 }} categorias de parâmetro.
                        </div>
                    </template>

                </DataTable>

                <Dialog v-model:visible="admParameterCategoryDialog" :style="{ width: '450px' }" header="Detalhes da categoria de parâmetro" :modal="true" class="p-fluid">
                    <div class="field">
                        <label for="description">Descrição</label>
                        <Textarea id="description" v-model="admParameterCategory.description" autofocus required="true" rows="3" cols="20"
                            :class="{ 'p-invalid': submitted && !admParameterCategory.description }" />
                        <small class="p-invalid" v-if="submitted && !admParameterCategory.description">A descrição é obrigatória.</small>
                    </div>
                    <div class="field">
                        <label for="quantity">Ordem</label>
                        <InputNumber id="quantity" v-model="admParameterCategory.order" integeronly locale="pt-BR" />
                    </div>
                    <template #footer>
                        <Button label="Cancelar" icon="pi pi-times" class="p-button-text" @click="hideDialog" />
                        <Button label="Salvar" icon="pi pi-check" class="p-button-text" @click="onSave" />
                    </template>
                </Dialog>

                <Dialog v-model:visible="deleteAdmParameterCategoryDialog" :style="{ width: '450px' }" header="Confirme" :modal="true">
                    <div class="flex align-items-center justify-content-center">
                        <i class="pi pi-exclamation-triangle mr-3" style="font-size: 2rem" />
                        <span v-if="admParameterCategory">Tem certeza de que deseja excluir <b>{{ admParameterCategory.description }}</b>?</span>
                    </div>
                    <template #footer>
                        <Button label="Não" icon="pi pi-times" class="p-button-text" @click="deleteAdmParameterCategoryDialog = false" />
                        <Button label="Sim" icon="pi pi-check" class="p-button-text" @click="confirmDelete" />
                    </template>
                </Dialog>

                <Dialog v-model:visible="deleteAdmParameterCategorysDialog" :style="{ width: '450px' }" header="Confirme" :modal="true">
                    <div class="flex align-items-center justify-content-center">
                        <i class="pi pi-exclamation-triangle mr-3" style="font-size: 2rem" />
                        <span v-if="admParameterCategory">Tem certeza de que deseja excluir as categorias de parâmetros selecionadas?</span>
                    </div>
                    <template #footer>
                        <Button label="Não" icon="pi pi-times" class="p-button-text" @click="deleteAdmParameterCategorysDialog = false" />
                        <Button label="Sim" icon="pi pi-check" class="p-button-text" @click="confirmDeleteSelected" />
                    </template>
                </Dialog>
            </div>
        </div>
    </div>
</template>
