// frontend/hfs-frontend-material/src/app/admin/pages/adm-menu/adm-menu.component.ts
import { Component, OnInit } from '@angular/core';
import { ReportParamForm } from 'src/app/base/models/ReportParamsForm';
import { ItypeReport } from 'src/app/base/services/ReportService';
import { AdmMenuService } from '../../service/AdmMenuService';
import { AdmMenu, emptyAdmMenu } from '../../api/AdmMenu';
import { MatSnackBar } from '@angular/material/snack-bar';
import { MatDialog } from '@angular/material/dialog';
import { AdmMenuDialogDelete } from './dialogs/adm-menu.dialog-delete';
import { AdmMenuDialogDetails } from './dialogs/adm-menu.dialog-details';
import {FlatTreeControl} from '@angular/cdk/tree';
import {MatTreeFlatDataSource, MatTreeFlattener} from '@angular/material/tree';
import { AdmPage } from '../../api/AdmPage';
import { AdmPageService } from '../../service/AdmPageService';
import { TreeNode } from 'src/app/base/models/TreeNode';

interface MenuFlatNode {
  expandable: boolean;
  name: string;
  data: any;
  select: boolean;
  level: number;
};

@Component({
  templateUrl: './adm-menu.component.html',
  styleUrls: ["./adm-menu.component.css"],
  providers: [AdmMenuService, AdmPageService]
})
export class AdmMenuComponent implements OnInit {

  listaAdmMenu: AdmMenu[] = [];

  admMenu: AdmMenu;

  selectedAdmMenu: AdmMenu;

  submitted: boolean;

  cols: any[];

  exportColumns: any[];

  listaNodeMenu: TreeNode[] = [];

  //selectedNodeMenu: TreeNode;

  menuRoot: TreeNode;

  listaAdmPage: AdmPage[] = [];

  listaAdmMenuParent: AdmMenu[] = [];

  reportParamForm: ReportParamForm;

  deleteAdmMenuDialog: boolean = false;  

  private _transformer = (node: TreeNode, level: number) => {
    return {
      expandable: !!node.children && node.children.length > 0,
      name: node.label,
      data: node.data,
      select: false,
      level: level,
    };
  };

  treeControl = new FlatTreeControl<MenuFlatNode>(
    node => node.level,
    node => node.expandable,
  );

  treeFlattener = new MatTreeFlattener(
    this._transformer,
    node => node.level,
    node => node.expandable,
    node => node.children,
  );

  dataSource = new MatTreeFlatDataSource(this.treeControl, this.treeFlattener);
  
  constructor(private admMenuService: AdmMenuService,
    private admPageService: AdmPageService,
    private snackBar: MatSnackBar, public dialog: MatDialog) {
    this.reportParamForm = {
        reportType: 'PDF',
        forceDownload: true
    };
  }

  hasChild = (_: number, node: MenuFlatNode) => node.expandable;
    
  ngOnInit(): void {
    this.atualizarArvore();

    this.cols = [
      { field: 'id', header: 'Id' },
      { field: 'description', header: 'Description' }
    ];

    this.exportColumns = this.cols.map(col => ({ title: col.header, dataKey: col.field }));
  }
  
  atualizarArvore(): void {
    this.listaNodeMenu = [];
    this.listaAdmMenu = [];
    this.listaAdmMenuParent = [];
    
    this.admPageService
      .findAll()
      .then(data => this.listaAdmPage = data);      

    this.admMenuService
      .findAll()
      .then(data => {
        this.listaAdmMenu = data;

        this.listaAdmMenuParent = this.listaAdmMenu.filter(menu => menu.idMenuParent == null);

        this.updateMenusTree(this.listaAdmMenu);

        this.dataSource.data = this.listaNodeMenu;

        this.treeControl.expandAll();
      });
  }

  updateMenusTree(listaAdmMenu: AdmMenu[]): void {
    this.listaNodeMenu = [];
    /*
    this.menuRoot = {
      'label': 'Menu do sistema',
      'data': '0',
      'children': []
    };
    */

    listaAdmMenu.forEach((itemMenu: AdmMenu) => {
      const m: TreeNode = {};
      m.data = itemMenu;
      m.label = itemMenu.description;      

      if (itemMenu.idPage === null) {
        m.children = this.mountSubMenu(itemMenu);
        //this.menuRoot.children.push(m);

        this.listaNodeMenu.push(m);
      }
    });

    //this.listaNodeMenu.push(this.menuRoot);    
  }

  isSubMenu(menu: AdmMenu): boolean {
    return menu.idPage === null;
  }

  getAdmSubMenus(menuPai: AdmMenu): AdmMenu[] {
    return this.listaAdmMenu.filter(menu => menu.idMenuParent === menuPai.id);
  }

  mountSubMenu(menu: AdmMenu): TreeNode[] {
    const lstSubMenu: TreeNode[] = [];

    this.getAdmSubMenus(menu).forEach((subMenu: AdmMenu) => {

      if (this.isSubMenu(subMenu)) {
        const m: TreeNode = {};
        m.data = subMenu;
        m.label = subMenu.description;
        m.children = this.mountSubMenu(subMenu);
      } else {
        const m: TreeNode = {};
        m.data = subMenu;
        m.label = subMenu.description;
        lstSubMenu.push(m);
      }
    });

    return lstSubMenu;
  }

  nodeParentSelect(node: MenuFlatNode) {
    this.selectedAdmMenu = node.data;
    //this.selectedNodeMenu = event.node;
  }

  nodeSelect(node: MenuFlatNode) {
    this.selectedAdmMenu = node.data;
    //this.selectedNodeMenu = event.node;
  }

  itemParentSelect(node: MenuFlatNode) {    
    this.deselectAll();
    node.select = true;
  }

  itemSelect(node: MenuFlatNode) {    
    this.deselectAll();
    node.select = true;
  }  

  onChangedTypeReport(typeReport: ItypeReport) {
    this.reportParamForm.reportType = typeReport.type;
  }

  onChangedForceDownload(forceDownload: boolean) {
    this.reportParamForm.forceDownload = forceDownload;
  }

  onExport() {
    this.admMenuService.report(this.reportParamForm).then(() => {
      this.snackBar.open('Categoria de parâmetro exportada', 'info', { duration: 3000 });
    });
  }

  openDialogDetails(param: AdmMenu){
    const dialogRef = this.dialog.open(AdmMenuDialogDetails, { 
      data: { 
        listaAdmPage: this.listaAdmPage, 
        listaAdmMenuParent: this.listaAdmMenuParent,
        entidade: param
      } 
    });
    
    dialogRef.afterClosed().subscribe(result => {
      if (result){
        this.admMenu = result.entidade;
        this.onSave(this.admMenu.admPage, this.admMenu.admMenuParent);
      }
    });
  }

  onInsert() {
    this.admMenu = emptyAdmMenu;
    this.admMenu.admMenuParent = emptyAdmMenu;
    this.openDialogDetails(emptyAdmMenu);
  }

  onEdit(admMenu: AdmMenu) {
    this.admMenu = { ...admMenu };
    this.openDialogDetails(this.admMenu);
  }

  onSave(admPage: AdmPage, admMenuParent: AdmMenu) {    
    if (admPage!=null){
      this.admMenu.idPage = admPage.id;
    }
    if (admMenuParent!=null){
      this.admMenu.idMenuParent = admMenuParent.id;
    }

    if (this.admMenu.description.trim()) {
        if (this.admMenu.id) {
          this.admMenuService.update(this.admMenu).then((obj: AdmMenu) => {
            this.admMenu = obj;

            //this.selectedNodeMenu.label = this.admMenu.description;
            //this.selectedNodeMenu.data = this.admMenu;
  
            this.listaAdmMenu[this.admMenuService
              .findIndexById(this.listaAdmMenu, this.admMenu.id)] = this.admMenu;

            this.listaAdmMenu = [...this.listaAdmMenu];
            this.admMenu = emptyAdmMenu;
            this.updateMenusTree(this.listaAdmMenu);
      
            this.snackBar.open('Categoria de parâmetro Atualizada', 'Sucesso', { duration: 3000 });
          });
        } else {
          this.admMenuService.insert(this.admMenu).then((obj: AdmMenu) => {
            this.admMenu = obj;
            this.listaAdmMenu.push(this.admMenu);

            this.listaAdmMenu = [...this.listaAdmMenu];
            this.admMenu = emptyAdmMenu;
            this.updateMenusTree(this.listaAdmMenu);
    
            this.snackBar.open('Categoria de parâmetro Criada', 'Sucesso', { duration: 3000 });
          });
        }

    }
  }

  onDelete(admMenu: AdmMenu) {
    const dialogRef = this.dialog.open(AdmMenuDialogDelete, { 
      data: { 
        lista: this.listaAdmMenu, 
        entidade: admMenu
      } 
    });

    dialogRef.afterClosed().subscribe(result => {
      if (result){
        this.listaAdmMenu = result.lista;
        this.admMenu = result.entidade;
        this.confirmDelete();
      }
    });
      
  } 

  confirmDelete() {
    this.admMenuService.delete(this.admMenu.id).then(obj => {
      this.listaAdmMenu = this.listaAdmMenu.filter(val => val.id !== this.admMenu.id);
      this.admMenu = emptyAdmMenu;     
      this.updateMenusTree(this.listaAdmMenu); 
      this.snackBar.open('Categoria de parâmetro excluído', 'Sucesso', { duration: 3000 });
    });
  }  

  expandAll() {
    this.treeControl.expandAll();
  }

  collapseAll() {
    this.treeControl.collapseAll();
  } 

  deselectAll() {
    this.treeControl.dataNodes.forEach((node) => {
        this.selectRecursive(node, false);
    });
  } 

  private selectRecursive(node: MenuFlatNode, isSelect: boolean) {
    node.select = isSelect;
    if (node.data.children) {
        node.data.children.forEach((childNode) => {
            this.selectRecursive(childNode, isSelect);
        });
    }
  }

}

<div class="grid">
    <div class="col-12">
        <div class="card px-6 py-6">

            <mat-card styleClass="p-mb-2">
                <mat-card-header>
                    <mat-card-title>Categoria de parâmetro de configuração</mat-card-title>
                </mat-card-header>
                <mat-card-content>
                    <app-report-panel (typeReportChange)="onChangedTypeReport($event)" (forceDownloadChange)="onChangedForceDownload($event)"></app-report-panel>
                </mat-card-content>
            </mat-card>    

            <mat-toolbar styleClass="mb-4">
                <div class="my-2">
                    <button mat-raised-button color="primary" style="margin-right: 10px;" (click)="onInsert()">
                        <mat-icon>add</mat-icon> Adicionar
                    </button>

                    <button mat-raised-button color="accent" style="margin-right: 10px;" (click)="onEdit(selectedAdmMenu)"
                        [disabled]="!selectedAdmMenu || !listaAdmMenu || !listaAdmMenu.length">
                        <mat-icon>edit</mat-icon> Editar
                    </button>

                    <button mat-raised-button color="warn" (click)="onDelete(selectedAdmMenu)" 
                        [disabled]="!selectedAdmMenu || !listaAdmMenu || !listaAdmMenu.length">
                        <mat-icon>delete</mat-icon> Excluir
                    </button>
                </div>

                <span class="spacer"></span>

                <button mat-raised-button style="margin-right: 10px;" (click)="expandAll()">
                    Expandir todos
                </button>
                <button mat-raised-button style="margin-right: 10px;" (click)="collapseAll()">
                    Recolher todos
                </button>
                <button mat-raised-button (click)="onExport()">
                    <mat-icon>upload</mat-icon> Exportar
                </button>
            </mat-toolbar>

            <mat-tree [dataSource]="dataSource" [treeControl]="treeControl">
                <mat-tree-node *matTreeNodeDef="let node" matTreeNodePadding (click)="nodeSelect(node)">
                  <button mat-icon-button disabled></button>
                  <div [class.tree-item-select]="node.select" (click)="itemSelect(node)" style="cursor: pointer;">{{node.name}}</div>
                </mat-tree-node>
                <mat-tree-node *matTreeNodeDef="let node;when: hasChild" matTreeNodePadding (click)="nodeParentSelect(node)">
                  <button mat-icon-button matTreeNodeToggle
                          [attr.aria-label]="'Toggle ' + node.name">
                    <mat-icon class="mat-icon-rtl-mirror">
                      {{treeControl.isExpanded(node) ? 'expand_more' : 'chevron_right'}}
                    </mat-icon>
                  </button>
                  <div [class.tree-item-select]="node.select" (click)="itemParentSelect(node)" style="cursor: pointer;">{{node.name}}</div>
                </mat-tree-node>
            </mat-tree>
                            
        </div>
    </div>
</div>

// frontend/hfs-frontend-vuetify/src/admin/pages/AdmMenu.vue
<script lang="ts">
import { ref, onMounted, shallowRef } from 'vue';
import AdmMenuService from '../../admin/service/AdmMenuService';
import { AdmMenu, emptyAdmMenu } from '../api/AdmMenu';
import { ReportParamForm, emptyReportParamForm } from '../../base/models/ReportParamsForm';
import { ItypeReport, PDFReport, SelectItemGroup } from '../../base/services/ReportService';
import { SnackbarMessage, emptySnackbarMessage } from '../../base/models/SnackbarMessage';
import AdmPageService from '../service/AdmPageService';
import { TreeNode, emptyTreeNode } from '../../base/models/TreeNode';
import { AdmPage } from '../api/AdmPage';

export default {
    setup() {
        const snackbar = ref<SnackbarMessage>(emptySnackbarMessage);

        const listaAdmMenu = ref<AdmMenu[]>([]);
        const admMenuDialog = shallowRef(false)
        const deleteAdmMenuDialog = ref(false);

        const admMenu = ref(emptyAdmMenu);
        const selectedAdmMenu = ref<AdmMenu>(emptyAdmMenu);
        const submitted = ref(false);

        const admMenuService = new AdmMenuService();
        const admPageService = new AdmPageService();

        const selectedTypeReport = ref<ItypeReport>();
        const selectedForceDownload = ref(true);
        const reportParamForm = ref<ReportParamForm>(emptyReportParamForm);

        const cols = ref<any[]>([]);
        const exportColumns = ref<any[]>([]);

        const listaNodeMenu = ref<TreeNode[]>([]);
        const selectedNodeMenu = ref<TreeNode>(emptyTreeNode);

        const listaAdmPage = ref<AdmPage[]>([]);
        const listaAdmMenuParent = ref<AdmMenu[]>([]);

        onMounted(() => {
            atualizarArvore();

            cols.value = [
                { field: 'id', header: 'Id' },
                { field: 'description', header: 'Description' }
            ];

            exportColumns.value= cols.value.map(col => ({title: col.header, dataKey: col.field}));

            selectedTypeReport.value = PDFReport.value;
        });

        const atualizarArvore = () => {
            listaNodeMenu.value = [];
            listaAdmMenu.value = [];
            listaAdmMenuParent.value = [];
            
            admPageService.findAll().then(data => listaAdmPage.value = data);
        
            admMenuService.findAll().then(data => {
                listaAdmMenu.value = data;
        
                listaAdmMenuParent.value = listaAdmMenu.value.filter(menu => menu.idMenuParent == null);
        
                updateMenusTree(listaAdmMenu.value);
            });
        }
        
        const updateMenusTree = (listaMenu: AdmMenu[]): void => {
            const _listaNodeMenu: TreeNode[] = [];
            let _listaAdmMenuParent: AdmMenu[] = [];
            const menuRoot: TreeNode = {
                'key': '0',
                'label': 'Menu do sistema',
                'data': '0',
                'children': []
            };

            _listaAdmMenuParent = listaMenu.filter(menu => menu.idMenuParent == null);    

            _listaAdmMenuParent.forEach((itemMenu: AdmMenu) => {
                const m: TreeNode = {
                    'key' : itemMenu.id?.toString(),
                    'label': itemMenu.description,
                    'data': itemMenu,
                    'children': mountSubMenu(listaMenu, itemMenu)
                };
                if (menuRoot.children){
                    menuRoot.children.push(m);
                }                
            });

            _listaNodeMenu.push(menuRoot);

            listaNodeMenu.value = _listaNodeMenu;

            expandAll();
        }
        
        const isSubMenu = (menu: AdmMenu): boolean => {
            return menu.idPage === null;
        }
        
        const getAdmSubMenus = (listaMenu: AdmMenu[], menuPai: AdmMenu): AdmMenu[] => {
            return listaMenu.filter(menu => menu.idMenuParent === menuPai.id);
        }
        
        const mountSubMenu = (listaMenu: AdmMenu[], menu: AdmMenu): TreeNode[] => {
            const lstSubMenu: TreeNode[] = [];

            getAdmSubMenus(listaMenu, menu).forEach((subMenu: AdmMenu) => {
            
                if (isSubMenu(subMenu)) {
                    const m: TreeNode = {
                        'key' : subMenu.id?.toString(),
                        'label': subMenu.description,
                        'data': subMenu,
                        'children': mountSubMenu(listaMenu, subMenu)
                    };
                } else {
                    const m: TreeNode = {
                        'key' : subMenu.id?.toString(),
                        'label': subMenu.description,
                        'data': subMenu,
                        'children': []
                    };
                    lstSubMenu.push(m);
                }

            });

            return lstSubMenu;
        }

        const snackBar = (msg: string, duration: number) => {
            snackbar.value.open = true;
            snackbar.value.message = msg;
            snackbar.value.timeout = duration;
        }

        const onInsert = () => {
            admMenu.value = emptyAdmMenu;
            submitted.value = false;
            admMenuDialog.value = true;
        };

        const onEdit = (param: AdmMenu) => {
            admMenu.value = { ...param };
            admMenuDialog.value = true;
        };

        const hideDialog = () => {
            admMenuDialog.value = false;
            submitted.value = false;
        };

        const onSave = () => {
            submitted.value = true;
            if (admMenu.value.admPage!=null){
                if (admMenu.value.admPage.id){
                    admMenu.value.idPage = admMenu.value.admPage.id;
                }
            }
            if (admMenu.value.admMenuParent!=null){
                if (admMenu.value.admMenuParent.id){
                    admMenu.value.idMenuParent = admMenu.value.admMenuParent.id;
                }
            }

            if (admMenu.value.description && admMenu.value.description.trim()) {
                if (admMenu.value.id) {
                    admMenuService.update(admMenu.value).then((obj: AdmMenu) => {
                        admMenu.value = obj;

                        selectedNodeMenu.value.label = admMenu.value.description;
                        selectedNodeMenu.value.data = admMenu.value;

                        if (admMenu.value.id){
                            const index = admMenuService.findIndexById(listaAdmMenu.value, admMenu.value.id);
                            listaAdmMenu.value[index] = admMenu.value;

                            admMenuDialog.value = false;
                            admMenu.value = emptyAdmMenu;
                            updateMenusTree(listaAdmMenu.value);

                            snackBar('Categoria de parâmetro Atualizada', 3000);
                        }
                    });            
                } else {
                    admMenuService.insert(admMenu.value).then((obj: AdmMenu) => {
                        admMenu.value = obj;

                        listaAdmMenu.value.push(admMenu.value);

                        listaAdmMenuParent.value = listaAdmMenu.value.filter(menu => menu.idMenuParent == null);

                        admMenuDialog.value = false;
                        admMenu.value = emptyAdmMenu;
                        updateMenusTree(listaAdmMenu.value);

                        snackBar('Categoria de parâmetro Criada', 3000);
                    });            
                }
            }
        };

        const onDelete = (param: AdmMenu) => {
            deleteAdmMenuDialog.value = true;
            admMenu.value = { ...param };
        } 

        const confirmDelete = () => {
            deleteAdmMenuDialog.value = false;
            if (admMenu.value.id){
                admMenuService.delete(admMenu.value.id).then(() => {
                    listaAdmMenu.value = listaAdmMenu.value.filter((val: AdmMenu) => val.id !== admMenu.value.id);
                    admMenu.value = emptyAdmMenu;      
                    updateMenusTree(listaAdmMenu.value);       
                    snackBar('Categoria de parâmetro excluído', 3000);
                });
            }    
        }

        const onTypeReportChange = (param: { pTypeReport: SelectItemGroup }) => {            
            if (param.pTypeReport.value){
                selectedTypeReport.value = param.pTypeReport.value;
                reportParamForm.value = { reportType: param.pTypeReport.value.type, forceDownload: selectedForceDownload.value };
            }        
        }

        const onForceDownloadChange = (param: { forceDownload: boolean }) => {
            selectedForceDownload.value = param.forceDownload;
            if (selectedTypeReport.value){
                reportParamForm.value = { reportType: selectedTypeReport.value.type, forceDownload: param.forceDownload };
            }
        }

        const onExport = () => {
            admMenuService.report(reportParamForm.value).then(() => {
                snackBar('Categoria de parâmetro exportada', 3000);
            });            
        }

        const expandAll = () => {
        };

        const collapseAll = () => {
        };

        const expandNode = (node: TreeNode) => {
        };

        return { listaAdmMenu, admMenu, submitted, snackbar, admMenuDialog, hideDialog, listaAdmPage, listaAdmMenuParent,
            deleteAdmMenuDialog, confirmDelete, selectedAdmMenu, emptyAdmMenu, expandAll, collapseAll,
            onInsert, onEdit, onDelete, onSave, onExport, onTypeReportChange, onForceDownloadChange }
    }
}        
</script>

<template>
    <div class="grid">
        <div class="col-12">
            <div class="card px-6 py-6">
                <v-snackbar v-model="snackbar.open" :timeout="snackbar.timeout" location="top">
                    {{ snackbar.message }}
                    <template v-slot:actions>
                        <v-btn color="red" density="compact" icon="close" @click="snackbar.open = false"></v-btn>
                    </template>
                </v-snackbar>
                <v-card-item>
                    <v-card-title>Categoria de parâmetro de configuração</v-card-title>
                </v-card-item>
                <v-card-text>
                    <ReportPanel @changeTypeReport="onTypeReportChange" @changeForceDownload="onForceDownloadChange"></ReportPanel>
                </v-card-text>

                <v-toolbar>
                    <v-btn prepend-icon="add" @click="onInsert" variant="elevated" color="green" :style="{ marginRight: '10px' }">Adicionar</v-btn>
                    <v-btn prepend-icon="delete" @click="onEdit(selectedAdmMenu)" variant="elevated" color="yellow"
                        :disabled="selectedAdmMenu === emptyAdmMenu" :style="{ marginRight: '10px' }">Editar</v-btn>
                    <v-btn prepend-icon="delete" @click="onDelete(selectedAdmMenu)" variant="elevated" color="red"
                        :disabled="selectedAdmMenu === emptyAdmMenu" :style="{ marginRight: '10px' }">Excluir</v-btn>
                        
                    <span class="spacer"></span>

                    <v-btn @click="expandAll" variant="elevated" :style="{ marginRight: '10px' }">Expandir todos</v-btn>
                    <v-btn @click="collapseAll" variant="elevated" :style="{ marginRight: '10px' }">Recolher todos</v-btn>

                    <v-btn prepend-icon="upload" @click="onExport" variant="elevated" color="indigo-darken-3">Exportar</v-btn>
                </v-toolbar>

                <v-dialog v-model="admMenuDialog" width="500">
                    <v-card title="Detalhes da categoria de parâmetro">
                        <v-card-text>
                            <v-row>
                                <v-select label="Página" v-model="admMenu.admPage"
                                    :items="listaAdmPage" item-title="description"></v-select>
                            </v-row>
                            <v-row>
                                <v-text-field label="Nome do menu" v-model="admMenu.description" required
                                    :class="{ 'text-red': submitted && !admMenu.description }">
                                </v-text-field>
                            </v-row>
                            <v-row>
                                <small class="text-red" v-if="submitted && !admMenu.description">O nome do menu é obrigatório.</small>
                            </v-row>
                            <v-row>
                                <v-select label="Menu pai" v-model="admMenu.admMenuParent"
                                    :items="listaAdmMenuParent" item-title="description"></v-select>
                            </v-row>
                            <v-row>
                                <v-text-field type="number" label="Ordem" v-model="admMenu.order" required
                                    :class="{ 'text-red': submitted && !admMenu.order }">
                                </v-text-field>
                            </v-row>
                            <v-row>
                                <small class="text-red" v-if="submitted && !admMenu.order">A ordem é obrigatória.</small>
                            </v-row>
                        </v-card-text>
                        <v-divider></v-divider>
                        <v-card-actions>
                            <v-spacer></v-spacer>
                            <v-btn prepend-icon="cancel" color="secondary" :style="{ marginRight: '10px' }" @click="hideDialog" variant="elevated">Cancelar</v-btn>
                            <v-btn prepend-icon="check" color="primary" @click="onSave" variant="elevated">Salvar</v-btn>
                        </v-card-actions>
                    </v-card>
                </v-dialog>

                <v-dialog v-model="deleteAdmMenuDialog" max-width="450" persistent>
                    <v-card prepend-icon="warning" title="Confirme">
                        <v-card-text>
                            <span v-if="admMenu">Tem certeza de que deseja excluir <b>{{ admMenu.description }}</b>?</span>
                        </v-card-text>                        
                        <template v-slot:actions>
                            <v-spacer></v-spacer>
                            <v-btn prepend-icon="cancel" color="secondary" :style="{ marginRight: '10px' }" 
                                @click="deleteAdmMenuDialog = false" variant="elevated">Não</v-btn>
                            <v-btn prepend-icon="check" color="primary" @click="confirmDelete" variant="elevated">Sim</v-btn>
                        </template>
                    </v-card>
                </v-dialog>

            </div>
        </div>
    </div>
</template>

<style>
.spacer {
    flex: 1 1 auto;
}
</style>
