// frontend/hfs-frontend-vue/src/admin/pages/AdmProfile.vue
<script lang="ts">
import { FilterMatchMode } from 'primevue/api';
import { ref, onMounted, onBeforeMount } from 'vue';
import { useToast } from 'primevue/usetoast';
import AdmProfileService from '../../admin/service/AdmProfileService';
import { ExportService } from '../../base/services/ExportService';
import { AdmProfile, cleanAdmProfile, emptyAdmProfile } from '../api/AdmProfile';
import { ReportParamForm, emptyReportParamForm } from '../../base/models/ReportParamsForm';
import { ItypeReport, PDFReport, SelectItemGroup } from '../../base/services/ReportService';
import { MenuItem } from '../../base/models/MenuItem';
import { AdmPage } from '../api/AdmPage';
import AdmPageService from '../service/AdmPageService';

export default {
    setup() {
        const toast = useToast();

        const listaAdmProfile = ref<AdmProfile[]>([]);
        const admProfileDialog = ref(false);
        const deleteAdmProfileDialog = ref(false);
        const deleteAdmProfilesDialog = ref(false);
        const admProfile = ref(emptyAdmProfile);
        const selectedAdmProfiles = ref();
        const dt = ref(null);
        const filters = ref({});
        const cols = ref();
        const exportColumns = ref([]);
        const submitted = ref(false);

        const admProfileService = new AdmProfileService();
        const admPageService = new AdmPageService();
        const exportService = new ExportService();

        const selectedTypeReport = ref<ItypeReport>();
        const selectedForceDownload = ref(true);
        const reportParamForm = ref<ReportParamForm>(emptyReportParamForm);

        const popupMenu = ref();
        const itemsMenuLinha = ref<MenuItem[]>([]);

        const profilePages = ref<AdmPage[][]>();

        onBeforeMount(() => {
            initFilters();
        });

        onMounted(() => {
            admProfileService.findAll().then((data) => (listaAdmProfile.value = data));

            selectedTypeReport.value = PDFReport.value;

            itemsMenuLinha.value = [{ label: "Editar" }, { label: "Excluir" }];

            cols.value = [
                { field: 'id', header: 'Id' },
                { field: 'description', header: 'Descrição' },
                { field: 'profilePages', header: 'Páginas(s) do perfil' }
            ];

            exportColumns.value = cols.value.map((col: { header: any; field: any; }) => ({title: col.header, dataKey: col.field}));

        });

        const toggleMenu = (event: any, rowData: AdmProfile) => {
            itemsMenuLinha.value = [];

            itemsMenuLinha.value.push({
                label: 'Editar',
                command: (event: any) => {
                    onEdit(rowData);
                }
            });

            itemsMenuLinha.value.push({
                label: 'Excluir',
                command: (event: any) => {
                    onDelete(rowData);
                }
            });
            
            popupMenu.value.toggle(event);
        }

        const loadAdmPages = () => {
            let sourcePages: AdmPage[] = [];
            let targetPages: AdmPage[] = [];
            
            if (admProfile.value.id != null) {
                targetPages = [...admProfile.value.admPages];
            }

            admPageService.findAll().then(pages => {
                sourcePages = pages.filter(page => !targetPages.find(target => target.id === page.id));

                profilePages.value = [sourcePages, targetPages];
            });
        }        

        const mostrarListar = () => {
            if (admProfileDialog.value)
                return { display: 'none' };
            else
                return { display: '' };
        }

        const mostrarEditar = () => {
            if (admProfileDialog.value)
                return { display: '' };
            else
                return { display: 'none' };
        }

        const onClean = () => {
            admProfile.value = cleanAdmProfile;
            loadAdmPages();
        }

        const onInsert = () => {
            admProfile.value = emptyAdmProfile;
            submitted.value = false;
            admProfileDialog.value = true;
            loadAdmPages();
        };

        const onEdit = (param: AdmProfile) => {
            admProfile.value = { ...param };
            admProfileDialog.value = true;
            loadAdmPages();
        };

        const hideDialog = () => {
            admProfileDialog.value = false;
            submitted.value = false;
        };

        const onSave = () => {
            submitted.value = true;
            admProfile.value.admPages = [];
            profilePages.value?.forEach((value: AdmPage[]) => {
                let sourcePages: AdmPage[] = value;

                sourcePages.forEach((value: AdmPage) => {
                    let targetPages: AdmPage = value;
                    admProfile.value.admPages.push(targetPages);
                });
            });

            if (admProfile.value.description && admProfile.value.description.trim()) {
                if (admProfile.value.id) {
                    admProfileService.update(admProfile.value).then((obj: AdmProfile) => {
                        admProfile.value = obj;

                        const index = admProfileService.findIndexById(listaAdmProfile.value, admProfile.value.id);
                        listaAdmProfile.value[index] = admProfile.value;

                        toast.add({severity:'success', summary: 'Successful', detail: 'Perfil Atualizada', life: 3000});
                    });            
                } else {
                    admProfileService.insert(admProfile.value).then((obj: AdmProfile) => {
                        admProfile.value = obj;

                        listaAdmProfile.value.push(admProfile.value);
                        toast.add({ severity: 'success', summary: 'Successful', detail: 'Perfil Criada', life: 3000 });
                    });            
                }

                admProfileDialog.value = false;
                admProfile.value = emptyAdmProfile;
            }
        };

        const deleteSelected = () => {
            deleteAdmProfilesDialog.value = true;
        }

        const onDelete = (param: AdmProfile) => {
            deleteAdmProfileDialog.value = true;
            admProfile.value = { ...param };
        } 

        const confirmDeleteSelected = () => {
            deleteAdmProfilesDialog.value = false;
            listaAdmProfile.value = listaAdmProfile.value.filter((val: AdmProfile) => !selectedAdmProfiles.value.includes(val));

            let excluiu = false;
            selectedAdmProfiles.value.forEach((item: AdmProfile) => {
                admProfileService.delete(item.id).then(obj => {
                    excluiu = true;
                });
            });

            if (excluiu) {
                toast.add({ severity: 'success', summary: 'Sucesso', detail: 'Perfis excluídos', life: 3000 });
                selectedAdmProfiles.value = [];
            }
        }

        const confirmDelete = () => {
            deleteAdmProfileDialog.value = false;
            admProfileService.delete(admProfile.value.id).then(obj => {
                listaAdmProfile.value = listaAdmProfile.value.filter((val: AdmProfile) => val.id !== admProfile.value.id);
                admProfile.value = emptyAdmProfile;        
                toast.add({ severity: 'success', summary: 'Sucesso', detail: 'Perfil excluído', life: 3000 });
            });
        }

        const onTypeReportChange = (param: { pTypeReport: SelectItemGroup }) => {
            if (param.pTypeReport.value){
                selectedTypeReport.value = param.pTypeReport.value;
                reportParamForm.value = { reportType: param.pTypeReport.value.type, forceDownload: selectedForceDownload.value };
            }        
        }

        const onForceDownloadChange = (param: { forceDownload: boolean }) => {
            selectedForceDownload.value = param.forceDownload;
            if (selectedTypeReport.value){
                reportParamForm.value = { reportType: selectedTypeReport.value.type, forceDownload: param.forceDownload };
            }
        }

        const onExport = () => {
            admProfileService.report(reportParamForm.value).then(() => {
                toast.add({ severity: 'info', summary: 'Perfil exportada', 
                    detail: 'Perfil exportada', life: 3000 });
            });
        }

        const initFilters = () => {
            filters.value = {
                global: { value: null, matchMode: FilterMatchMode.CONTAINS }
            };
        };

        const exportPdf = () => {
            const head: string[] = [];
            const data: any[] = [];

            exportColumns.value.forEach((item: { title: string; }) => head.push(item.title));
            listaAdmProfile.value.forEach((item: AdmProfile) => data.push(
                [item.id, item.description, item.profilePages]
            ));

            exportService.exportPdf(head, data, 'perfis.pdf');
        }

        const exportExcel = () => {
            exportService.exportExcel(listaAdmProfile.value, 'perfis');
        }


        return { listaAdmProfile, admProfile, filters, submitted, itemsMenuLinha, toggleMenu, popupMenu,
            selectedAdmProfiles, deleteSelected, admProfileDialog, hideDialog, mostrarListar, mostrarEditar, onClean,
            deleteAdmProfileDialog, confirmDelete, deleteAdmProfilesDialog, profilePages,
            onInsert, onEdit, onDelete, onSave, onExport, onTypeReportChange, onForceDownloadChange,
            confirmDeleteSelected }
    }
}        
</script>

<template>
    <div class="grid">
        <div class="col-12">
            <div class="card px-6 py-6" :style="mostrarListar()">
                <!-- <Toast /> -->
                <Panel header="Perfil" class="p-mb-2">
                    <ReportPanel @changeTypeReport="onTypeReportChange" @changeForceDownload="onForceDownloadChange"></ReportPanel>
                </Panel>                
                <Toolbar class="mb-4">
                    <template v-slot:start>
                        <div class="my-2">
                            <Button label="Adicionar" icon="pi pi-plus" class="p-button-success mr-2" @click="onInsert" />
                            <Button label="Excluir" icon="pi pi-trash" class="p-button-danger" @click="deleteSelected" 
                                :disabled="!selectedAdmProfiles || !selectedAdmProfiles.length" />
                        </div>
                    </template>

                    <template v-slot:end>
                        <Button label="Exportar" icon="pi pi-upload" class="p-button-help" @click="onExport" />
                    </template>
                </Toolbar>

                <Menu ref="popupMenu" id="popup_menu" :model="itemsMenuLinha" :popup="true" />

                <DataTable
                    ref="dt" paginatorPosition="both"
                    :value="listaAdmProfile"
                    v-model:selection="selectedAdmProfiles"
                    dataKey="id"
                    :paginator="true"
                    :rows="10"
                    :filters="filters"
                    paginatorTemplate="FirstPageLink PrevPageLink PageLinks NextPageLink LastPageLink CurrentPageReport RowsPerPageDropdown"
                    :rowsPerPageOptions="[10,30,50,100,150,200]" emptyMessage="Nenhum registro encontrado."
                    currentPageReportTemplate="Mostrando {first} até {last} de {totalRecords} entradas"
                    responsiveLayout="scroll"
                >
                    <template #header>
                        <div class="flex flex-column md:flex-row md:justify-content-between md:align-items-center">
                            <h5 class="m-0">Gerenciar páginas</h5>
                            <span class="block mt-2 md:mt-0 p-input-icon-left">
                                <i class="pi pi-search" />
                                <InputText v-model="filters['global'].value" placeholder="Procurar..." />
                            </span>
                        </div>
                    </template>

                    <Column selectionMode="multiple" headerStyle="width: 3rem"></Column>
                    <Column field="id" header="Id" :sortable="true" headerStyle="width:5%; min-width:5rem;">
                        <template #body="slotProps">
                            <span class="p-column-title">Id</span>
                            {{ slotProps.data.id }}
                        </template>
                    </Column>
                    <Column field="description" header="Descrição" :sortable="true" headerStyle="min-width:8rem;">
                        <template #body="slotProps">
                            <span class="p-column-title">Descrição</span>
                            {{ slotProps.data.description }}
                        </template>
                    </Column>
                    <Column field="profilePages" header="Páginas(s) do perfil" :sortable="true" headerStyle="min-width:8rem;">
                        <template #body="slotProps">
                            <span class="p-column-title">Páginas(s) do perfil</span>
                            {{ slotProps.data.profilePages }}
                        </template>
                    </Column>
                    <Column headerStyle="min-width:10rem;">
                        <template #body="slotProps">
                            <div class="flex">
                                <Button link icon="pi pi-ellipsis-v" @click="toggleMenu($event, slotProps.data)" 
                                    aria-haspopup="true" aria-controls="popup_menu" />
                            </div>
                        </template>
                    </Column>

                    <template #footer>
                        <div class="p-d-flex p-ai-center p-jc-between">
                            No total existem {{listaAdmProfile ? listaAdmProfile.length : 0 }} perfis.
                        </div>
                    </template>

                </DataTable>
            </div>

            <div :style="mostrarEditar()">
                <!-- <Toast /> -->
                <Panel header="Detalhes do perfil" class="p-mb-2">
                    <Toolbar class="mb-4">
                        <template v-slot:start>
                        </template>
                        <template v-slot:end>
                            <div class="my-2">
                                <Button label="Cancelar" icon="pi pi-times" class="p-button-secondary mr-2" @click="hideDialog"></button>
                                <Button label="Limpar" icon="pi pi-star-o" class="p-button-primary mr-2" @click="onClean"></button>
                                <Button label="Salvar" icon="pi pi-check" class="p-button-success" @click="onSave"></button>        
                            </div>
                        </template>
                    </Toolbar>         
                    <div class="card p-fluid">
                        <div class="field">
                            <label for="description">Descrição</label>
                            <InputText id="description" v-model="admProfile.description" required="true"
                                :class="{ 'p-invalid': submitted && !admProfile.description }" />
                            <small class="p-invalid" v-if="submitted && !admProfile.description">A descrição é obrigatória.</small>
                        </div>
                        <div class="field">
                            <label for="profilePages">Página(s):</label>
                            <PickList v-model="profilePages" dataKey="id">
                                <template #sourceheader>Disponível</template>
                                <template #targetheader>Selecionada</template>
                                <template #item="slotProps">
                                    <div>
                                        {{slotProps.item.description}}
                                    </div>
                                </template>
                            </PickList>                                
                        </div>
                    </div>               
                </Panel>                
            </div>

            <Dialog v-model:visible="deleteAdmProfileDialog" :style="{ width: '450px' }" header="Confirme" :modal="true">
                <div class="flex align-items-center justify-content-center">
                    <i class="pi pi-exclamation-triangle mr-3" style="font-size: 2rem" />
                    <span v-if="admProfile">Tem certeza de que deseja excluir <b>{{ admProfile.description }}</b>?</span>
                </div>
                <template #footer>
                    <Button label="Não" icon="pi pi-times" class="p-button-text" @click="deleteAdmProfileDialog = false" />
                    <Button label="Sim" icon="pi pi-check" class="p-button-text" @click="confirmDelete" />
                </template>
            </Dialog>

            <Dialog v-model:visible="deleteAdmProfilesDialog" :style="{ width: '450px' }" header="Confirme" :modal="true">
                <div class="flex align-items-center justify-content-center">
                    <i class="pi pi-exclamation-triangle mr-3" style="font-size: 2rem" />
                    <span v-if="admProfile">Tem certeza de que deseja excluir as categorias de parâmetros selecionadas?</span>
                </div>
                <template #footer>
                    <Button label="Não" icon="pi pi-times" class="p-button-text" @click="deleteAdmProfilesDialog = false" />
                    <Button label="Sim" icon="pi pi-check" class="p-button-text" @click="confirmDeleteSelected" />
                </template>
            </Dialog>
        </div>
    </div>
</template>

// frontend/hfs-frontend/src/app/admin/pages/adm-profile/adm-profile.component.ts
import { Component, OnInit } from '@angular/core';
import { MessageService, MenuItem } from 'primeng/api';
import { ExportService } from 'src/app/base/services/export.service';
import { ReportParamForm } from 'src/app/base/models/ReportParamsForm';
import { ItypeReport } from 'src/app/base/services/ReportService';
import { AdmProfileService } from '../../service/AdmProfileService';
import { AdmProfile, cleanAdmProfile } from '../../api/AdmProfile';
import { AdmPage } from '../../api/AdmPage';
import { AdmPageService } from '../../service/AdmPageService';
import { Menu } from 'primeng/menu';
import { Table } from 'primeng/table';

@Component({
  templateUrl: './adm-profile.component.html',
  providers: [MessageService, AdmProfileService]
})
export class AdmProfileComponent implements OnInit {

  admProfileDialog: boolean;

  listaAdmProfile: AdmProfile[] = [];

  admProfile: AdmProfile = {};

  selectedAdmProfile: AdmProfile[] = [];

  submitted: boolean;

  cols: any[];

  exportColumns: any[];

  reportParamForm: ReportParamForm;

  deleteAdmProfileDialog: boolean = false;

  deleteAdmProfilesDialog: boolean = false;

  itemsMenuLinha: MenuItem[];

  sourcePages: AdmPage[];
  targetPages: AdmPage[];

  constructor(private messageService: MessageService,
    private admProfileService: AdmProfileService,
    private admPageService: AdmPageService,
    private exportService: ExportService) {
      this.reportParamForm = {
        reportType: 'PDF',
        forceDownload: true
      };

      this.itemsMenuLinha = [{ label: "Editar" }, { label: "Excluir" }];
  }

  toggleMenu(menu: Menu, event: any, rowData: AdmProfile) {
    this.itemsMenuLinha = [];

    this.itemsMenuLinha.push({
      label: 'Editar',
      command: (event: any) => {
        this.onEdit(rowData);
      }
    });

    this.itemsMenuLinha.push({
      label: 'Excluir',
      command: (event: any) => {
        this.onDelete(rowData);
      }
    });

    menu.toggle(event);
  }

  ngOnInit(): void {
    this.admProfileService
      .findAll()
      .then(data => this.listaAdmProfile = data);

    this.cols = [
      { field: 'id', header: 'Id' },
      { field: 'description', header: 'Descrição' },
      { field: 'profilePages', header: 'Páginas(s) do perfil' }
    ];

    this.exportColumns = this.cols.map(col => ({title: col.header, dataKey: col.field}));
  }

  private loadAdmPages(): void {
    this.targetPages = [];
    if (this.admProfile.id != null) {
      // this.admPageService.findPagesByProfile(this.admProfile).then(data => this.targetPages = data);
      this.targetPages = [...this.admProfile.admPages];
    }
    this.admPageService.findAll().then(pages => {
      this.sourcePages = pages.filter(pager => !this.targetPages.find(target => target.id === pager.id));
    });
  }

  mostrarListar() {
    if (this.admProfileDialog)
        return {display:'none'};
    else
        return {display:''};
  }

  mostrarEditar() {
      if (this.admProfileDialog)
          return {display:''};
      else
          return {display:'none'};
  }

  onClean() {
    this.admProfile = cleanAdmProfile;
    this.loadAdmPages();
  }

  onSave() {
    this.submitted = true;
    this.admProfile.admPages = [];
    this.targetPages.forEach(item => {
      this.admProfile.admPages.push(item)
    });

    if (this.admProfile.description.trim()) {
        if (this.admProfile.id) {
          this.admProfileService.update(this.admProfile).then((obj: AdmProfile) => {
            this.admProfile = obj;

            this.listaAdmProfile[
              this.admProfileService.findIndexById(this.listaAdmProfile, this.admProfile.id)] = this.admProfile;
            this.messageService.add({ severity: 'success', summary: 'Sucesso', detail: 'Perfil Atualizado', life: 3000 });
          });
        } else {
          this.admProfileService.insert(this.admProfile).then((obj: AdmProfile) => {
            this.admProfile = obj;

            this.listaAdmProfile.push(this.admProfile);
            this.messageService.add({ severity: 'success', summary: 'Sucesso', detail: 'Perfil Criado', life: 3000 });
          });
        }

        this.listaAdmProfile = [...this.listaAdmProfile];
        this.admProfileDialog = false;
        this.admProfile = {};
    }
  }

  onChangedTypeReport(typeReport: ItypeReport) {
    this.reportParamForm.reportType = typeReport.type;
  }

  onChangedForceDownload(forceDownload: boolean) {
    this.reportParamForm.forceDownload = forceDownload;
  }

  onExport() {
    this.admProfileService.report(this.reportParamForm).then(() => {
      this.messageService.add({severity: 'info', summary: 'Perfil Exportado', detail: 'Perfil Exportado', life: 1000});
    });
  }

  onInsert() {
    this.admProfile = {};
    this.submitted = false;
    this.admProfileDialog = true;
    this.loadAdmPages();
  }

  onEdit(admProfile: AdmProfile) {
    this.admProfile = { ...admProfile };
    this.admProfileDialog = true;
    this.loadAdmPages();
  }

  hideDialog() {
    this.admProfileDialog = false;
    this.submitted = false;
  }

  deleteSelected() {
    this.deleteAdmProfilesDialog = true;
  }

  onDelete(admProfile: AdmProfile) {
    this.deleteAdmProfileDialog = true;
    this.admProfile = { ...admProfile };
  }

  confirmDeleteSelected() {    
    this.deleteAdmProfilesDialog = false;
    this.listaAdmProfile = this.listaAdmProfile.filter(val => !this.selectedAdmProfile.includes(val));

    let excluiu = false;
    this.selectedAdmProfile.forEach((item) => {
      this.admProfileService.delete(item.id).then(obj => {
        excluiu = true;
      });
    });

    if (excluiu) {
      this.messageService.add({ severity: 'success', summary: 'Sucesso', detail: 'Perfil(s) excluídos', life: 3000 });
      this.selectedAdmProfile = [];  
    }
  }

  confirmDelete() {
    this.deleteAdmProfileDialog = false;
    this.admProfileService.delete(this.admProfile.id).then(obj => {
      this.listaAdmProfile = this.listaAdmProfile.filter(val => val.id !== this.admProfile.id);
      this.admProfile = {};
      this.messageService.add({ severity: 'success', summary: 'Sucesso', detail: 'Perfil Excluído', life: 3000 });
    });
  }

  onGlobalFilter(table: Table, event: Event) {
    table.filterGlobal((event.target as HTMLInputElement).value, 'contains');
  }

  exportPdf() {
    const head: string[] = [];
    const data: any[] = [];

    this.exportColumns.forEach(item => head.push(item.title));
    this.listaAdmProfile.forEach(item => data.push(
      [item.id, item.description, item.profilePages]
    ));

    this.exportService.exportPdf(head, data, 'perfis.pdf');
  }

  exportExcel() {
    this.exportService.exportExcel(this.listaAdmProfile, 'perfis');
  }

}

<div class="grid">
    <div class="col-12">

        <div class="card px-6 py-6" [style]="mostrarListar()">
            <p-toast></p-toast>
            <p-panel header="Perfil" styleClass="p-mb-2">
                <app-report-panel (typeReportChange)="onChangedTypeReport($event)" (forceDownloadChange)="onChangedForceDownload($event)"></app-report-panel>
            </p-panel>            
            <p-toolbar styleClass="mb-4">
                <ng-template pTemplate="left">
                    <div class="my-2">
                        <button pButton pRipple label="Adicionar" icon="pi pi-plus" class="p-button-success mr-2" (click)="onInsert()"></button>
                        <button pButton pRipple label="Excluir" icon="pi pi-trash" class="p-button-danger" (click)="deleteSelected()" 
                        [disabled]="!selectedAdmProfile || !selectedAdmProfile.length"></button>
                    </div>
                </ng-template>

                <ng-template pTemplate="right">
                    <button pButton pRipple label="Exportar" icon="pi pi-upload" class="p-button-help" (click)="onExport()"></button>
                </ng-template>
            </p-toolbar>

            <p-menu #popupMenu [model]="itemsMenuLinha" [popup]="true"></p-menu>

            <p-table #dt [value]="listaAdmProfile" [columns]="cols" responsiveLayout="scroll" [rows]="10" 
                [globalFilterFields]="['description']" paginatorPosition="both"
                [paginator]="true" [rowsPerPageOptions]="[10,30,50,100,150,200]" [showCurrentPageReport]="true" 
                currentPageReportTemplate="Mostrando {first} até {last} de {totalRecords} entradas" 
                [(selection)]="selectedAdmProfile" selectionMode="multiple" [rowHover]="true" dataKey="id">
                <ng-template pTemplate="caption">
                    <div class="flex flex-column md:flex-row md:justify-content-between md:align-items-center">
                        <h5 class="m-0">Gerenciar parâmetros</h5>
                        <span class="block mt-2 md:mt-0 p-input-icon-left">
                            <i class="pi pi-search"></i>
                            <input pInputText type="text" (input)="onGlobalFilter(dt, $event)" placeholder="Procurar..."  class="w-full sm:w-auto"/>
                        </span>
                    </div>
                </ng-template>
                <ng-template pTemplate="header">
                    <tr>
                        <th style="width: 3rem">
                            <p-tableHeaderCheckbox></p-tableHeaderCheckbox>
                        </th>                        
                        <th pSortableColumn="id">Id <p-sortIcon field="id"></p-sortIcon></th>
                        <th pSortableColumn="description">Descrição <p-sortIcon field="description"></p-sortIcon></th>
                        <th pSortableColumn="profilePages">Páginas(s) do perfil<p-sortIcon field="profilePages"></p-sortIcon></th>
                        <th></th>
                    </tr>
                </ng-template>
                <ng-template pTemplate="body" let-admProfile>
                    <tr>
                        <td>
                            <p-tableCheckbox [value]="admProfile"></p-tableCheckbox>
                        </td>
                        <td style="width:5%; min-width:5rem;"><span class="p-column-title">Id</span>
                            {{admProfile.id}}
                        </td>
                        <td style="min-width:8rem;">
                            <span class="p-column-title">Descrição</span>
                            {{admProfile.description}}
                        </td>                        
                        <td style="min-width:8rem;">
                            <span class="p-column-title">Páginas(s) do perfil</span>
                            {{admProfile.profilePages}}
                        </td>
                        <td style="width: 10px;">
                            <div class="flex">                                
                                <a *ngIf="itemsMenuLinha" (click)="toggleMenu(popupMenu, $event, admProfile)" style="cursor: pointer;">
                                    <i class="pi pi-ellipsis-v"></i>
                                </a>
                            </div>
                        </td>
                    </tr>
                </ng-template>
                <ng-template pTemplate="summary">
                    <div class="p-d-flex p-ai-center p-jc-between">
                        No total existem {{listaAdmProfile ? listaAdmProfile.length : 0 }} perfis.
                    </div>
                </ng-template>            
            </p-table>
        </div>        

        <div [style]="mostrarEditar()">

            <p-panel header="Detalhes do perfil" styleClass="p-mb-2">
                <p-toast></p-toast>
                <p-toolbar styleClass="mb-4">
                    <ng-template pTemplate="left">
                    </ng-template>
                    <ng-template pTemplate="right">
                        <div class="my-2">
                            <button pButton pRipple label="Cancelar" icon="pi pi-times" class="p-button-secondary mr-2" (click)="hideDialog()"></button>
                            <button pButton pRipple label="Limpar" icon="pi pi-star-o" class="p-button-primary mr-2" (click)="onClean()"></button>
                            <button pButton pRipple label="Salvar" icon="pi pi-check" class="p-button-success" (click)="onSave()"></button>        
                        </div>
                    </ng-template>
                </p-toolbar>
    
                <div class="card p-fluid">
                    <div class="field">
                        <label for="description">Descrição</label>
                        <input type="text" pInputText id="description" [(ngModel)]="admProfile.description" required
                            [ngClass]="{'ng-invalid ng-dirty' : submitted && !admProfile.description}" />
                        <small class="ng-dirty ng-invalid" *ngIf="submitted && !admProfile.description">A descrição é obrigatória.</small>
                    </div>
                    <div class="field">
                        <label for="profilePages">Página(s):</label>
                        <p-pickList id="profilePages" 
                            [source]="sourcePages" [target]="targetPages" sourceHeader="Disponível" targetHeader="Selecionada" [dragdrop]="true"
                            [responsive]="true" [sourceStyle]="{'height':'30rem'}" [targetStyle]="{'height':'30rem'}" filterBy="description"
                            sourceFilterPlaceholder="Pesquisar por descrição" targetFilterPlaceholder="Pesquisar por descrição">
                            <ng-template let-page pTemplate="item">
                                <div class="page-item">
                                    <div>{{page.description}}</div>
                                </div>
                            </ng-template>
                        </p-pickList>
                    </div>
            
                </div>
            </p-panel>              

        </div>        

        <p-dialog [(visible)]="deleteAdmProfileDialog" header="Confirme" [modal]="true" [style]="{width:'450px'}">
            <div class="flex align-items-center justify-content-center">
                <i class="pi pi-exclamation-triangle mr-3" style="font-size: 2rem"></i>
                <span *ngIf="admProfile">Tem certeza de que deseja excluir <b>{{admProfile.description}}</b>?</span>
            </div>
            <ng-template pTemplate="footer">
                <button pButton pRipple icon="pi pi-times" class="p-button-text" label="Não" (click)="deleteAdmProfileDialog = false"></button>
                <button pButton pRipple icon="pi pi-check" class="p-button-text" label="Sim" (click)="confirmDelete()"></button>
            </ng-template>
        </p-dialog>

        <p-dialog [(visible)]="deleteAdmProfilesDialog" header="Confirme" [modal]="true" [style]="{width:'450px'}">
            <div class="flex align-items-center justify-content-center">
                <i class="pi pi-exclamation-triangle mr-3" style="font-size: 2rem"></i>
                <span>Tem certeza de que deseja excluir os perfis selecionados?</span>
            </div>
            <ng-template pTemplate="footer">
                <button pButton pRipple icon="pi pi-times" class="p-button-text" label="Não" (click)="deleteAdmProfilesDialog = false"></button>
                <button pButton pRipple icon="pi pi-check" class="p-button-text" label="Sim" (click)="confirmDeleteSelected()"></button>
            </ng-template>
        </p-dialog>

    </div>
</div>
