// frontend/hfs-frontend-jest/src/app/hfsfullstack/pages/funcionario/funcionario.component.ts
import { Component, OnInit } from '@angular/core';
import { MessageService } from 'primeng/api';
import { Funcionario, cleanFuncionario } from '../../api/funcionario';
import { FuncionarioService } from '../../service/funcionario.service';
import { LazyLoadEvent } from 'primeng/api';
import { ItypeReport } from '../../../base/services/ReportService';
import { ReportParamForm } from '../../../base/models/ReportParamsForm';
import { ExportService } from '../../../base/services/export.service';
import { BaseUtilService } from '../../../base/util/base-util.service';

@Component({
    templateUrl: './funcionario.component.html',
    providers: [MessageService, ExportService, FuncionarioService, BaseUtilService]
})
export class FuncionarioComponent implements OnInit {

    funcionarioDialog: boolean = false;

    deleteFuncionarioDialog: boolean = false;

    deleteFuncionariosDialog: boolean = false;

    listaFuncionario: Funcionario[] = [];

    funcionario: Funcionario = {};

    selectedFuncionario: Funcionario[] = [];

    submitted: boolean = false;

    cols: any[];

    exportColumns: any[];
  
    reportParamForm: ReportParamForm;
  
    rowsPerPageOptions = [5, 10, 30, 50, 100, 150, 200];

    totalRecords!: number;

    loading: boolean = false;

    selectAll: boolean = false;

    constructor(private funcionarioService: FuncionarioService, 
        private messageService: MessageService,
        private exportService: ExportService,
        private baseUtilService: BaseUtilService) { }

    ngOnInit() {
        this.cols = [
            { field: 'id', header: 'Código' },
            { field: 'nome', header: 'Nome' },
            { field: 'cpfFormatado', header: 'Cpf' },
            { field: 'email', header: 'Email' },
            { field: 'telefone', header: 'Telefone' },
            { field: 'celular', header: 'Celular' },
            { field: 'setor', header: 'Setor' },
            { field: 'codCargo', header: 'CodCargo' },
            { field: 'cargo', header: 'Cargo' },
            { field: 'dataAdmissaoFormatada', header: 'Data Admissão' },
            { field: 'dataSaidaFormatada', header: 'Data Saída' },
            { field: 'ativo', header: 'Ativo' }
        ];

        this.exportColumns = this.cols.map(col => ({title: col.header, dataKey: col.field}));

        this.loading = true;
    }

    loadFuncionarios(event: LazyLoadEvent) {        
        this.loading = true;

        let nome: string = "";
        let page: number = 0;

        page = event.first / event.rows;
        
        if(event.sortField === undefined){
            event.sortField = 'id';
        }

        if (event.filters['nome'] !== undefined){
            nome = event.filters['nome'].value;
        }

        this.funcionarioService.findAllPaginated(nome,
            page, event.rows, event.sortField,
            event.sortOrder === 1 ? 'asc' : 'desc'
        ).then((data) => {
            this.listaFuncionario = data['content'];
            this.totalRecords = data['totalElements'];
            this.loading = false;
        });

    }        

    onSelectionChange(value = []) {
        this.selectAll = value.length === this.totalRecords;
        this.selectedFuncionario = value;
    }

    onSelectAllChange(event: any) {
        const checked = event.checked;

        if (checked) {
            this.funcionarioService.findAll().then((res) => {
                this.selectedFuncionario = res;
                this.selectAll = true;
            });
        } else {
            this.selectedFuncionario = [];
            this.selectAll = false;
        }
    }

    mostrarListar() {
        if (this.funcionarioDialog)
            return {display:'none'};
        else
            return {display:''};
    }

    mostrarEditar() {
        if (this.funcionarioDialog)
            return {display:''};
        else
            return {display:'none'};
    }
    
    onClean() {
        this.funcionario = cleanFuncionario;
    }

    onSave() {
        this.submitted = true;
        this.funcionario.cpf = this.baseUtilService.cpfFormatadoParaCpf(this.funcionario.cpfFormatado);
        this.funcionario.dataAdmissao = this.baseUtilService.dataStringToDate(this.funcionario.dataAdmissaoFormatada);
        this.funcionario.dataSaida = this.baseUtilService.dataStringToDate(this.funcionario.dataSaidaFormatada);

        if (this.funcionario.nome.trim()) {
            if (this.funcionario.id) {
                this.funcionarioService.update(this.funcionario).then((obj: Funcionario) => {
                this.funcionario = obj;

                this.listaFuncionario[
                    this.funcionarioService.findIndexById(this.listaFuncionario, this.funcionario.id)] = this.funcionario;
                this.messageService.add({ severity: 'success', summary: 'Sucesso', detail: 'Funcionário Atualizado', life: 3000 });
                });
            } else {
                this.funcionarioService.insert(this.funcionario).then((obj: Funcionario) => {
                this.funcionario = obj;

                this.listaFuncionario.push(this.funcionario);
                this.messageService.add({ severity: 'success', summary: 'Sucesso', detail: 'Funcionário Criado', life: 3000 });
                });
            }

            this.listaFuncionario = [...this.listaFuncionario];
            this.funcionarioDialog = false;
            this.funcionario = {};
        }
    }

    onChangedTypeReport(typeReport: ItypeReport) {
        this.reportParamForm.reportType = typeReport.type;
    }

    onChangedForceDownload(forceDownload: boolean) {
        this.reportParamForm.forceDownload = forceDownload;
    }

    onExport() {
        this.funcionarioService.report(this.reportParamForm).then(() => {
            this.messageService.add({severity: 'info', summary: 'Funcionário Exportado', detail: 'Funcionário Exportado', life: 1000});
        });
    }

    onInsert() {
        this.funcionario = {};
        this.submitted = false;
        this.funcionarioDialog = true;
    }

    onEdit(funcionario: Funcionario) {
        this.funcionario = { ...funcionario };
        this.funcionarioDialog = true;
    }
    
    hideDialog() {
        this.funcionarioDialog = false;
        this.submitted = false;
    }

    deleteSelected() {
        this.deleteFuncionariosDialog = true;
    }

    onDelete(funcionario: Funcionario) {
        this.deleteFuncionarioDialog = true;
        this.funcionario = { ...funcionario };
    }

    confirmDeleteSelected() {    
        this.deleteFuncionariosDialog = false;
        this.listaFuncionario = this.listaFuncionario.filter(val => !this.selectedFuncionario.includes(val));

        let excluiu = false;
        this.selectedFuncionario.forEach((item) => {
            this.funcionarioService.delete(item.id).then(obj => {
                excluiu = true;
            });
        });

        if (excluiu) {
            this.messageService.add({ severity: 'success', summary: 'Sucesso', detail: 'Funcionários excluídos', life: 3000 });
            this.selectedFuncionario = [];  
        }
    }

    confirmDelete() {
        this.deleteFuncionarioDialog = false;
        this.funcionarioService.delete(this.funcionario.id).then(obj => {
          this.listaFuncionario = this.listaFuncionario.filter(val => val.id !== this.funcionario.id);
          this.funcionario = {};        
          this.messageService.add({ severity: 'success', summary: 'Sucesso', detail: 'Página excluída', life: 3000 });
        });
    }
          
    exportPdf() {
        const head: string[] = [];
        const data: any[] = [];

        this.exportColumns.forEach(item => head.push(item.title));
        this.listaFuncionario.forEach(item => data.push(
            [item.id, item.nome, item.cpfFormatado, item.email, item.telefone, item.celular, 
            item.setor, item.codCargo, item.cargo, item.dataAdmissaoFormatada, item.dataSaidaFormatada, item.ativo]
        ));

        this.exportService.exportPdf(head, data, 'funcionarios.pdf');
    }
    
    exportExcel() {
        this.exportService.exportExcel(this.listaFuncionario, 'funcionarios');
    }    
    

}

<div class="grid">
    <div class="col-12">
        <div class="card px-6 py-6" [style]="mostrarListar()">
            <p-toast></p-toast>
            <p-toolbar styleClass="mb-4">
                <ng-template pTemplate="left">
                    <div class="my-2">
                        <button pButton pRipple label="Adicionar" icon="pi pi-plus" class="p-button-success mr-2" (click)="onInsert()"></button>
                        <button pButton pRipple label="Excluir" icon="pi pi-trash" class="p-button-danger" (click)="deleteSelected()" 
                        [disabled]="!selectedFuncionario || !selectedFuncionario.length"></button>
                    </div>
                </ng-template>
            </p-toolbar>

            <p-table #dt [value]="listaFuncionario" [columns]="cols" responsiveLayout="scroll" [rows]="10" 
                [globalFilterFields]="['nome']" paginatorPosition="top"
                [paginator]="true" [rowsPerPageOptions]="[10,20,30,100,200,500]" [showCurrentPageReport]="true" 
                currentPageReportTemplate="Mostrando {first} até {last} de {totalRecords} entradas" 
                [(selection)]="selectedFuncionario" selectionMode="multiple" [rowHover]="true" dataKey="id"                
                (selectionChange)="onSelectionChange($event)" [selectAll]="selectAll" (selectAllChange)="onSelectAllChange($event)"                
                [lazy]="true" (onLazyLoad)="loadFuncionarios($event)" [loading]="loading" [totalRecords]="totalRecords">
                <ng-template pTemplate="caption">
                    <div class="flex flex-column md:flex-row md:justify-content-between md:align-items-center">
                        <h5 class="m-0">Funcionários</h5>

                        <div class="flex">
                            <button type="button" pButton pRipple icon="pi pi-file" (click)="dt.exportCSV()" class="mr-2" pTooltip="CSV" tooltipPosition="bottom"></button>
                            <button type="button" pButton pRipple icon="pi pi-file-excel" (click)="exportExcel()" class="p-button-success mr-2" pTooltip="XLS" tooltipPosition="bottom"></button>
                            <button type="button" pButton pRipple icon="pi pi-file-pdf" (click)="exportPdf()" class="p-button-warning mr-2" pTooltip="PDF" tooltipPosition="bottom"></button>
                            <button type="button" pButton pRipple icon="pi pi-filter" (click)="dt.exportCSV({ selectionOnly: true })" class="p-button-info mr-2" pTooltip="Somente Seleção" tooltipPosition="bottom"></button>
                        </div>                        

                    </div>
                </ng-template>
                <ng-template pTemplate="header">
                    <tr>
                        <th style="width: 3rem">
                        </th>                        
                        <th></th>
                        <th pSortableColumn="id">Id <p-sortIcon field="id"></p-sortIcon></th>
                        <th pSortableColumn="nome">Nome <p-sortIcon field="nome"></p-sortIcon></th>
                        <th pSortableColumn="cpf">Cpf <p-sortIcon field="cpfFormatado"></p-sortIcon></th>
                        <th pSortableColumn="email">Email <p-sortIcon field="email"></p-sortIcon></th>
                        <th pSortableColumn="telefone">Telefone <p-sortIcon field="telefone"></p-sortIcon></th>
                        <th pSortableColumn="celular">Celular <p-sortIcon field="celular"></p-sortIcon></th>
                        <th pSortableColumn="setor">Setor <p-sortIcon field="setor"></p-sortIcon></th>
                        <th pSortableColumn="codCargo">CodCargo <p-sortIcon field="codCargo"></p-sortIcon></th>
                        <th pSortableColumn="cargo">Cargo <p-sortIcon field="cargo"></p-sortIcon></th>
                        <th pSortableColumn="dataAdmissao">Data Admissão <p-sortIcon field="dataAdmissaoFormatada"></p-sortIcon></th>
                        <th pSortableColumn="dataSaida">Data Saída <p-sortIcon field="dataSaidaFormatada"></p-sortIcon></th>
                        <th pSortableColumn="ativo">Ativo <p-sortIcon field="ativo"></p-sortIcon></th>                        
                    </tr>
                    <tr>
                        <th style="width: 3rem">
                            <p-tableHeaderCheckbox></p-tableHeaderCheckbox>
                        </th>                        
                        <th></th>
                        <th></th>
                        <th><p-columnFilter type="text" field="nome"></p-columnFilter></th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                    </tr>
                </ng-template>
                <ng-template pTemplate="body" let-funcionario>
                    <tr>
                        <td>
                            <p-tableCheckbox [value]="funcionario"></p-tableCheckbox>
                        </td>
                        <td>
                            <div class="flex">
                                <button pButton pRipple icon="pi pi-pencil" class="p-button-rounded p-button-success mr-2" (click)="onEdit(funcionario)"></button>
                                <button pButton pRipple icon="pi pi-trash" class="p-button-rounded p-button-warning" (click)="onDelete(funcionario)"></button>
                            </div>
                        </td>
                        <td style="width:5%; min-width:5rem;"><span class="p-column-title">Id</span>
                            {{funcionario.id}}
                        </td>
                        <td style="min-width:20rem;">
                            <span class="p-column-title">Nome</span>
                            {{funcionario.nome}}
                        </td>
                        <td style="min-width:10rem;">
                            <span class="p-column-title">Cpf</span>
                            {{funcionario.cpfFormatado}}
                        </td>
                        <td style="width:14%; min-width:10rem;">
                            <span class="p-column-title">Email</span>
                            {{funcionario.email}}
                        </td>
                        <td style="width:14%; min-width:10rem;">
                            <span class="p-column-title">Telefone</span>
                            {{funcionario.telefone}}
                        </td>
                        <td style="width:14%; min-width:10rem;">
                            <span class="p-column-title">Celular</span>
                            {{funcionario.celular}}
                        </td>
                        <td style="width:14%; min-width:10rem;">
                            <span class="p-column-title">Setor</span>
                            {{funcionario.setor}}
                        </td>
                        <td style="width:14%; min-width:10rem;">
                            <span class="p-column-title">CodCargo</span>
                            {{funcionario.codCargo}}
                        </td>
                        <td style="min-width:20rem;">
                            <span class="p-column-title">Cargo</span>
                            {{funcionario.cargo}}
                        </td>
                        <td style="min-width:12rem;">
                            <span class="p-column-title">Data Admissão</span>
                            {{funcionario.dataAdmissaoFormatada}}
                        </td>
                        <td style="width:14%; min-width:10rem;">
                            <span class="p-column-title">Data Saída</span>
                            {{funcionario.dataSaidaFormatada}}
                        </td>
                        <td style="width:14%; min-width:10rem;">
                            <span class="p-column-title">Ativo</span>
                            {{funcionario.ativo}}
                        </td>
                    </tr>
                </ng-template>
            </p-table>
        </div>

        <div [style]="mostrarEditar()">

            <p-panel header="Detalhes do funcionário" styleClass="p-mb-2">
                <p-toast></p-toast>
                <p-toolbar styleClass="mb-4">
                    <ng-template pTemplate="left">
                    </ng-template>
                    <ng-template pTemplate="right">
                        <div class="my-2">
                            <button pButton pRipple label="Cancelar" icon="pi pi-times" class="p-button-secondary mr-2" (click)="hideDialog()"></button>
                            <button pButton pRipple label="Limpar" icon="pi pi-star-o" class="p-button-primary mr-2" (click)="onClean()"></button>
                            <button pButton pRipple label="Salvar" icon="pi pi-check" class="p-button-success" (click)="onSave()"></button>        
                        </div>
                    </ng-template>
                </p-toolbar>
    
                <div class="card p-fluid">
                    <div class="field">
                        <label for="nome">Nome</label>
                        <input type="text" pInputText id="nome" [(ngModel)]="funcionario.nome" required autofocus 
                            [ngClass]="{'ng-invalid ng-dirty' : submitted && !funcionario.nome}" />
                        <small class="ng-dirty ng-invalid" *ngIf="submitted && !funcionario.nome">Nome é obrigatório.</small>
                    </div>
                    <div class="field">
                        <label for="email">Email</label>
                        <input type="text" pInputText id="email" [(ngModel)]="funcionario.email" />
                    </div>
                    <div class="formgrid grid">
                        <div class="field col">
                            <label for="cpf">cpf</label>
                            <p-inputMask mask="999.999.999-99" id="cpf" [(ngModel)]="funcionario.cpfFormatado" required
                                [ngClass]="{'ng-invalid ng-dirty' : submitted && !funcionario.cpfFormatado}"></p-inputMask>
                            <small class="ng-dirty ng-invalid" *ngIf="submitted && !funcionario.cpfFormatado">CPF é obrigatório.</small>    
                        </div>
                        <div class="field col">
                            <label for="telefone">Telefone</label>
                            <input type="text" pInputText id="telefone" [(ngModel)]="funcionario.telefone" />
                        </div>
                    </div>
                    <div class="formgrid grid">
                        <div class="field col">
                            <label for="celular">Celular</label>
                            <input type="text" pInputText id="celular" [(ngModel)]="funcionario.celular" />
                        </div>
                        <div class="field col">
                            <label for="setor">Setor</label>
                            <input type="text" pInputText id="setor" [(ngModel)]="funcionario.setor" />
                        </div>
                    </div>
                    <div class="formgrid grid">
                        <div class="field col">
                            <label for="codCargo">CodCargo</label>
                            <p-inputNumber mode="decimal" [useGrouping]="false" id="codCargo" [(ngModel)]="funcionario.codCargo"></p-inputNumber>
                        </div>
                        <div class="field col">
                            <label for="cargo">Cargo</label>
                            <input type="text" pInputText id="cargo" [(ngModel)]="funcionario.cargo" />
                        </div>
                    </div>
                    <div class="formgrid grid">
                        <div class="field col">
                            <label for="dataAdmissao">Data Admissão</label>
                            <p-calendar id="dataAdmissao" [(ngModel)]="funcionario.dataAdmissaoFormatada" [showIcon]="true" 
                                dateFormat="dd/mm/yy" dataType="string"></p-calendar>
                        </div>
                        <div class="field col">
                            <label for="dataSaida">Data Saída</label>
                            <p-calendar id="dataSaida" [(ngModel)]="funcionario.dataSaidaFormatada" [showIcon]="true" 
                                dateFormat="dd/mm/yy" dataType="string"></p-calendar>
                        </div>
                    </div>    
                    <div class="flex align-items-center gap-1">                        
                        <p-checkbox value="Ativo" inputId="ativo" [binary]="true" [(ngModel)]="funcionario.ativo" />
                        <label for="ativo">Ativo</label>
                    </div>       
                </div>
            </p-panel>              

        </div>
  
        <p-dialog [(visible)]="deleteFuncionarioDialog" header="Confirme" [modal]="true" [style]="{width:'450px'}">
            <div class="flex align-items-center justify-content-center">
                <i class="pi pi-exclamation-triangle mr-3" style="font-size: 2rem"></i>
                <span *ngIf="funcionario">Tem certeza de que deseja excluir <b>{{funcionario.nome}}</b>?</span>
            </div>
            <ng-template pTemplate="footer">
                <button pButton pRipple icon="pi pi-times" class="p-button-text" label="Não" (click)="deleteFuncionarioDialog = false"></button>
                <button pButton pRipple icon="pi pi-check" class="p-button-text" label="Sim" (click)="confirmDelete()"></button>
            </ng-template>
        </p-dialog>

        <p-dialog [(visible)]="deleteFuncionariosDialog" header="Confirme" [modal]="true" [style]="{width:'450px'}">
            <div class="flex align-items-center justify-content-center">
                <i class="pi pi-exclamation-triangle mr-3" style="font-size: 2rem"></i>
                <span>Tem certeza de que deseja excluir os funcionários selecionados?</span>
            </div>
            <ng-template pTemplate="footer">
                <button pButton pRipple icon="pi pi-times" class="p-button-text" label="Não" (click)="deleteFuncionariosDialog = false"></button>
                <button pButton pRipple icon="pi pi-check" class="p-button-text" label="Sim" (click)="confirmDeleteSelected()"></button>
            </ng-template>
        </p-dialog>
    </div>
</div>

// frontend/hfs-frontend-vue/src/hfsfullstack/pages/Funcionario.vue
<script lang="ts">
import { FilterMatchMode } from 'primevue/api';
import { ref, onMounted, onBeforeMount } from 'vue';
import { useToast } from 'primevue/usetoast';
import FuncionarioService from '../service/FuncionarioService';
import { Funcionario, cleanFuncionario, emptyFuncionario } from '../api/funcionario';
import { ReportParamForm, emptyReportParamForm } from '../../base/models/ReportParamsForm';
import { ItypeReport, PDFReport, SelectItemGroup } from '../../base/services/ReportService';
import { LazyTableParam, emptyLazyTableParam } from '../../base/models/LazyTableParam';
import { first } from 'rxjs';
import { ExportService } from '../../base/services/ExportService';
import { BaseUtilService } from '../../base/util/BaseUtilService';

export default {
    setup() {
        const toast = useToast();

        const listaFuncionario = ref();
        const funcionarioDialog = ref(false);
        const deleteFuncionarioDialog = ref(false);
        const deleteFuncionariosDialog = ref(false);
        const funcionario = ref(emptyFuncionario);
        const selectedFuncionarios = ref<Funcionario[]>([]);
        const dt = ref(null);
        const first = ref(0);
        const filters = ref({});
        const cols = ref();
        const exportColumns = ref([]);
        const submitted = ref(false);

        const funcionarioService = new FuncionarioService();
        const exportService = new ExportService();
        const baseUtilService = new BaseUtilService();

        const selectedTypeReport = ref<ItypeReport>();
        const selectedForceDownload = ref(true);
        const reportParamForm = ref<ReportParamForm>(emptyReportParamForm);

        const rowsPerPageOptions = ref<number[]>([5, 10, 30, 50, 100, 150, 200]);

        const totalRecords = ref<number>(0);

        const loading = ref<boolean>(false);

        const selectAll = ref<boolean>(false);

        const lazyFilters = ref({
            'nome': {value: '', matchMode: 'contains'},
        });

        const lazyParams = ref<LazyTableParam>({
            first: 0,
            rows: 10,
            sortField: 'nome',
            sortOrder: 1,
            filters: {
                'nome': { value: '', matchMode: 'contains' },
            }
        });

        onBeforeMount(() => {
            initFilters();
        });

        onMounted(() => {
            selectedTypeReport.value = PDFReport.value;

            cols.value = [
                { field: 'id', header: 'Código' },
                { field: 'nome', header: 'Nome' },
                { field: 'cpfFormatado', header: 'Cpf' },
                { field: 'email', header: 'Email' },
                { field: 'telefone', header: 'Telefone' },
                { field: 'celular', header: 'Celular' },
                { field: 'setor', header: 'Setor' },
                { field: 'codCargo', header: 'CodCargo' },
                { field: 'cargo', header: 'Cargo' },
                { field: 'dataAdmissaoFormatada', header: 'Data Admissão' },
                { field: 'dataSaidaFormatada', header: 'Data Saída' },
                { field: 'ativo', header: 'Ativo' }
            ];
            
            exportColumns.value = cols.value.map((col: { header: any; field: any; }) => ({title: col.header, dataKey: col.field}));

            loadFuncionarios();
        });

        const loadFuncionarios = () => {        
            loading.value = true;

            funcionarioService.findAllPaginated(lazyParams.value).then((data) => {
                listaFuncionario.value = data['content'];
                totalRecords.value = data['totalElements'];
                loading.value = false;
            });

        }        

        const onPage = (event) => {
            lazyParams.value = event;
            loadFuncionarios(event);
        };

        const onSort = (event) => {
            lazyParams.value = event;
            loadFuncionarios(event);
        };

        const onFilter = (event: any) => {
            lazyParams.value.filters = lazyFilters.value ;
            loadFuncionarios(event);
        };

        const onRowSelect = () => {
            selectAll.value = selectedFuncionarios.value.length === totalRecords.value;
        };

        const onRowUnselect = () => {
            selectAll.value = false;
        };        

        const onSelectAllChange = (event) => {
            selectAll.value = event.checked;

            if (selectAll) {
                funcionarioService.findAll().then((res) => {
                    selectedFuncionarios.value = res;
                    selectAll.value = true;
                });
            } else {
                selectedFuncionarios.value = [];
                selectAll.value = false;
            }
        }

        const mostrarListar = () => {
            if (funcionarioDialog.value)
                return { display: 'none' };
            else
                return { display: '' };
        }

        const mostrarEditar = () => {
            if (funcionarioDialog.value)
                return { display: '' };
            else
                return { display: 'none' };
        }

        const onInsert = () => {
            funcionario.value = emptyFuncionario;
            submitted.value = false;
            funcionarioDialog.value = true;
        };

        const onEdit = (param: Funcionario) => {
            funcionario.value = { ...param };
            funcionarioDialog.value = true;
        };

        const hideDialog = () => {
            funcionarioDialog.value = false;
            submitted.value = false;
        };

        const onClean = () => {
            funcionario.value = cleanFuncionario;
        }

        const onSave = () => {
            submitted.value = true;
            if (funcionario.value.description && funcionario.value.description.trim()) {
                if (funcionario.value.id) {
                    funcionarioService.update(funcionario.value).then((obj: Funcionario) => {
                        funcionario.value = obj;

                        const index = funcionarioService.findIndexById(listaFuncionario.value, funcionario.value.id);
                        listaFuncionario.value[index] = funcionario.value;
                        toast.add({severity:'success', summary: 'Successful', detail: 'Funcionário Atualizado', life: 3000});
                    });            
                } else {
                    funcionarioService.insert(funcionario.value).then((obj: Funcionario) => {
                        funcionario.value = obj;

                        listaFuncionario.value.push(funcionario.value);
                        toast.add({ severity: 'success', summary: 'Successful', detail: 'Funcionário Criado', life: 3000 });
                    });            
                }

                funcionarioDialog.value = false;
                funcionario.value = emptyFuncionario;
            }
        };

        const deleteSelected = () => {
            deleteFuncionariosDialog.value = true;
        }

        const onDelete = (param: Funcionario) => {
            deleteFuncionarioDialog.value = true;
            funcionario.value = { ...param };
        } 

        const confirmDeleteSelected = () => {
            deleteFuncionariosDialog.value = false;
            listaFuncionario.value = listaFuncionario.value.filter((val: Funcionario) => !selectedFuncionarios.value.includes(val));

            let excluiu = false;
            selectedFuncionarios.value.forEach((item: Funcionario) => {
                funcionarioService.delete(item.id).then(obj => {
                    excluiu = true;
                });
            });

            if (excluiu) {
                toast.add({ severity: 'success', summary: 'Sucesso', detail: 'Funcionários excluídos', life: 3000 });
                selectedFuncionarios.value = [];
            }
        }

        const confirmDelete = () => {
            deleteFuncionarioDialog.value = false;
            funcionarioService.delete(funcionario.value.id).then(obj => {
                listaFuncionario.value = listaFuncionario.value.filter((val: Funcionario) => val.id !== funcionario.value.id);
                funcionario.value = emptyFuncionario;        
                toast.add({ severity: 'success', summary: 'Sucesso', detail: 'Funcionário excluído', life: 3000 });
            });
        }

        const onTypeReportChange = (param: { pTypeReport: SelectItemGroup }) => {
            if (param.pTypeReport.value){
                selectedTypeReport.value = param.pTypeReport.value;
                reportParamForm.value = { reportType: param.pTypeReport.value.type, forceDownload: selectedForceDownload.value };
            }        
        }

        const onForceDownloadChange = (param: { forceDownload: boolean }) => {
            selectedForceDownload.value = param.forceDownload;
            if (selectedTypeReport.value){
                reportParamForm.value = { reportType: selectedTypeReport.value.type, forceDownload: param.forceDownload };
            }
        }

        const onExport = () => {
            funcionarioService.report(reportParamForm.value).then(() => {
                toast.add({ severity: 'info', summary: 'Funcionário exportado', 
                    detail: 'Funcionário exportada', life: 3000 });
            });
        }

        const initFilters = () => {
            filters.value = {
                global: { value: null, matchMode: FilterMatchMode.CONTAINS }
            };
        };

        const exportCSV = (selectionOnly: any) => {
            dt.value.exportCSV(selectionOnly);
        };

        const exportPdf = () => {
            const head: string[] = [];
            const data: any[] = [];

            exportColumns.value.forEach(item => head.push(item.title));
            listaFuncionario.value.forEach(item => data.push(
                [item.id, item.nome, item.cpfFormatado, item.email, item.telefone, item.celular, 
                item.setor, item.codCargo, item.cargo, item.dataAdmissaoFormatada, item.dataSaidaFormatada, item.ativo]
            ));

            exportService.exportPdf(head, data, 'funcionarios.pdf');
        }
        
        const exportExcel = () => {
            exportService.exportExcel(listaFuncionario.value, 'funcionarios');
        }    

        return { listaFuncionario, funcionario, filters, submitted, onClean, exportPdf, exportExcel, exportCSV,
            selectedFuncionarios, deleteSelected, funcionarioDialog, hideDialog, mostrarListar, mostrarEditar,
            deleteFuncionarioDialog, confirmDelete, deleteFuncionariosDialog,
            onInsert, onEdit, onDelete, onSave, onExport, onTypeReportChange, onForceDownloadChange, confirmDeleteSelected,
            first, totalRecords, loading, onPage, onSort, onFilter, selectAll, onSelectAllChange, onRowSelect, onRowUnselect }
    }
}        
</script>

<template>
    <div class="grid">
        <div class="col-12">
            <div class="card px-6 py-6" :style="mostrarListar()">
                <!-- <Toast /> -->
                <Panel header="Funcionário" class="p-mb-2">
                    <ReportPanel @changeTypeReport="onTypeReportChange" @changeForceDownload="onForceDownloadChange"></ReportPanel>
                </Panel>                
                <Toolbar class="mb-4">
                    <template v-slot:start>
                        <div class="my-2">
                            <Button label="Adicionar" icon="pi pi-plus" class="p-button-success mr-2" @click="onInsert" />
                            <Button label="Excluir" icon="pi pi-trash" class="p-button-danger" @click="deleteSelected" 
                                :disabled="!selectedFuncionarios || !selectedFuncionarios.length" />
                        </div>
                    </template>

                    <template v-slot:end>
                        <Button label="Exportar" icon="pi pi-upload" class="p-button-help" @click="onExport" />
                    </template>
                </Toolbar>

                <DataTable
                    ref="dt" paginatorPosition="both" lazy
                    :value="listaFuncionario"
                    v-model:selection="selectedFuncionarios"
                    dataKey="id"
                    :paginator="true"
                    :rows="10"
                    v-model:filters="filters"
                    paginatorTemplate="FirstPageLink PrevPageLink PageLinks NextPageLink LastPageLink CurrentPageReport RowsPerPageDropdown"
                    :rowsPerPageOptions="[10,30,50,100,150,200]" emptyMessage="Nenhum registro encontrado."
                    currentPageReportTemplate="Mostrando {first} até {last} de {totalRecords} entradas"
                    responsiveLayout="scroll" :globalFilterFields="['nome']"
                    :first="first" :totalRecords="totalRecords" :loading="loading" 
                    @page="onPage($event)" @sort="onSort($event)" @filter="onFilter($event)" filterDisplay="row"
                    :selectAll="selectAll" @select-all-change="onSelectAllChange" @row-select="onRowSelect" @row-unselect="onRowUnselect" 
                    tableStyle="min-width: 75rem"
                >
                    <template #header>
                        <div class="flex flex-column md:flex-row md:justify-content-between md:align-items-center">
                            <h5 class="m-0">Funcionários</h5>
                            <span class="block mt-2 md:mt-0 p-input-icon-left">
                                <i class="pi pi-search" />
                                <InputText v-model="filters['global'].value" placeholder="Procurar..." />
                            </span>

                            <div class="flex">
                                <Button icon="pi pi-file" @click="exportCSV($event)" class="mr-2" v-tooltip.bottom="'CSV'" />
                                <Button icon="pi pi-file-excel" @click="exportExcel" class="p-button-success mr-2" v-tooltip.bottom="'XLS'" />
                                <Button icon="pi pi-file-pdf" @click="exportPdf" class="p-button-warning mr-2" v-tooltip.bottom="'PDF'" />
                                <Button icon="pi pi-filter" @click="exportCSV({ selectionOnly: true })" class="p-button-info mr-2" v-tooltip.bottom="'Somente Seleção'" />
                            </div>

                        </div>
                    </template>

                    <Column selectionMode="multiple" headerStyle="width: 3rem"></Column>
                    <Column headerStyle="min-width:10rem;">
                        <template #body="slotProps">
                            <Button icon="pi pi-pencil" class="p-button-rounded p-button-success mr-2" @click="onEdit(slotProps.data)" />
                            <Button icon="pi pi-trash" class="p-button-rounded p-button-warning mt-2" @click="onDelete(slotProps.data)" />
                        </template>
                    </Column>
                    <Column field="id" header="Id" :sortable="true" headerStyle="width:14%; min-width:10rem;">
                        <template #body="slotProps">
                            <span class="p-column-title">Id</span>
                            {{ slotProps.data.id }}
                        </template>
                    </Column>
                    <Column field="nome" header="Nome" :sortable="true" headerStyle="min-width:20rem;">
                        <template #body="slotProps">
                            <span class="p-column-title">Nome</span>
                            {{ slotProps.data.nome }}
                        </template>
                    </Column>
                    <Column field="cpfFormatado" header="Cpf" :sortable="true" headerStyle="min-width:10rem;">
                        <template #body="slotProps">
                            <span class="p-column-title">Cpf</span>
                            {{ slotProps.data.cpfFormatado }}
                        </template>
                    </Column>
                    <Column field="email" header="Email" :sortable="true" headerStyle="width:14%; min-width:10rem;">
                        <template #body="slotProps">
                            <span class="p-column-title">Email</span>
                            {{ slotProps.data.email }}
                        </template>
                    </Column>
                    <Column field="telefone" header="Telefone" :sortable="true" headerStyle="width:14%; min-width:10rem;">
                        <template #body="slotProps">
                            <span class="p-column-title">Telefone</span>
                            {{ slotProps.data.telefone }}
                        </template>
                    </Column>
                    <Column field="celular" header="Celular" :sortable="true" headerStyle="width:14%; min-width:10rem;">
                        <template #body="slotProps">
                            <span class="p-column-title">Celular</span>
                            {{ slotProps.data.celular }}
                        </template>
                    </Column>
                    <Column field="setor" header="Setor" :sortable="true" headerStyle="width:14%; min-width:10rem;">
                        <template #body="slotProps">
                            <span class="p-column-title">Setor</span>
                            {{ slotProps.data.setor }}
                        </template>
                    </Column>
                    <Column field="codCargo" header="CodCargo" :sortable="true" headerStyle="width:14%; min-width:10rem;">
                        <template #body="slotProps">
                            <span class="p-column-title">CodCargo</span>
                            {{ slotProps.data.codCargo }}
                        </template>
                    </Column>
                    <Column field="cargo" header="Cargo" :sortable="true" headerStyle="min-width:20rem;">
                        <template #body="slotProps">
                            <span class="p-column-title">Cargo</span>
                            {{ slotProps.data.cargo }}
                        </template>
                    </Column>
                    <Column field="dataAdmissaoFormatada" header="Data Admissão" :sortable="true" headerStyle="min-width:12rem;">
                        <template #body="slotProps">
                            <span class="p-column-title">Data Admissão</span>
                            {{ slotProps.data.dataAdmissaoFormatada }}
                        </template>
                    </Column>
                    <Column field="dataSaidaFormatada" header="Data Saída" :sortable="true" headerStyle="width:14%; min-width:10rem;">
                        <template #body="slotProps">
                            <span class="p-column-title">Data Saída</span>
                            {{ slotProps.data.dataSaidaFormatada }}
                        </template>
                    </Column>
                    <Column field="ativo" header="Ativo" :sortable="true" headerStyle="width:14%; min-width:10rem;">
                        <template #body="slotProps">
                            <span class="p-column-title">Ativo</span>
                            {{ slotProps.data.ativo }}
                        </template>
                    </Column>

                    <template #footer>
                        <div class="p-d-flex p-ai-center p-jc-between">
                            No total existem {{listaFuncionario ? listaFuncionario.length : 0 }} funcionários.
                        </div>
                    </template>                    
                </DataTable>
            </div>

            <div :style="mostrarEditar()">
                <!-- <Toast /> -->
                <Panel header="Detalhes da página" class="p-mb-2">
                    <Toolbar class="mb-4">
                        <template v-slot:start>
                        </template>
                        <template v-slot:end>
                            <div class="my-2">
                                <Button label="Cancelar" icon="pi pi-times" class="p-button-secondary mr-2" @click="hideDialog"></button>
                                <Button label="Limpar" icon="pi pi-star-o" class="p-button-primary mr-2" @click="onClean"></button>
                                <Button label="Salvar" icon="pi pi-check" class="p-button-success" @click="onSave"></button>        
                            </div>
                        </template>
                    </Toolbar>         
                    <div class="card p-fluid">
                        <div class="field">
                            <label for="nome">Nome</label>
                            <InputText id="nome" v-model="funcionario.nome" autofocus required="true"
                                :class="{ 'p-invalid': submitted && !funcionario.nome }" />
                            <small class="p-invalid" v-if="submitted && !funcionario.nome">O Nome é obrigatório.</small>
                        </div>
                        <div class="field">
                            <label for="email">Email</label>
                            <InputText id="email" v-model="funcionario.email" />
                        </div>
                        <div class="formgrid grid">
                            <div class="field col">
                                <label for="cpf">Cpf</label>
                                <InputMask mask="999.999.999-99" id="cpf" v-model="funcionario.cpfFormatado" required="true"
                                    :class="{ 'p-invalid': submitted && !funcionario.cpf }" />
                                <small class="p-invalid" v-if="submitted && !funcionario.cpf">O Cpf é obrigatório.</small>
                            </div>
                            <div class="field col">
                                <label for="telefone">Telefone</label>
                                <InputText id="telefone" v-model="funcionario.telefone" />
                            </div>
                        </div>
                        <div class="formgrid grid">
                            <div class="field col">
                                <label for="celular">Celular</label>
                                <InputText id="celular" v-model="funcionario.celular" />
                            </div>
                            <div class="field col">
                                <label for="setor">Setor</label>
                                <InputText id="setor" v-model="funcionario.setor" />
                            </div>
                        </div>
                        <div class="formgrid grid">
                            <div class="field col">
                                <label for="codCargo">CodCargo</label>
                                <InputNumber id="codCargo" v-model="funcionario.codCargo" integeronly locale="pt-BR" />
                            </div>
                            <div class="field col">
                                <label for="cargo">Cargo</label>
                                <InputText id="cargo" v-model="funcionario.cargo" />
                            </div>                        
                        </div>
                        <div class="formgrid grid">
                            <div class="field col">
                                <label for="dataAdmissao">Data Admissão</label>
                                <Calendar id="dataAdmissao" v-model="funcionario.dataAdmissaoFormatada" showIcon :showOnFocus="false" 
                                   dateFormat="dd/mm/yy" modelValue="string" />
                            </div>
                            <div class="field col">
                                <label for="dataSaida">Data Saída</label>
                                <Calendar id="dataSaida" v-model="funcionario.dataSaidaFormatada" showIcon :showOnFocus="false" 
                                   dateFormat="dd/mm/yy" modelValue="string" />
                            </div>
                        </div>    
                        <div class="flex align-items-center gap-1">
                            <Checkbox v-model="funcionario.ativo" inputId="ativo" name="ativo" value="Ativo" :binary="true" />
                            <label for="ativo">Ativo</label>                            
                        </div>                    
                    </div>
                </Panel>
            </div>  

            <Dialog v-model:visible="deleteFuncionarioDialog" :style="{ width: '450px' }" header="Confirme" :modal="true">
                <div class="flex align-items-center justify-content-center">
                    <i class="pi pi-exclamation-triangle mr-3" style="font-size: 2rem" />
                    <span v-if="funcionario">Tem certeza de que deseja excluir <b>{{ funcionario.nome }}</b>?</span>
                </div>
                <template #footer>
                    <Button label="Não" icon="pi pi-times" class="p-button-text" @click="deleteFuncionarioDialog = false" />
                    <Button label="Sim" icon="pi pi-check" class="p-button-text" @click="confirmDelete" />
                </template>
            </Dialog>

            <Dialog v-model:visible="deleteFuncionariosDialog" :style="{ width: '450px' }" header="Confirme" :modal="true">
                <div class="flex align-items-center justify-content-center">
                    <i class="pi pi-exclamation-triangle mr-3" style="font-size: 2rem" />
                    <span v-if="funcionario">Tem certeza de que deseja excluir as categorias de parâmetros selecionadas?</span>
                </div>
                <template #footer>
                    <Button label="Não" icon="pi pi-times" class="p-button-text" @click="deleteFuncionariosDialog = false" />
                    <Button label="Sim" icon="pi pi-check" class="p-button-text" @click="confirmDeleteSelected" />
                </template>
            </Dialog>

        </div>
    </div>
</template>
