// frontend/hfs-frontend-material/src/app/system/usuario/usuario.component.ts
import { Component, OnInit } from '@angular/core';
import { UserAuthenticated } from 'src/app/base/models/user-authenticated.interface';
import { AuthService } from 'src/app/base/services/auth.service';

@Component({
    templateUrl: './usuario.component.html'
})
export class UsuarioComponent implements OnInit {

    public userAuthenticated: UserAuthenticated | null = null;

    constructor(private authService: AuthService) { }

    public ngOnInit() {
        this.authService.getUser().subscribe(user => this.userAuthenticated = user);
    }
}

<div class="grid">
    <div class="col-12">
        <div class="card px-6 py-6">
            <mat-card>
                <mat-card-header>
                    <mat-card-title>Usuário logado</mat-card-title>
                </mat-card-header>
                <mat-card-content>
                    <br>
                    <b>ID: </b>
                    {{userAuthenticated.id}}
                    <br><br>
                    <b>Login: </b>
                    {{userAuthenticated.userName}}
                    <br><br>
                    <b>E-mail: </b>
                    {{userAuthenticated.email}}
                    <br><br>
                    <b>E-mail verificado: </b>
                    {{userAuthenticated.emailVerified ? 'Sim' : 'Não'}}
                    <br><br>
                    <b>Nome: </b>
                    {{userAuthenticated.fullName}}
                    <br><br>
                    <b>É administrador: </b>
                    {{userAuthenticated.isAdmin ? 'Sim' : 'Não'}}
                    <br><br>
                    <b>Papéis: </b>
                    <li *ngFor="let role of this.userAuthenticated.roles">
                        {{role}}
                    </li>
                    <br><br>
                </mat-card-content>
            </mat-card>       
        </div>
    </div>
</div>

// frontend/hfs-frontend-react-next/app/(main)/system/usuario/page.tsx
'use client';
import { Card } from 'primereact/card';
import React, { useEffect, useState } from 'react';
import { UserAuthenticated, emptyUserAuthenticated } from '../../base/models/UserAuthenticated';
import { SessionStorageService } from '../../base/services/SessionStorageService';

const UsuarioPage = () => {

    const sessionStorageService = new SessionStorageService();
    
    const [userAuthenticated, setUserAuthenticated] = useState<UserAuthenticated>(emptyUserAuthenticated);
    const [listaRoles, setListaRoles] = useState<[]>([]);

    useEffect(() => {
        setUserAuthenticated(sessionStorageService.getPersistedObj('userAuthenticated') as UserAuthenticated);
        
        let lista: [] = [];
        userAuthenticated.roles.forEach((role, index) => {
            lista.push(<li key={index}>{role}</li>);
        });     
        
        setListaRoles(lista);
        
    }, []);

    return (
        <div className="grid">
            <div className="col-12">
                <div className="card px-6 py-6">
                    <Card title="Usuário logado">
                        <p className="m-0">
                            <b>ID: </b>
                            {userAuthenticated.id}
                            <br></br>
                            <br></br>
                            <b>Login: </b>
                            {userAuthenticated.userName}
                            <br></br>
                            <br></br>
                            <b>E-mail: </b>
                            {userAuthenticated.email}
                            <br></br>
                            <br></br>
                            <b>E-mail verificado: </b>
                            {userAuthenticated.emailVerified ? 'Sim' : 'Não'}
                            <br></br>
                            <br></br>
                            <b>Nome: </b>
                            {userAuthenticated.fullName}
                            <br></br>
                            <br></br>
                            <b>É administrador: </b>
                            {userAuthenticated.isAdmin ? 'Sim' : 'Não'}
                            <br></br>
                            <br></br>
                            <b>Papéis: </b>
                            {listaRoles}
                            <br></br>
                            <br></br>
                        </p>
                    </Card>       
                </div>
            </div>
        </div>
    );
};

export default UsuarioPage;
