// frontend/hfs-frontend-vue/src/admin/pages/AdmPage.vue
<script lang="ts">
import { FilterMatchMode } from 'primevue/api';
import { ref, onMounted, onBeforeMount } from 'vue';
import { useToast } from 'primevue/usetoast';
import AdmPageService from '../../admin/service/AdmPageService';
import { AdmPage, cleanAdmPage, emptyAdmPage } from '../api/AdmPage';
import { ReportParamForm, emptyReportParamForm } from '../../base/models/ReportParamsForm';
import { ItypeReport, PDFReport, SelectItemGroup } from '../../base/services/ReportService';
import { MenuItem } from '../../base/models/MenuItem';
import { AdmProfile } from '../api/AdmProfile';
import AdmProfileService from '../service/AdmProfileService';

export default {
    setup() {
        const toast = useToast();

        const listaAdmPage = ref<AdmPage[]>([]);
        const admPageDialog = ref(false);
        const deleteAdmPageDialog = ref(false);
        const deleteAdmPagesDialog = ref(false);
        const admPage = ref(emptyAdmPage);
        const selectedAdmPages = ref();
        const dt = ref(null);
        const filters = ref({});
        const cols = ref();
        const exportColumns = ref([]);
        const submitted = ref(false);

        const admPageService = new AdmPageService();
        const admProfileService = new AdmProfileService();
        //const exportService = new ExportService();

        const selectedTypeReport = ref<ItypeReport>();
        const selectedForceDownload = ref(true);
        const reportParamForm = ref<ReportParamForm>(emptyReportParamForm);

        const popupMenu = ref();
        const itemsMenuLinha = ref<MenuItem[]>([]);

        const pageProfiles = ref<AdmProfile[][]>();

        onBeforeMount(() => {
            initFilters();
        });

        onMounted(() => {
            admPageService.findAll().then((data) => (listaAdmPage.value = data));

            selectedTypeReport.value = PDFReport.value;

            itemsMenuLinha.value = [{ label: "Editar" }, { label: "Excluir" }];

            cols.value = [
                { field: 'id', header: 'Id' },
                { field: 'url', header: 'Página' },
                { field: 'description', header: 'Descrição' },
                { field: 'pageProfiles', header: 'Perfil(s) da página' }
            ];

            exportColumns.value = cols.value.map((col: { header: any; field: any; }) => ({title: col.header, dataKey: col.field}));

        });

        const toggleMenu = (event: any, rowData: AdmPage) => {
            itemsMenuLinha.value = [];

            itemsMenuLinha.value.push({
                label: 'Editar',
                command: () => {
                    onEdit(rowData);
                }
            });

            itemsMenuLinha.value.push({
                label: 'Excluir',
                command: () => {
                    onDelete(rowData);
                }
            });
            
            popupMenu.value.toggle(event);
        }

        const loadAdmProfiles = (admPage: AdmPage | null): void => {
            let sourceProfiles: AdmProfile[] = [];
            let targetProfiles: AdmProfile[] = [];

            if (admPage) {
                if (admPage.id == null) {
                    admProfileService.findAll().then(profiles => pageProfiles.value = [profiles, []]);
                } else {
                    admProfileService.findProfilesByPage(admPage).then(item => {
                        targetProfiles = item;

                        admProfileService.findAll().then(profiles => {
                            sourceProfiles = profiles.filter(profile => !item.find(target => target.id === profile.id));
                            pageProfiles.value = [sourceProfiles, targetProfiles];
                        });
                    });                            
                }        
            }
        }

        const mostrarListar = () => {
            if (admPageDialog.value)
                return { display: 'none' };
            else
                return { display: '' };
        }

        const mostrarEditar = () => {
            if (admPageDialog.value)
                return { display: '' };
            else
                return { display: 'none' };
        }

        const onClean = () => {
            admPage.value = cleanAdmPage;
            loadAdmProfiles(null);
        }

        const onInsert = () => {
            admPage.value = emptyAdmPage;
            submitted.value = false;
            admPageDialog.value = true;
            loadAdmProfiles(null);
        };

        const onEdit = (param: AdmPage) => {
            admPage.value = { ...param };
            admPageDialog.value = true;
            loadAdmProfiles(admPage.value);
        };

        const hideDialog = () => {
            admPageDialog.value = false;
            submitted.value = false;
        };

        const onSave = () => {
            submitted.value = true;
            admPage.value.admIdProfiles = [];
            pageProfiles.value?.forEach((value: AdmProfile[]) => {
                let sourceProfiles: AdmProfile[] = value;

                sourceProfiles.forEach((value: AdmProfile) => {
                    let targetProfile: AdmProfile = value;
                    if (targetProfile.id){
                        admPage.value.admIdProfiles.push(targetProfile.id);
                    }                    
                });
            });

            if (admPage.value.description && admPage.value.description.trim()) {
                if (admPage.value.id) {
                    admPageService.update(admPage.value).then((obj: AdmPage) => {
                        admPage.value = obj;

                        if(admPage.value.id){
                            const index = admPageService.findIndexById(listaAdmPage.value, admPage.value.id);
                            listaAdmPage.value[index] = admPage.value;

                            toast.add({severity:'success', summary: 'Successful', detail: 'Página Atualizada', life: 3000});
                        }
                    });            
                } else {
                    admPageService.insert(admPage.value).then((obj: AdmPage) => {
                        admPage.value = obj;

                        listaAdmPage.value.push(admPage.value);
                        toast.add({ severity: 'success', summary: 'Successful', detail: 'Página Criada', life: 3000 });
                    });            
                }

                admPageDialog.value = false;
                admPage.value = emptyAdmPage;
            }
        };

        const deleteSelected = () => {
            deleteAdmPagesDialog.value = true;
        }

        const onDelete = (param: AdmPage) => {
            deleteAdmPageDialog.value = true;
            admPage.value = { ...param };
        } 

        const confirmDeleteSelected = () => {
            deleteAdmPagesDialog.value = false;
            listaAdmPage.value = listaAdmPage.value.filter((val: AdmPage) => !selectedAdmPages.value.includes(val));

            let excluiu = false;
            selectedAdmPages.value.forEach((item: AdmPage) => {
                if (item.id){
                    admPageService.delete(item.id).then(() => {
                        excluiu = true;
                    });
                }
            });

            if (excluiu) {
                toast.add({ severity: 'success', summary: 'Sucesso', detail: 'Páginas excluídas', life: 3000 });
                selectedAdmPages.value = [];
            }
        }

        const confirmDelete = () => {
            deleteAdmPageDialog.value = false;
            if (admPage.value.id){
                admPageService.delete(admPage.value.id).then(() => {
                    listaAdmPage.value = listaAdmPage.value.filter((val: AdmPage) => val.id !== admPage.value.id);
                    admPage.value = emptyAdmPage;        
                    toast.add({ severity: 'success', summary: 'Sucesso', detail: 'Página excluída', life: 3000 });
                });
            }
        }

        const onTypeReportChange = (param: { pTypeReport: SelectItemGroup }) => {
            if (param.pTypeReport.value){
                selectedTypeReport.value = param.pTypeReport.value;
                reportParamForm.value = { reportType: param.pTypeReport.value.type, forceDownload: selectedForceDownload.value };
            }        
        }

        const onForceDownloadChange = (param: { forceDownload: boolean }) => {
            selectedForceDownload.value = param.forceDownload;
            if (selectedTypeReport.value){
                reportParamForm.value = { reportType: selectedTypeReport.value.type, forceDownload: param.forceDownload };
            }
        }

        const onExport = () => {
            admPageService.report(reportParamForm.value).then(() => {
                toast.add({ severity: 'info', summary: 'Página exportada', 
                    detail: 'Página exportada', life: 3000 });
            });
        }

        const initFilters = () => {
            filters.value = {
                global: { value: null, matchMode: FilterMatchMode.CONTAINS }
            };
        };
/*
        const exportPdf = () => {
            const head: string[] = [];
            const data: any[] = [];

            exportColumns.value.forEach((item: { title: string; }) => head.push(item.title));
            listaAdmPage.value.forEach((item: AdmPage) => data.push(
                [item.id, item.url, item.description, item.pageProfiles]
            ));

            exportService.exportPdf(head, data, 'paginas.pdf');
        }

        const exportExcel = () => {
            exportService.exportExcel(listaAdmPage.value, 'paginas');
        }
*/

        return { listaAdmPage, admPage, filters, submitted, itemsMenuLinha, toggleMenu, popupMenu,
            selectedAdmPages, deleteSelected, admPageDialog, hideDialog, mostrarListar, mostrarEditar, onClean,
            deleteAdmPageDialog, confirmDelete, deleteAdmPagesDialog, pageProfiles,
            onInsert, onEdit, onDelete, onSave, onExport, onTypeReportChange, onForceDownloadChange,
            confirmDeleteSelected }
    }
}        
</script>

<template>
    <div class="grid">
        <div class="col-12">
            <div class="card px-6 py-6" :style="mostrarListar()">
                <!-- <Toast /> -->
                <Panel header="Página" class="p-mb-2">
                    <ReportPanel @changeTypeReport="onTypeReportChange" @changeForceDownload="onForceDownloadChange"></ReportPanel>
                </Panel>                
                <Toolbar class="mb-4">
                    <template v-slot:start>
                        <div class="my-2">
                            <Button label="Adicionar" icon="pi pi-plus" class="p-button-success mr-2" @click="onInsert" />
                            <Button label="Excluir" icon="pi pi-trash" class="p-button-danger" @click="deleteSelected" 
                                :disabled="!selectedAdmPages || !selectedAdmPages.length" />
                        </div>
                    </template>

                    <template v-slot:end>
                        <Button label="Exportar" icon="pi pi-upload" class="p-button-help" @click="onExport" />
                    </template>
                </Toolbar>

                <Menu ref="popupMenu" id="popup_menu" :model="itemsMenuLinha" :popup="true" />

                <DataTable
                    ref="dt" paginatorPosition="both"
                    :value="listaAdmPage"
                    v-model:selection="selectedAdmPages"
                    dataKey="id"
                    :paginator="true"
                    :rows="10"
                    :filters="filters"
                    paginatorTemplate="FirstPageLink PrevPageLink PageLinks NextPageLink LastPageLink CurrentPageReport RowsPerPageDropdown"
                    :rowsPerPageOptions="[10,30,50,100,150,200]" emptyMessage="Nenhum registro encontrado."
                    currentPageReportTemplate="Mostrando {first} até {last} de {totalRecords} entradas"
                    responsiveLayout="scroll"
                >
                    <template #header>
                        <div class="flex flex-column md:flex-row md:justify-content-between md:align-items-center">
                            <h5 class="m-0">Gerenciar páginas</h5>
                            <span class="block mt-2 md:mt-0 p-input-icon-left">
                                <i class="pi pi-search" />
                                <InputText v-model="filters['global'].value" placeholder="Procurar..." />
                            </span>
                        </div>
                    </template>

                    <Column selectionMode="multiple" headerStyle="width: 3rem"></Column>
                    <Column field="id" header="Id" :sortable="true" headerStyle="width:5%; min-width:5rem;">
                        <template #body="slotProps">
                            <span class="p-column-title">Id</span>
                            {{ slotProps.data.id }}
                        </template>
                    </Column>
                    <Column field="url" header="Página" :sortable="true" headerStyle="min-width:10rem;">
                        <template #body="slotProps">
                            <span class="p-column-title">Página</span>
                            {{ slotProps.data.url }}
                        </template>
                    </Column>
                    <Column field="description" header="Descrição" :sortable="true" headerStyle="min-width:8rem;">
                        <template #body="slotProps">
                            <span class="p-column-title">Descrição</span>
                            {{ slotProps.data.description }}
                        </template>
                    </Column>
                    <Column field="pageProfiles" header="Perfil(s) da página" :sortable="true" headerStyle="min-width:8rem;">
                        <template #body="slotProps">
                            <span class="p-column-title">Perfil(s) da página</span>
                            {{ slotProps.data.pageProfiles }}
                        </template>
                    </Column>
                    <Column headerStyle="min-width:10rem;">
                        <template #body="slotProps">
                            <div class="flex">
                                <Button link icon="pi pi-ellipsis-v" @click="toggleMenu($event, slotProps.data)" 
                                    aria-haspopup="true" aria-controls="popup_menu" />
                            </div>
                        </template>
                    </Column>

                    <template #footer>
                        <div class="p-d-flex p-ai-center p-jc-between">
                            No total existem {{listaAdmPage ? listaAdmPage.length : 0 }} páginas.
                        </div>
                    </template>

                </DataTable>
            </div>

            <div :style="mostrarEditar()">
                <!-- <Toast /> -->
                <Panel header="Detalhes da página" class="p-mb-2">
                    <Toolbar class="mb-4">
                        <template v-slot:start>
                        </template>
                        <template v-slot:end>
                            <div class="my-2">
                                <Button label="Cancelar" icon="pi pi-times" class="p-button-secondary mr-2" @click="hideDialog"></button>
                                <Button label="Limpar" icon="pi pi-star-o" class="p-button-primary mr-2" @click="onClean"></button>
                                <Button label="Salvar" icon="pi pi-check" class="p-button-success" @click="onSave"></button>        
                            </div>
                        </template>
                    </Toolbar>         
                    <div class="card p-fluid">
                        <div class="field">
                            <label for="url">Página:</label>
                            <InputText id="url" v-model="admPage.url" required="true" :class="{'p-invalid': submitted && !admPage.url}" />
                            <small class="p-invalid" v-if="submitted && !admPage.url">A página é obrigatória.</small>
                        </div>
                        <div class="field">
                            <label for="description">Descrição</label>
                            <InputText id="description" v-model="admPage.description" required="true"
                                :class="{ 'p-invalid': submitted && !admPage.description }" />
                            <small class="p-invalid" v-if="submitted && !admPage.description">A descrição é obrigatória.</small>
                        </div>
                        <div class="field">
                            <label for="pageProfiles">Perfil(s) da página:</label>
                            <PickList v-model="pageProfiles" dataKey="id">
                                <template #sourceheader>Disponível</template>
                                <template #targetheader>Selecionada</template>
                                <template #item="slotProps">
                                    <div>
                                        {{slotProps.item.description}}
                                    </div>
                                </template>
                            </PickList>                                
                        </div>
                    </div>               
                </Panel>                
            </div>

            <Dialog v-model:visible="deleteAdmPageDialog" :style="{ width: '450px' }" header="Confirme" :modal="true">
                <div class="flex align-items-center justify-content-center">
                    <i class="pi pi-exclamation-triangle mr-3" style="font-size: 2rem" />
                    <span v-if="admPage">Tem certeza de que deseja excluir <b>{{ admPage.description }}</b>?</span>
                </div>
                <template #footer>
                    <Button label="Não" icon="pi pi-times" class="p-button-text" @click="deleteAdmPageDialog = false" />
                    <Button label="Sim" icon="pi pi-check" class="p-button-text" @click="confirmDelete" />
                </template>
            </Dialog>

            <Dialog v-model:visible="deleteAdmPagesDialog" :style="{ width: '450px' }" header="Confirme" :modal="true">
                <div class="flex align-items-center justify-content-center">
                    <i class="pi pi-exclamation-triangle mr-3" style="font-size: 2rem" />
                    <span v-if="admPage">Tem certeza de que deseja excluir as categorias de parâmetros selecionadas?</span>
                </div>
                <template #footer>
                    <Button label="Não" icon="pi pi-times" class="p-button-text" @click="deleteAdmPagesDialog = false" />
                    <Button label="Sim" icon="pi pi-check" class="p-button-text" @click="confirmDeleteSelected" />
                </template>
            </Dialog>
        </div>
    </div>
</template>

// frontend/hfs-frontend/src/app/admin/pages/adm-page/adm-page.component.ts
import { Component, OnInit } from '@angular/core';
import { MessageService, MenuItem } from 'primeng/api';
import { ExportService } from 'src/app/base/services/export.service';
import { ReportParamForm } from 'src/app/base/models/ReportParamsForm';
import { ItypeReport } from 'src/app/base/services/ReportService';
import { AdmPageService } from '../../service/AdmPageService';
import { AdmPage, cleanAdmPage, emptyAdmPage } from '../../api/AdmPage';
import { AdmProfile } from '../../api/AdmProfile';
import { AdmProfileService } from '../../service/AdmProfileService';
import { Menu } from 'primeng/menu';
import { Table } from 'primeng/table';

@Component({
  templateUrl: './adm-page.component.html',
  providers: [MessageService, AdmPageService]
})
export class AdmPageComponent implements OnInit {

  admPageDialog: boolean;

  listaAdmPage: AdmPage[] = [];

  admPage: AdmPage = emptyAdmPage;

  selectedAdmPage: AdmPage[] = [];

  submitted: boolean;

  cols: any[];

  exportColumns: any[];

  reportParamForm: ReportParamForm;

  deleteAdmPageDialog: boolean = false;

  deleteAdmPagesDialog: boolean = false;

  itemsMenuLinha: MenuItem[];  

  sourceProfiles: AdmProfile[];
  targetProfiles: AdmProfile[];

  constructor(private messageService: MessageService,
    private admPageService: AdmPageService,
    private admProfileService: AdmProfileService,
    private exportService: ExportService) {
      this.reportParamForm = {
        reportType: 'PDF',
        forceDownload: true
      };

      this.itemsMenuLinha = [{ label: "Editar" }, { label: "Excluir" }];
  }

  toggleMenu(menu: Menu, event: any, rowData: AdmPage) {
    this.itemsMenuLinha = [];

    this.itemsMenuLinha.push({
      label: 'Editar',
      command: (event: any) => {
        this.onEdit(rowData);
      }
    });

    this.itemsMenuLinha.push({
      label: 'Excluir',
      command: (event: any) => {
        this.onDelete(rowData);
      }
    });

    menu.toggle(event);
  }

  ngOnInit(): void {
    this.admPageService
      .findAll()
      .then(data => this.listaAdmPage = data);

    this.cols = [
      { field: 'id', header: 'Id' },
      { field: 'url', header: 'Página' },
      { field: 'description', header: 'Descrição' },
      { field: 'pageProfiles', header: 'Perfil(s) da página' }
    ];

    this.exportColumns = this.cols.map(col => ({title: col.header, dataKey: col.field}));

  }

  private loadAdmProfiles(admPage: AdmPage): void {
    this.targetProfiles = [];

    if (admPage == null) {

      this.admProfileService.findAll().then(profiles => {
        this.sourceProfiles = profiles;
      });

    } else {      
      
      if (this.admPage.id != null) {
        this.admProfileService.findProfilesByPage(admPage).then(data => {
          this.targetProfiles = data;
  
          this.admProfileService.findAll().then(profiles => {
            this.sourceProfiles = profiles.filter(profile => 
              !this.targetProfiles.find(target => target.id === profile.id)
            );
          });
  
        });
      }

    }
  }

  mostrarListar() {
    if (this.admPageDialog)
        return {display:'none'};
    else
        return {display:''};
  }

  mostrarEditar() {
      if (this.admPageDialog)
          return {display:''};
      else
          return {display:'none'};
  }

  onClean() {
    this.admPage = cleanAdmPage;
    this.loadAdmProfiles(null);
  }

  onSave() {
    this.submitted = true;
    this.admPage.admIdProfiles = [];
    this.targetProfiles.forEach(item => {
      this.admPage.admIdProfiles.push(item.id)
    });

    if (this.admPage.description.trim()) {
        if (this.admPage.id) {
          this.admPageService.update(this.admPage).then((obj: AdmPage) => {
            this.admPage = obj;

            this.listaAdmPage[
              this.admPageService.findIndexById(this.listaAdmPage, this.admPage.id)] = this.admPage;
            this.messageService.add({ severity: 'success', summary: 'Sucesso', detail: 'Página Atualizada', life: 3000 });
          });
        } else {
          this.admPageService.insert(this.admPage).then((obj: AdmPage) => {
            this.admPage = obj;

            this.listaAdmPage.push(this.admPage);
            this.messageService.add({ severity: 'success', summary: 'Sucesso', detail: 'Página Criada', life: 3000 });
          });
        }

        this.listaAdmPage = [...this.listaAdmPage];
        this.admPageDialog = false;
        this.admPage = emptyAdmPage;
    }
  }

  onChangedTypeReport(typeReport: ItypeReport) {
    this.reportParamForm.reportType = typeReport.type;
  }

  onChangedForceDownload(forceDownload: boolean) {
    this.reportParamForm.forceDownload = forceDownload;
  }

  onExport() {
    this.admPageService.report(this.reportParamForm).then(() => {
      this.messageService.add({severity: 'info', summary: 'Página Exportada', detail: 'Página Exportada', life: 1000});
    });
  }

  onInsert() {
    this.admPage = emptyAdmPage;
    this.submitted = false;
    this.admPageDialog = true;
    this.loadAdmProfiles(null);
  }

  onEdit(admPage: AdmPage) {
    this.admPage = { ...admPage };
    this.admPageDialog = true;
    this.loadAdmProfiles(admPage);
  }

  hideDialog() {
    this.admPageDialog = false;
    this.submitted = false;
  }

  deleteSelected() {
    this.deleteAdmPagesDialog = true;
  }

  onDelete(admPage: AdmPage) {
    this.deleteAdmPageDialog = true;
    this.admPage = { ...admPage };
  } 

  confirmDeleteSelected() {    
    this.deleteAdmPagesDialog = false;
    this.listaAdmPage = this.listaAdmPage.filter(val => !this.selectedAdmPage.includes(val));

    let excluiu = false;
    this.selectedAdmPage.forEach((item) => {
      this.admPageService.delete(item.id).then(obj => {
        excluiu = true;
      });
    });

    if (excluiu) {
      this.messageService.add({ severity: 'success', summary: 'Sucesso', detail: 'Páginas excluídas', life: 3000 });
      this.selectedAdmPage = [];  
    }
  }

  confirmDelete() {
    this.deleteAdmPageDialog = false;
    this.admPageService.delete(this.admPage.id).then(obj => {
      this.listaAdmPage = this.listaAdmPage.filter(val => val.id !== this.admPage.id);
      this.admPage = emptyAdmPage;        
      this.messageService.add({ severity: 'success', summary: 'Sucesso', detail: 'Página excluída', life: 3000 });
    });
  }

  onGlobalFilter(table: Table, event: Event) {
    table.filterGlobal((event.target as HTMLInputElement).value, 'contains');
  }
  
  exportPdf() {
    const head: string[] = [];
    const data: any[] = [];

    this.exportColumns.forEach(item => head.push(item.title));
    this.listaAdmPage.forEach(item => data.push(
      [item.id, item.url, item.description, item.pageProfiles]
    ));

    this.exportService.exportPdf(head, data, 'paginas.pdf');
  }

  exportExcel() {
    this.exportService.exportExcel(this.listaAdmPage, 'paginas');
  }

}

<div class="grid">
    <div class="col-12">

        <div class="card px-6 py-6" [style]="mostrarListar()">
            <p-toast></p-toast>
            <p-panel header="Página" styleClass="p-mb-2">
                <app-report-panel (typeReportChange)="onChangedTypeReport($event)" (forceDownloadChange)="onChangedForceDownload($event)"></app-report-panel>
            </p-panel>            
            <p-toolbar styleClass="mb-4">
                <ng-template pTemplate="left">
                    <div class="my-2">
                        <button pButton pRipple label="Adicionar" icon="pi pi-plus" class="p-button-success mr-2" (click)="onInsert()"></button>
                        <button pButton pRipple label="Excluir" icon="pi pi-trash" class="p-button-danger" (click)="deleteSelected()" 
                        [disabled]="!selectedAdmPage || !selectedAdmPage.length"></button>
                    </div>
                </ng-template>

                <ng-template pTemplate="right">
                    <button pButton pRipple label="Exportar" icon="pi pi-upload" class="p-button-help" (click)="onExport()"></button>
                </ng-template>
            </p-toolbar>

            <p-menu #popupMenu [model]="itemsMenuLinha" [popup]="true"></p-menu>

            <p-table #dt [value]="listaAdmPage" [columns]="cols" responsiveLayout="scroll" [rows]="10" 
                [globalFilterFields]="['url']" paginatorPosition="both"
                [paginator]="true" [rowsPerPageOptions]="[10,30,50,100,150,200]" [showCurrentPageReport]="true" 
                currentPageReportTemplate="Mostrando {first} até {last} de {totalRecords} entradas" 
                [(selection)]="selectedAdmPage" selectionMode="multiple" [rowHover]="true" dataKey="id">
                <ng-template pTemplate="caption">
                    <div class="flex flex-column md:flex-row md:justify-content-between md:align-items-center">
                        <h5 class="m-0">Gerenciar páginas</h5>
                        <span class="block mt-2 md:mt-0 p-input-icon-left">
                            <i class="pi pi-search"></i>
                            <input pInputText type="text" (input)="onGlobalFilter(dt, $event)" placeholder="Procurar..."  class="w-full sm:w-auto"/>
                        </span>
                    </div>
                </ng-template>
                <ng-template pTemplate="header">
                    <tr>
                        <th style="width: 3rem">
                            <p-tableHeaderCheckbox></p-tableHeaderCheckbox>
                        </th>                        
                        <th pSortableColumn="id">Id <p-sortIcon field="id"></p-sortIcon></th>
                        <th pSortableColumn="url">Página <p-sortIcon field="url"></p-sortIcon></th>
                        <th pSortableColumn="description">Descrição <p-sortIcon field="description"></p-sortIcon></th>
                        <th pSortableColumn="pageProfiles">Perfil(s) da página <p-sortIcon field="pageProfiles"></p-sortIcon></th>
                        <th></th>
                    </tr>
                </ng-template>
                <ng-template pTemplate="body" let-admPage>
                    <tr>
                        <td>
                            <p-tableCheckbox [value]="admPage"></p-tableCheckbox>
                        </td>
                        <td style="width:5%; min-width:5rem;"><span class="p-column-title">Id</span>
                            {{admPage.id}}
                        </td>
                        <td style="min-width:10rem;">
                            <span class="p-column-title">Página</span>
                            {{admPage.url}}
                        </td>
                        <td style="min-width:8rem;">
                            <span class="p-column-title">Descrição</span>
                            {{admPage.description}}
                        </td>
                        <td style="min-width:8rem;">
                            <span class="p-column-title">Perfil(s) da página</span>
                            {{admPage.pageProfiles}}
                        </td>
                        <td style="width: 10px;">
                            <div class="flex">                                
                                <a *ngIf="itemsMenuLinha" (click)="toggleMenu(popupMenu, $event, admPage)" style="cursor: pointer;">
                                    <i class="pi pi-ellipsis-v"></i>
                                </a>
                            </div>
                        </td>
                    </tr>
                </ng-template>
                <ng-template pTemplate="summary">
                    <div class="p-d-flex p-ai-center p-jc-between">
                        No total existem {{listaAdmPage ? listaAdmPage.length : 0 }} páginas.
                    </div>
                </ng-template>
            </p-table>
        </div>        

        <div [style]="mostrarEditar()">

            <p-panel header="Detalhes da página" styleClass="p-mb-2">
                <p-toast></p-toast>
                <p-toolbar styleClass="mb-4">
                    <ng-template pTemplate="left">
                    </ng-template>
                    <ng-template pTemplate="right">
                        <div class="my-2">
                            <button pButton pRipple label="Cancelar" icon="pi pi-times" class="p-button-secondary mr-2" (click)="hideDialog()"></button>
                            <button pButton pRipple label="Limpar" icon="pi pi-star-o" class="p-button-primary mr-2" (click)="onClean()"></button>
                            <button pButton pRipple label="Salvar" icon="pi pi-check" class="p-button-success" (click)="onSave()"></button>        
                        </div>
                    </ng-template>
                </p-toolbar>
    
                <div class="card p-fluid">
                    <div class="field">
                        <label for="url">Página:</label>
                        <input type="text" pInputText id="url" [(ngModel)]="admPage.url" required 
                            [ngClass]="{'ng-invalid ng-dirty' : submitted && !admPage.url}" />
                        <small class="ng-dirty ng-invalid" *ngIf="submitted && !admPage.url">A página é obrigatória.</small>
                    </div>
                    <div class="field">
                        <label for="description">Descrição</label>
                        <input type="text" pInputText id="description" [(ngModel)]="admPage.description" required
                            [ngClass]="{'ng-invalid ng-dirty' : submitted && !admPage.description}" />
                        <small class="ng-dirty ng-invalid" *ngIf="submitted && !admPage.description">A descrição é obrigatória.</small>
                    </div>
                    <div class="field">
                        <label for="pageProfiles">Perfil(s) da página:</label>
            
                        <p-pickList id="pageProfiles" 
                            [source]="sourceProfiles" [target]="targetProfiles" sourceHeader="Disponível" targetHeader="Selecionada" [dragdrop]="true"
                            [responsive]="true" [sourceStyle]="{'height':'30rem'}" [targetStyle]="{'height':'30rem'}" filterBy="description"
                            sourceFilterPlaceholder="Pesquisar por descrição" targetFilterPlaceholder="Pesquisar por descrição">
                            <ng-template let-profile pTemplate="item">
                                <div class="profile-item">
                                    <div>{{profile.description}}</div>
                                </div>
                            </ng-template>
                        </p-pickList>
                    </div>
                </div>
            </p-panel>              

        </div>        

        <p-dialog [(visible)]="deleteAdmPageDialog" header="Confirme" [modal]="true" [style]="{width:'450px'}">
            <div class="flex align-items-center justify-content-center">
                <i class="pi pi-exclamation-triangle mr-3" style="font-size: 2rem"></i>
                <span *ngIf="admPage">Tem certeza de que deseja excluir <b>{{admPage.description}}</b>?</span>
            </div>
            <ng-template pTemplate="footer">
                <button pButton pRipple icon="pi pi-times" class="p-button-text" label="Não" (click)="deleteAdmPageDialog = false"></button>
                <button pButton pRipple icon="pi pi-check" class="p-button-text" label="Sim" (click)="confirmDelete()"></button>
            </ng-template>
        </p-dialog>

        <p-dialog [(visible)]="deleteAdmPagesDialog" header="Confirme" [modal]="true" [style]="{width:'450px'}">
            <div class="flex align-items-center justify-content-center">
                <i class="pi pi-exclamation-triangle mr-3" style="font-size: 2rem"></i>
                <span>Tem certeza de que deseja excluir as páginas selecionados?</span>
            </div>
            <ng-template pTemplate="footer">
                <button pButton pRipple icon="pi pi-times" class="p-button-text" label="Não" (click)="deleteAdmPagesDialog = false"></button>
                <button pButton pRipple icon="pi pi-check" class="p-button-text" label="Sim" (click)="confirmDeleteSelected()"></button>
            </ng-template>
        </p-dialog>

    </div>
</div>
