// frontend/hfs-frontend-vue/src/admin/pages/AdmPage.vue
<script lang="ts">
import { FilterMatchMode } from 'primevue/api';
import { ref, onMounted, onBeforeMount } from 'vue';
import { useToast } from 'primevue/usetoast';
import AdmPageService from '../../admin/service/AdmPageService';
import { AdmPage, cleanAdmPage, emptyAdmPage } from '../api/AdmPage';
import { ReportParamForm, emptyReportParamForm } from '../../base/models/ReportParamsForm';
import { ItypeReport, PDFReport, SelectItemGroup } from '../../base/services/ReportService';
import { MenuItem } from '../../base/models/MenuItem';
import { AdmProfile } from '../api/AdmProfile';
import AdmProfileService from '../service/AdmProfileService';

export default {
    setup() {
        const toast = useToast();

        const listaAdmPage = ref<AdmPage[]>([]);
        const admPageDialog = ref(false);
        const deleteAdmPageDialog = ref(false);
        const deleteAdmPagesDialog = ref(false);
        const admPage = ref(emptyAdmPage);
        const selectedAdmPages = ref();
        const dt = ref(null);
        const filters = ref({});
        const cols = ref();
        const exportColumns = ref([]);
        const submitted = ref(false);

        const admPageService = new AdmPageService();
        const admProfileService = new AdmProfileService();
        //const exportService = new ExportService();

        const selectedTypeReport = ref<ItypeReport>();
        const selectedForceDownload = ref(true);
        const reportParamForm = ref<ReportParamForm>(emptyReportParamForm);

        const popupMenu = ref();
        const itemsMenuLinha = ref<MenuItem[]>([]);

        const pageProfiles = ref<AdmProfile[][]>();

        onBeforeMount(() => {
            initFilters();
        });

        onMounted(() => {
            admPageService.findAll().then((data) => (listaAdmPage.value = data));

            selectedTypeReport.value = PDFReport.value;

            itemsMenuLinha.value = [{ label: "Editar" }, { label: "Excluir" }];

            cols.value = [
                { field: 'id', header: 'Id' },
                { field: 'url', header: 'Página' },
                { field: 'description', header: 'Descrição' },
                { field: 'pageProfiles', header: 'Perfil(s) da página' }
            ];

            exportColumns.value = cols.value.map((col: { header: any; field: any; }) => ({title: col.header, dataKey: col.field}));

        });

        const toggleMenu = (event: any, rowData: AdmPage) => {
            itemsMenuLinha.value = [];

            itemsMenuLinha.value.push({
                label: 'Editar',
                command: () => {
                    onEdit(rowData);
                }
            });

            itemsMenuLinha.value.push({
                label: 'Excluir',
                command: () => {
                    onDelete(rowData);
                }
            });
            
            popupMenu.value.toggle(event);
        }

        const loadAdmProfiles = (admPage: AdmPage | null): void => {
            let sourceProfiles: AdmProfile[] = [];
            let targetProfiles: AdmProfile[] = [];

            if (admPage) {
                if (admPage.id == null) {
                    admProfileService.findAll().then(profiles => pageProfiles.value = [profiles, []]);
                } else {
                    admProfileService.findProfilesByPage(admPage).then(item => {
                        targetProfiles = item;

                        admProfileService.findAll().then(profiles => {
                            sourceProfiles = profiles.filter(profile => !item.find(target => target.id === profile.id));
                            pageProfiles.value = [sourceProfiles, targetProfiles];
                        });
                    });                            
                }        
            }
        }

        const mostrarListar = () => {
            if (admPageDialog.value)
                return { display: 'none' };
            else
                return { display: '' };
        }

        const mostrarEditar = () => {
            if (admPageDialog.value)
                return { display: '' };
            else
                return { display: 'none' };
        }

        const onClean = () => {
            admPage.value = cleanAdmPage;
            loadAdmProfiles(null);
        }

        const onInsert = () => {
            admPage.value = emptyAdmPage;
            submitted.value = false;
            admPageDialog.value = true;
            loadAdmProfiles(null);
        };

        const onEdit = (param: AdmPage) => {
            admPage.value = { ...param };
            admPageDialog.value = true;
            loadAdmProfiles(admPage.value);
        };

        const hideDialog = () => {
            admPageDialog.value = false;
            submitted.value = false;
        };

        const onSave = () => {
            submitted.value = true;
            admPage.value.admIdProfiles = [];
            pageProfiles.value?.forEach((value: AdmProfile[]) => {
                let sourceProfiles: AdmProfile[] = value;

                sourceProfiles.forEach((value: AdmProfile) => {
                    let targetProfile: AdmProfile = value;
                    if (targetProfile.id){
                        admPage.value.admIdProfiles.push(targetProfile.id);
                    }                    
                });
            });

            if (admPage.value.description && admPage.value.description.trim()) {
                if (admPage.value.id) {
                    admPageService.update(admPage.value).then((obj: AdmPage) => {
                        admPage.value = obj;

                        if(admPage.value.id){
                            const index = admPageService.findIndexById(listaAdmPage.value, admPage.value.id);
                            listaAdmPage.value[index] = admPage.value;

                            toast.add({severity:'success', summary: 'Successful', detail: 'Página Atualizada', life: 3000});
                        }
                    });            
                } else {
                    admPageService.insert(admPage.value).then((obj: AdmPage) => {
                        admPage.value = obj;

                        listaAdmPage.value.push(admPage.value);
                        toast.add({ severity: 'success', summary: 'Successful', detail: 'Página Criada', life: 3000 });
                    });            
                }

                admPageDialog.value = false;
                admPage.value = emptyAdmPage;
            }
        };

        const deleteSelected = () => {
            deleteAdmPagesDialog.value = true;
        }

        const onDelete = (param: AdmPage) => {
            deleteAdmPageDialog.value = true;
            admPage.value = { ...param };
        } 

        const confirmDeleteSelected = () => {
            deleteAdmPagesDialog.value = false;
            listaAdmPage.value = listaAdmPage.value.filter((val: AdmPage) => !selectedAdmPages.value.includes(val));

            let excluiu = false;
            selectedAdmPages.value.forEach((item: AdmPage) => {
                if (item.id){
                    admPageService.delete(item.id).then(() => {
                        excluiu = true;
                    });
                }
            });

            if (excluiu) {
                toast.add({ severity: 'success', summary: 'Sucesso', detail: 'Páginas excluídas', life: 3000 });
                selectedAdmPages.value = [];
            }
        }

        const confirmDelete = () => {
            deleteAdmPageDialog.value = false;
            if (admPage.value.id){
                admPageService.delete(admPage.value.id).then(() => {
                    listaAdmPage.value = listaAdmPage.value.filter((val: AdmPage) => val.id !== admPage.value.id);
                    admPage.value = emptyAdmPage;        
                    toast.add({ severity: 'success', summary: 'Sucesso', detail: 'Página excluída', life: 3000 });
                });
            }
        }

        const onTypeReportChange = (param: { pTypeReport: SelectItemGroup }) => {
            if (param.pTypeReport.value){
                selectedTypeReport.value = param.pTypeReport.value;
                reportParamForm.value = { reportType: param.pTypeReport.value.type, forceDownload: selectedForceDownload.value };
            }        
        }

        const onForceDownloadChange = (param: { forceDownload: boolean }) => {
            selectedForceDownload.value = param.forceDownload;
            if (selectedTypeReport.value){
                reportParamForm.value = { reportType: selectedTypeReport.value.type, forceDownload: param.forceDownload };
            }
        }

        const onExport = () => {
            admPageService.report(reportParamForm.value).then(() => {
                toast.add({ severity: 'info', summary: 'Página exportada', 
                    detail: 'Página exportada', life: 3000 });
            });
        }

        const initFilters = () => {
            filters.value = {
                global: { value: null, matchMode: FilterMatchMode.CONTAINS }
            };
        };
/*
        const exportPdf = () => {
            const head: string[] = [];
            const data: any[] = [];

            exportColumns.value.forEach((item: { title: string; }) => head.push(item.title));
            listaAdmPage.value.forEach((item: AdmPage) => data.push(
                [item.id, item.url, item.description, item.pageProfiles]
            ));

            exportService.exportPdf(head, data, 'paginas.pdf');
        }

        const exportExcel = () => {
            exportService.exportExcel(listaAdmPage.value, 'paginas');
        }
*/

        return { listaAdmPage, admPage, filters, submitted, itemsMenuLinha, toggleMenu, popupMenu,
            selectedAdmPages, deleteSelected, admPageDialog, hideDialog, mostrarListar, mostrarEditar, onClean,
            deleteAdmPageDialog, confirmDelete, deleteAdmPagesDialog, pageProfiles,
            onInsert, onEdit, onDelete, onSave, onExport, onTypeReportChange, onForceDownloadChange,
            confirmDeleteSelected }
    }
}        
</script>

<template>
    <div class="grid">
        <div class="col-12">
            <div class="card px-6 py-6" :style="mostrarListar()">
                <!-- <Toast /> -->
                <Panel header="Página" class="p-mb-2">
                    <ReportPanel @changeTypeReport="onTypeReportChange" @changeForceDownload="onForceDownloadChange"></ReportPanel>
                </Panel>                
                <Toolbar class="mb-4">
                    <template v-slot:start>
                        <div class="my-2">
                            <Button label="Adicionar" icon="pi pi-plus" class="p-button-success mr-2" @click="onInsert" />
                            <Button label="Excluir" icon="pi pi-trash" class="p-button-danger" @click="deleteSelected" 
                                :disabled="!selectedAdmPages || !selectedAdmPages.length" />
                        </div>
                    </template>

                    <template v-slot:end>
                        <Button label="Exportar" icon="pi pi-upload" class="p-button-help" @click="onExport" />
                    </template>
                </Toolbar>

                <Menu ref="popupMenu" id="popup_menu" :model="itemsMenuLinha" :popup="true" />

                <DataTable
                    ref="dt" paginatorPosition="both"
                    :value="listaAdmPage"
                    v-model:selection="selectedAdmPages"
                    dataKey="id"
                    :paginator="true"
                    :rows="10"
                    :filters="filters"
                    paginatorTemplate="FirstPageLink PrevPageLink PageLinks NextPageLink LastPageLink CurrentPageReport RowsPerPageDropdown"
                    :rowsPerPageOptions="[10,30,50,100,150,200]" emptyMessage="Nenhum registro encontrado."
                    currentPageReportTemplate="Mostrando {first} até {last} de {totalRecords} entradas"
                    responsiveLayout="scroll"
                >
                    <template #header>
                        <div class="flex flex-column md:flex-row md:justify-content-between md:align-items-center">
                            <h5 class="m-0">Gerenciar páginas</h5>
                            <span class="block mt-2 md:mt-0 p-input-icon-left">
                                <i class="pi pi-search" />
                                <InputText v-model="filters['global'].value" placeholder="Procurar..." />
                            </span>
                        </div>
                    </template>

                    <Column selectionMode="multiple" headerStyle="width: 3rem"></Column>
                    <Column field="id" header="Id" :sortable="true" headerStyle="width:5%; min-width:5rem;">
                        <template #body="slotProps">
                            <span class="p-column-title">Id</span>
                            {{ slotProps.data.id }}
                        </template>
                    </Column>
                    <Column field="url" header="Página" :sortable="true" headerStyle="min-width:10rem;">
                        <template #body="slotProps">
                            <span class="p-column-title">Página</span>
                            {{ slotProps.data.url }}
                        </template>
                    </Column>
                    <Column field="description" header="Descrição" :sortable="true" headerStyle="min-width:8rem;">
                        <template #body="slotProps">
                            <span class="p-column-title">Descrição</span>
                            {{ slotProps.data.description }}
                        </template>
                    </Column>
                    <Column field="pageProfiles" header="Perfil(s) da página" :sortable="true" headerStyle="min-width:8rem;">
                        <template #body="slotProps">
                            <span class="p-column-title">Perfil(s) da página</span>
                            {{ slotProps.data.pageProfiles }}
                        </template>
                    </Column>
                    <Column headerStyle="min-width:10rem;">
                        <template #body="slotProps">
                            <div class="flex">
                                <Button link icon="pi pi-ellipsis-v" @click="toggleMenu($event, slotProps.data)" 
                                    aria-haspopup="true" aria-controls="popup_menu" />
                            </div>
                        </template>
                    </Column>

                    <template #footer>
                        <div class="p-d-flex p-ai-center p-jc-between">
                            No total existem {{listaAdmPage ? listaAdmPage.length : 0 }} páginas.
                        </div>
                    </template>

                </DataTable>
            </div>

            <div :style="mostrarEditar()">
                <!-- <Toast /> -->
                <Panel header="Detalhes da página" class="p-mb-2">
                    <Toolbar class="mb-4">
                        <template v-slot:start>
                        </template>
                        <template v-slot:end>
                            <div class="my-2">
                                <Button label="Cancelar" icon="pi pi-times" class="p-button-secondary mr-2" @click="hideDialog"></button>
                                <Button label="Limpar" icon="pi pi-star-o" class="p-button-primary mr-2" @click="onClean"></button>
                                <Button label="Salvar" icon="pi pi-check" class="p-button-success" @click="onSave"></button>        
                            </div>
                        </template>
                    </Toolbar>         
                    <div class="card p-fluid">
                        <div class="field">
                            <label for="url">Página:</label>
                            <InputText id="url" v-model="admPage.url" required="true" :class="{'p-invalid': submitted && !admPage.url}" />
                            <small class="p-invalid" v-if="submitted && !admPage.url">A página é obrigatória.</small>
                        </div>
                        <div class="field">
                            <label for="description">Descrição</label>
                            <InputText id="description" v-model="admPage.description" required="true"
                                :class="{ 'p-invalid': submitted && !admPage.description }" />
                            <small class="p-invalid" v-if="submitted && !admPage.description">A descrição é obrigatória.</small>
                        </div>
                        <div class="field">
                            <label for="pageProfiles">Perfil(s) da página:</label>
                            <PickList v-model="pageProfiles" dataKey="id">
                                <template #sourceheader>Disponível</template>
                                <template #targetheader>Selecionada</template>
                                <template #item="slotProps">
                                    <div>
                                        {{slotProps.item.description}}
                                    </div>
                                </template>
                            </PickList>                                
                        </div>
                    </div>               
                </Panel>                
            </div>

            <Dialog v-model:visible="deleteAdmPageDialog" :style="{ width: '450px' }" header="Confirme" :modal="true">
                <div class="flex align-items-center justify-content-center">
                    <i class="pi pi-exclamation-triangle mr-3" style="font-size: 2rem" />
                    <span v-if="admPage">Tem certeza de que deseja excluir <b>{{ admPage.description }}</b>?</span>
                </div>
                <template #footer>
                    <Button label="Não" icon="pi pi-times" class="p-button-text" @click="deleteAdmPageDialog = false" />
                    <Button label="Sim" icon="pi pi-check" class="p-button-text" @click="confirmDelete" />
                </template>
            </Dialog>

            <Dialog v-model:visible="deleteAdmPagesDialog" :style="{ width: '450px' }" header="Confirme" :modal="true">
                <div class="flex align-items-center justify-content-center">
                    <i class="pi pi-exclamation-triangle mr-3" style="font-size: 2rem" />
                    <span v-if="admPage">Tem certeza de que deseja excluir as categorias de parâmetros selecionadas?</span>
                </div>
                <template #footer>
                    <Button label="Não" icon="pi pi-times" class="p-button-text" @click="deleteAdmPagesDialog = false" />
                    <Button label="Sim" icon="pi pi-check" class="p-button-text" @click="confirmDeleteSelected" />
                </template>
            </Dialog>
        </div>
    </div>
</template>

// frontend/hfs-frontend-react-next/app/(main)/admin/admPage/page.tsx
/* eslint-disable @next/next/no-img-element */
'use client';
import { Button } from 'primereact/button';
import { Column } from 'primereact/column';
import { DataTable } from 'primereact/datatable';
import { Dialog } from 'primereact/dialog';
import { InputText } from 'primereact/inputtext';
import { Toast } from 'primereact/toast';
import { Toolbar } from 'primereact/toolbar';
import { classNames } from 'primereact/utils';
import React, { useEffect, useMemo, useRef, useState } from 'react';
import AdmPageService from '../service/AdmPageService';
import { AdmPage, cleanAdmPage, emptyAdmPage } from '../api/AdmPage';
import { ReportParamForm, emptyReportParamForm } from '../../base/models/ReportParamsForm';
import { ItypeReport, PDFReport } from '../../base/services/ReportService';
import { Panel } from 'primereact/panel';
import ReportPanelComponent from '../../base/components/ReportPanel';
import { Menu } from 'primereact/menu';
import { MenuItem } from 'primereact/menuitem';
import { ExportService } from '../../base/services/ExportService';
import { AdmProfile } from '../api/AdmProfile';
import AdmProfileService from '../service/AdmProfileService';
import { PickList } from 'primereact/picklist';
import { CheckboxChangeEvent } from 'primereact/checkbox';

const AdmPagePage = () => {

    const [admPageService,] = useState<AdmPageService>(new AdmPageService());
    const admProfileService = new AdmProfileService();
    const exportService = new ExportService();

    const [listaAdmPage, setListaAdmPage] = useState<AdmPage[]>([]);
    const [admPageDialog, setAdmPageDialog] = useState<boolean>(false);
    const [deleteAdmPageDialog, setDeleteAdmPageDialog] = useState<boolean>(false);
    const [deleteAdmPagesDialog, setDeleteAdmPagesDialog] = useState<boolean>(false);
    const [admPage, setAdmPage] = useState<AdmPage>(emptyAdmPage); 
    const [selectedAdmPages, setSelectedAdmPages] = useState<AdmPage[]>([]);

    const [submitted, setSubmitted] = useState(false);
    const [cols, setCols] = useState<any[]>([]);
    const [exportColumns, setExportColumns] = useState<any[]>([]);
    const [globalFilter, setGlobalFilter] = useState('');
    const toast = useRef<Toast>(null);
    const dt = useRef<DataTable<any>>(null);

    const [selectedTypeReport, setSelectedTypeReport] = useState<ItypeReport>(PDFReport);
    const [selectedForceDownload, setSelectedForceDownload] = useState(true);
    const [reportParamForm, setReportParamForm] = useState<ReportParamForm>(emptyReportParamForm);    

    const [itemsMenuLinha, setItemsMenuLinha] = useState<MenuItem[]>([]);
    const popupMenu = useRef<Menu>(null);

    const [sourceProfiles, setSourceProfiles] = useState<AdmProfile[]>([]);
    const [targetProfiles, setTargetProfiles] = useState<AdmProfile[]>([]);

    useEffect(() => {  
        admPageService.findAll().then(item => setListaAdmPage(item));

        setItemsMenuLinha([{ label: "Editar" }, { label: "Excluir" }]);

        setCols([
            { field: 'id', header: 'Id' },
            { field: 'url', header: 'Página' },
            { field: 'description', header: 'Descrição' },
            { field: 'pageProfiles', header: 'Perfil(s) da página' }
        ]);
            
        setExportColumns(cols.map(col => ({title: col.header, dataKey: col.field})));
      
    }, [admPageService, cols]);

    const toggleMenu = (menu: React.RefObject<Menu>, event: any, rowData: AdmPage) => {
        setItemsMenuLinha([]);

        let _itemsMenuLinha: MenuItem[] = [];

        _itemsMenuLinha.push({
            label: 'Editar',
            command: () => {
                onEdit(rowData);
            }
        });

        _itemsMenuLinha.push({
            label: 'Excluir',
            command: () => {
                onDelete(rowData);
            }
        });

        setItemsMenuLinha(_itemsMenuLinha);

        if (menu.current){
            menu.current.toggle(event);
        }        
    }

    const loadAdmProfiles = (page: AdmPage) => {
        setTargetProfiles([]);
        if (page.id != null) {
            admProfileService.findProfilesByPage(page).then(item => {
                setTargetProfiles(item);

                admProfileService.findAll().then(profiles => {
                    setSourceProfiles(profiles.filter(profile => !item.find(target => target.id === profile.id)));
                });

            });
        } else {
            admProfileService.findAll().then(profiles => setSourceProfiles(profiles));
        }
    }

    const mostrarListar = () => {
        if (admPageDialog)
            return { display: 'none' };
        else
            return { display: '' };
    }

    const mostrarEditar = () => {
        if (admPageDialog)
            return { display: '' };
        else
            return { display: 'none' };
    }

    const onClean = () => {
        setAdmPage(cleanAdmPage);
        loadAdmProfiles(cleanAdmPage);
    }

    const onInsert = () => {
        setAdmPage(emptyAdmPage);
        setSubmitted(false);      
        setAdmPageDialog(true);
        loadAdmProfiles(emptyAdmPage);
    }
    
    const onEdit = (admPage: AdmPage) => {
        setAdmPage({ ...admPage });
        setAdmPageDialog(true);
        loadAdmProfiles(admPage);
    }
    
    const hideDialog = () => {
        setAdmPageDialog(false);
        setSubmitted(false);
    }

    const hideDeleteAdmPageDialog = () => {
        setDeleteAdmPageDialog(false);
    };

    const hideDeleteAdmPagesDialog = () => {
        setDeleteAdmPagesDialog(false);
    };

    const onSave = () => {
        setSubmitted(true);
        admPage.admIdProfiles = [];
        targetProfiles.forEach(item => {
            if (item.id){
                admPage.admIdProfiles.push(item.id);
            }            
        });
        
        if (admPage.description.trim()) {
            let _listaAdmPage = [...listaAdmPage];
            let _admPage = {...admPage};

            if (admPage.id) {
                admPageService.update(admPage).then((obj: AdmPage) => {
                    _admPage = obj;
                    
                    if (admPage.id){
                        const index = admPageService.findIndexById(listaAdmPage, admPage.id);
                        _listaAdmPage[index] = _admPage;
    
                        setListaAdmPage(_listaAdmPage);
                        toast.current?.show({ severity: 'success', summary: 'Sucesso', detail: 'Página Atualizada', life: 3000 });    
                    }
                });
            } else {
                admPageService.insert(admPage).then((obj: AdmPage) => {
                    _admPage = obj;
                    _listaAdmPage.push(_admPage);
                    setListaAdmPage(_listaAdmPage);
                    toast.current?.show({ severity: 'success', summary: 'Sucesso', detail: 'Página Criada', life: 3000 });
                });
            }
            
            setAdmPageDialog(false);
            setAdmPage(emptyAdmPage);            
        }
    }
        
    const deleteSelected = () => {
        setDeleteAdmPagesDialog(true);
    }
  
    const onDelete = (admPage: AdmPage) => {
        setDeleteAdmPageDialog(true);
        setAdmPage({ ...admPage });
    } 
  
    const confirmDeleteSelected = () => {
        setDeleteAdmPagesDialog(false);
        setListaAdmPage(listaAdmPage.filter(val => !selectedAdmPages.includes(val)));
  
        let excluiu = false;
        selectedAdmPages.forEach((item) => {
            if (item.id){
                admPageService.delete(item.id).then(obj => {
                    excluiu = true;
                });    
            }
        });
    
        if (excluiu) {
            toast.current?.show({ severity: 'success', summary: 'Sucesso', detail: 'Páginas excluídas', life: 3000 });
            setSelectedAdmPages([]);
        }
    }
  
    const confirmDelete = () => {
        setDeleteAdmPageDialog(false);
        if (admPage.id){
            admPageService.delete(admPage.id).then(obj => {
                setListaAdmPage(listaAdmPage.filter(val => val.id !== admPage.id));
                setAdmPage(emptyAdmPage); 
                toast.current?.show({ severity: 'success', summary: 'Sucesso', detail: 'Página excluída', life: 3000 });
            });
        }
    }
  
    const onChangedTypeReport = (typeReport: ItypeReport) => {
        setSelectedTypeReport(typeReport);
        setReportParamForm({ reportType: typeReport.type, 
          forceDownload: selectedForceDownload });
    }
    
    const onChangedForceDownload = (event: CheckboxChangeEvent) => {
        const forceDownload = event.checked;
        if (forceDownload){
            setSelectedForceDownload(forceDownload);
            setReportParamForm({ reportType: selectedTypeReport.type, 
              forceDownload: forceDownload });    
        }
    }
    
    const onExport = () => {
        admPageService.report(reportParamForm).then(() => {
          toast.current?.show({ severity: 'info', summary: 'Página exportada', 
            detail: 'Página exportada', life: 3000 });
        });
    }

    const exportPdf = () => {
        const head: string[] = [];
        const data: any[] = [];
    
        exportColumns.forEach(item => head.push(item.title));
        listaAdmPage.forEach((item: AdmPage) => data.push(
            [item.id, item.url, item.description, item.pageProfiles]
        ));
    
        exportService.exportPdf(head, data, 'Paginas.pdf');
      }
    
    const exportExcel = () => {
        exportService.exportExcel(listaAdmPage, 'Paginas');
    }

    const onUrlChange = (e: React.FormEvent<HTMLInputElement>) => {
        const val: string = (e.currentTarget && e.currentTarget.value) || '';
        let _admPage = { ...admPage };
        _admPage.url = val;

        setAdmPage(_admPage);
    }

    const onDescriptionInputChange = (e: React.FormEvent<HTMLInputElement>) => {
        const val = (e.target && e.currentTarget.value) || '';
        let _admPage = { ...admPage };
        _admPage.description = val;

        setAdmPage(_admPage);
    };

    const leftToolbarTemplate = () => {
        return (
            <React.Fragment>
                <div className="my-2">
                    <Button label="Adicionar" icon="pi pi-plus" severity="success" className=" mr-2" onClick={onInsert} />
                    <Button label="Excluir" icon="pi pi-trash" severity="danger" onClick={deleteSelected} 
                        disabled={!selectedAdmPages || !(selectedAdmPages as any).length} />
                </div>
            </React.Fragment>
        );
    };

    const rightToolbarTemplate = () => {
        return (
            <React.Fragment>
                <Button label="Exportar" icon="pi pi-upload" className="p-button-help" onClick={onExport} />
            </React.Fragment>
        );
    };

    const leftEditToolbarTemplate = () => {
        return (
            <React.Fragment>
            </React.Fragment>
        );
    };

    const rightEditToolbarTemplate = () => {
        return (
            <React.Fragment>
                <Button label="Cancelar" icon="pi pi-times" className="p-button-secondary mr-2" onClick={hideDialog} />
                <Button label="Limpar" icon="pi pi-star-o" className="p-button-primary mr-2" onClick={onClean} />
                <Button label="Salvar" icon="pi pi-check" className="p-button-success" onClick={onSave} />
            </React.Fragment>
        );
    };

    const tabelaHeader = (
        <div className="flex flex-column md:flex-row md:justify-content-between md:align-items-center">
            <h5 className="m-0">Gerenciar páginas</h5>
            <span className="block mt-2 md:mt-0 p-input-icon-left">
                <i className="pi pi-search" />
                <InputText type="search" onInput={(e) => setGlobalFilter(e.currentTarget.value)} placeholder="Procurar..." />
            </span>
        </div>
    );

    const tabelaFooter = (
        <div className="p-d-flex p-ai-center p-jc-between">
            No total existem {listaAdmPage ? listaAdmPage.length : 0 } páginas.
        </div>
    );

    const idBodyTemplate = (rowData: AdmPage) => {
        return (
            <>
                <span className="p-column-title">Id</span>
                {rowData.id}
            </>
        );
    };    

    const urlBodyTemplate = (rowData: AdmPage) => {
        return (
            <>
                <span className="p-column-title">Página</span>
                {rowData.url}
            </>
        );
    };    

    const pageProfilesBodyTemplate = (rowData: AdmPage) => {
        return (
            <>
                <span className="p-column-title">Perfil(s) da página</span>
                {rowData.pageProfiles}
            </>
        );
    };    

    const descriptionBodyTemplate = (rowData: AdmPage) => {
        return (
            <>
                <span className="p-column-title">Descrição</span>
                {rowData.description}
            </>
        );
    };    

    const actionBodyTemplate = (rowData: AdmPage) => {
        if (rowData){            
            return (
                <>
                    <div className="flex">                        
                        <Button link icon="pi pi-ellipsis-v" onClick={(event) => toggleMenu(popupMenu, event, rowData)} style={{ cursor: 'pointer' }} 
                            aria-controls="popup_menu" aria-haspopup />                            
                    </div>
                </>
            );
        }
    };

    const onPageProfilesChange = (event: { 
        source: React.SetStateAction<AdmProfile[]>; 
        target: React.SetStateAction<AdmProfile[]>; }) => {
        setSourceProfiles(event.source);
        setTargetProfiles(event.target);
    }    

    const itemTemplate = (item: AdmProfile) => {
        return (
          <div>
              {item.description}
          </div>
        );
    }
        
    const deleteAdmPageDialogFooter = (
        <>
            <Button label="Não" icon="pi pi-times" text onClick={hideDeleteAdmPageDialog} />
            <Button label="sim" icon="pi pi-check" text onClick={confirmDelete} />
        </>
    );
    
    const deleteAdmPagesDialogFooter = (
        <>
            <Button label="Não" icon="pi pi-times" text onClick={hideDeleteAdmPagesDialog} />
            <Button label="Sim" icon="pi pi-check" text onClick={confirmDeleteSelected} />
        </>
    );

    return (
        <div className="grid crud-demo">
            <div className="col-12">
                <div className="card px-6 py-6" style={mostrarListar()}>
                    <Toast ref={toast} />
                    <Panel header="Página" className="p-mb-2">
                        <ReportPanelComponent typeReportChange={e => onChangedTypeReport(e.value)}
                            forceDownloadChange={e => onChangedForceDownload(e)}
                        ></ReportPanelComponent>
                    </Panel>

                    <Toolbar className="mb-4" start={leftToolbarTemplate} end={rightToolbarTemplate}></Toolbar>

                    <Menu model={itemsMenuLinha} popup ref={popupMenu} id="popup_menu" popupAlignment="right" />

                    <DataTable ref={dt} value={listaAdmPage} selection={selectedAdmPages} paginatorPosition="both"
                        onSelectionChange={(e) => setSelectedAdmPages(e.value as any)}
                        dataKey="id" paginator rows={10} rowsPerPageOptions={[10,30,50,100,150,200]} className="datatable-responsive"
                        paginatorTemplate="FirstPageLink PrevPageLink PageLinks NextPageLink LastPageLink CurrentPageReport RowsPerPageDropdown"
                        currentPageReportTemplate="Mostrando {first} até {last} de {totalRecords} entradas" 
                        globalFilter={globalFilter} emptyMessage="Nenhum registro encontrado."
                        header={tabelaHeader} footer={tabelaFooter} responsiveLayout="scroll"
                    >
                        <Column selectionMode="multiple" headerStyle={{ width: '4rem' }}></Column>
                        <Column field="id" header="Id" sortable headerStyle={{ width: '5%', minWidth: '5rem' }} body={idBodyTemplate}></Column>
                        <Column field="url" header="Página" sortable headerStyle={{ minWidth: '10rem' }} body={urlBodyTemplate}></Column>
                        <Column field="description" header="Descrição" sortable headerStyle={{ minWidth: '8rem' }} body={descriptionBodyTemplate}></Column>
                        <Column field="pageProfiles" header="Perfil(s) da página" sortable headerStyle={{ minWidth: '8rem' }} body={pageProfilesBodyTemplate}></Column>                        
                        <Column body={actionBodyTemplate} headerStyle={{ minWidth: '10rem' }}></Column>
                    </DataTable>
                </div>

                <div className="card px-6 py-6" style={mostrarEditar()}>
                    <Toast ref={toast} />
                    <Panel header="Detalhes da página" className="p-mb-2">
                        <Toolbar className="mb-4" start={leftEditToolbarTemplate} end={rightEditToolbarTemplate}></Toolbar>
                    </Panel>
                    <div className="card p-fluid">
                        <div className="field">
                            <label htmlFor="url">Página:</label>
                            <InputText id="url" value={admPage.url} onChange={(e) => onUrlChange(e)} required 
                                className={classNames({'p-invalid': submitted && !admPage.url})} />
                            {submitted && !admPage.url && <small className="p-invalid">A página é obrigatória.</small>}
                        </div>
                        <div className="field">
                            <label htmlFor="description">Descrição</label>
                            <InputText id="description" value={admPage.description} onChange={(e) => onDescriptionInputChange(e)} required
                                className={classNames({'p-invalid': submitted && !admPage.description})}
                            />
                            {submitted && !admPage.description && <small className="p-invalid">A descrição é obrigatória.</small>}
                        </div>
                        <div className="field">
                            <label htmlFor="pageProfiles">Perfil(s) da página:</label>
                            <PickList source={sourceProfiles} target={targetProfiles} itemTemplate={itemTemplate}
                                sourceHeader="Disponível" targetHeader="Selecionada"
                                sourceStyle={{height:'30rem'}} targetStyle={{height:'30rem'}} onChange={onPageProfilesChange}>
                            </PickList>                            
                        </div>    
                    </div>
                </div>                

                <Dialog visible={deleteAdmPageDialog} style={{ width: '450px' }} header="Confirm" modal 
                    footer={deleteAdmPageDialogFooter} onHide={hideDeleteAdmPageDialog}>
                    <div className="flex align-items-center justify-content-center">
                        <i className="pi pi-exclamation-triangle mr-3" style={{ fontSize: '2rem' }} />
                        {admPage && (
                            <span>
                                Tem certeza de que deseja excluir <b>{admPage.description}</b>?
                            </span>
                        )}
                    </div>
                </Dialog>

                <Dialog visible={deleteAdmPagesDialog} style={{ width: '450px' }} header="Confirm" modal 
                    footer={deleteAdmPagesDialogFooter} onHide={hideDeleteAdmPagesDialog}>
                    <div className="flex align-items-center justify-content-center">
                        <i className="pi pi-exclamation-triangle mr-3" style={{ fontSize: '2rem' }} />
                        {admPage && <span>Tem certeza de que deseja excluir as categorias de parâmetros selecionadas?</span>}
                    </div>
                </Dialog>

            </div>
        </div>
    );
};

export default AdmPagePage;
