// frontend/hfs-frontend-vuetify/src/layout/AppConfig.vue
<script setup>
import { ref } from 'vue';
import { useLayout } from '@/layout/composables/layout';

defineProps({
    simple: {
        type: Boolean,
        default: false
    }
});
const scales = ref([12, 13, 14, 15, 16]);
const visible = ref(false);

const { changeThemeSettings, setScale, layoutConfig } = useLayout();

const onConfigButtonClick = () => {
    visible.value = !visible.value;
};
const onChangeTheme = (theme, mode) => {
    const elementId = 'theme-css';
    const linkElement = document.getElementById(elementId);
    const cloneLinkElement = linkElement.cloneNode(true);
    const newThemeUrl = linkElement.getAttribute('href').replace(layoutConfig.theme.value, theme);
    cloneLinkElement.setAttribute('id', elementId + '-clone');
    cloneLinkElement.setAttribute('href', newThemeUrl);
    cloneLinkElement.addEventListener('load', () => {
        linkElement.remove();
        cloneLinkElement.setAttribute('id', elementId);
        changeThemeSettings(theme, mode === 'dark');
    });
    linkElement.parentNode.insertBefore(cloneLinkElement, linkElement.nextSibling);
};
const decrementScale = () => {
    setScale(layoutConfig.scale.value - 1);
    applyScale();
};
const incrementScale = () => {
    setScale(layoutConfig.scale.value + 1);
    applyScale();
};
const applyScale = () => {
    document.documentElement.style.fontSize = layoutConfig.scale.value + 'px';
};

const changeMenuMode = (valor) => {
    layoutConfig.menuMode.value = valor;
};

const changeInputStyle = (valor) => {
    layoutConfig.inputStyle.value = valor;
};

</script>

<template>
    <div class="grid">
        <div class="col-12">
            <div class="card px-6 py-6">    
                <h5>Esquema de cor</h5>
                <div class="grid">
                    <div class="col-2">
                        <v-btn icon="light_mode" :style="{ marginRight: '10px' }" @click="onChangeTheme('lara-light-indigo', 'light')"></v-btn>
                        <v-btn icon="dark_mode" @click="onChangeTheme('lara-dark-indigo', 'dark')"></v-btn>                        
                    </div>
                </div>

                <h5>Escala</h5>
                <div class="grid">
                    <div class="col-2">
                        <v-btn icon="remove" @click="decrementScale()" :disabled="layoutConfig.scale.value === scales[0]" :style="{ marginRight: '10px' }"></v-btn>
                        <v-btn icon="add" @click="incrementScale()" :disabled="layoutConfig.scale.value === scales[scales.length - 1]"></v-btn>
                    </div>    
                </div>

                <h5>Tipo de menu</h5>
                <div class="flex">
                    <v-radio-group>
                        <v-radio label="Static" value="static" @click="changeMenuMode('static')"></v-radio>
                        <v-radio label="Overlay" value="overlay" @click="changeMenuMode('overlay')" ></v-radio>                        
                    </v-radio-group>
                </div>

                <h5>Estilo de entrada</h5>
                <div class="flex">
                    <v-radio-group>
                        <v-radio label="Outlined" value="outlined" @click="changeInputStyle('outlined')"></v-radio>
                        <v-radio label="Filled" value="filled" @click="changeInputStyle('filled')"></v-radio>
                    </v-radio-group>
                </div>

                <h5>Efeito cascata</h5>
                <v-btn-toggle rounded="xl">
                    <v-btn icon="toggle_off" @click="layoutConfig.ripple.value = true"></v-btn>
                    <v-btn icon="toggle_on" @click="layoutConfig.ripple.value = false"></v-btn>
                </v-btn-toggle>                    
        </div>
    </div>
</div>
</template>

<style lang="scss" scoped></style>

// frontend/hfs-frontend-material/src/app/layout/config/app.config.component.ts
import { Component, Input } from '@angular/core';
import { LayoutService } from '../service/app.layout.service';
import { MenuService } from '../app.menu.service';

@Component({
    selector: 'app-config',
    templateUrl: './app.config.component.html',
})
export class AppConfigComponent {
    @Input() minimal: boolean = false;

    scales: number[] = [12, 13, 14, 15, 16];

    constructor(
        public layoutService: LayoutService,
        public menuService: MenuService        
    ) {}

    get visible(): boolean {
        return this.layoutService.state.configSidebarVisible;
    }
    set visible(_val: boolean) {
        this.layoutService.state.configSidebarVisible = _val;
    }

    get scale(): number {
        return this.layoutService.config().scale;
    }
    set scale(_val: number) {
        this.layoutService.config.update((config) => ({
            ...config,
            scale: _val,
        }));
    }

    get menuMode(): string {
        return this.layoutService.config().menuMode;
    }
    set menuMode(_val: string) {
        this.layoutService.config.update((config) => ({
            ...config,
            menuMode: _val,
        }));
    }

    get inputStyle(): string {
        return this.layoutService.config().inputStyle;
    }
    set inputStyle(_val: string) {
        this.layoutService.config().inputStyle = _val;
    }

    get ripple(): boolean {
        return this.layoutService.config().ripple;
    }
    set ripple(_val: boolean) {
        this.layoutService.config.update((config) => ({
            ...config,
            ripple: _val,
        }));
    }

    set theme(val: string) {
        this.layoutService.config.update((config) => ({
            ...config,
            theme: val,
        }));
    }
    get theme(): string {
        return this.layoutService.config().theme;
    }

    set colorScheme(val: string) {
        this.layoutService.config.update((config) => ({
            ...config,
            colorScheme: val,
        }));
    }
    get colorScheme(): string {
        return this.layoutService.config().colorScheme;
    }

    onConfigButtonClick() {
        this.layoutService.showConfigSidebar();
    }

    changeTheme(theme: string, colorScheme: string) {
        this.theme = theme;
        this.colorScheme = colorScheme;
    }

    decrementScale() {
        this.scale--;
    }

    incrementScale() {
        this.scale++;
    }

    changeMenuMode(valor: string) {
        this.menuMode = valor;
        
    };

    changeInputStyle(valor: string) {
        this.inputStyle = valor;
    };
}

<div class="grid">
    <div class="col-12">
        <div class="card px-6 py-6">

            <h5>Esquema de cor</h5>
            <div class="grid">
                <div class="col-2">
                    <button mat-icon-button class="p-link w-4rem h-2rem" (click)="changeTheme('lara-light-indigo', 'light')">
                        <mat-icon style="font-size: 1.8rem">light_mode</mat-icon>
                    </button>
                    <button mat-icon-button class="p-link w-4rem h-2rem" (click)="changeTheme('lara-dark-indigo', 'dark')">
                        <mat-icon style="font-size: 1.8rem">dark_mode</mat-icon>
                    </button>
                </div>
            </div>
        
            <h5>Escala</h5>
            <div class="grid">
                <div class="col-2">
                    <button mat-icon-button (click)="decrementScale()" class="p-button-text p-button-rounded w-2rem h-2rem mr-2" [disabled]="scale === scales[0]">
                        <mat-icon style="font-size: 1.8rem">remove</mat-icon>
                    </button>
                    <button mat-icon-button (click)="incrementScale()" class="p-button-text p-button-rounded w-2rem h-2rem ml-2" [disabled]="scale === scales[scales.length - 1]">
                        <mat-icon style="font-size: 1.8rem">add</mat-icon>
                    </button>
                </div>
            </div>
            
            <ng-container *ngIf="!minimal">
                <h5>Tipo de menu</h5>
                <mat-radio-group aria-label="Tipo de menu" [(ngModel)]="menuMode">
                    <div class="field-radiobutton">
                        <mat-radio-button id="mode1" value="static" (click)="changeMenuMode('static')"></mat-radio-button>
                        <label for="mode1">Static</label>
                    </div>
                    <div class="field-radiobutton">
                        <mat-radio-button id="mode2" value="overlay" (click)="changeMenuMode('overlay')"></mat-radio-button>
                        <label for="mode2">Overlay</label>
                    </div>
                </mat-radio-group>
            </ng-container>

            <ng-container *ngIf="!minimal">
                <h5>Estilo de entrada</h5>
                <div class="flex">
                    <mat-radio-group aria-label="Tipo de menu" [(ngModel)]="inputStyle">
                        <div class="field-radiobutton flex-1">
                            <mat-radio-button id="outlined_input" value="outlined" (click)="changeInputStyle('outlined')"></mat-radio-button>
                            <label for="outlined_input">Outlined</label>
                        </div>
                        <div class="field-radiobutton flex-1">
                            <mat-radio-button id="filled_input" value="filled" (click)="changeInputStyle('filled')" ></mat-radio-button>
                            <label for="filled_input">Filled</label>
                        </div>    
                    </mat-radio-group>
                </div>
            </ng-container>
        </div>
    </div>
</div>
