// frontend/hfs-frontend-vuetify/src/hfsfullstack/pages/Funcionario.vue
<script lang="ts">
import { ref, onMounted, onBeforeMount, shallowRef, watch } from 'vue';
import { ReportParamForm, emptyReportParamForm } from '../../base/models/ReportParamsForm';
import { ItypeReport, PDFReport, SelectItemGroup } from '../../base/services/ReportService';
import { SnackbarMessage, emptySnackbarMessage } from '../../base/models/SnackbarMessage';
import { Funcionario, cleanFuncionario, emptyFuncionario } from '../api/funcionario';
import FuncionarioService from '../service/FuncionarioService';
import { ExportService } from '../../base/services/ExportService';
import { DataTableFilterMeta, LazyTableParam, emptyLazyTableParam } from '../../base/models/LazyTableParam';
import { PaginationDTO } from '../../base/models/PaginationDTO';

export default {
    setup() {
        const snackbar = ref<SnackbarMessage>(emptySnackbarMessage);

        const listaFuncionario = ref<Funcionario[]>([]);
        const funcionarioDialog = shallowRef(false)
        const deleteFuncionarioDialog = ref(false);
        const deleteFuncionariosDialog = ref(false);
        const funcionario = ref(emptyFuncionario);
        const selectedFuncionarios = ref<number[]>([]);
        const submitted = ref(false);

        const funcionarioService = new FuncionarioService();
        const exportService = new ExportService();
        //const baseUtilService = new BaseUtilService();

        const selectedTypeReport = ref<ItypeReport>();
        const selectedForceDownload = ref(true);
        const reportParamForm = ref<ReportParamForm>(emptyReportParamForm);

        const itemsPerPage = ref(10);
        const columns = ref();        
        const exportColumns = ref([]);
        const loading = ref(true);
        const totalItems = ref(0);
        const search = ref('');
        const form = ref();
        const nomePesquisa = ref('')

        const filters = ref<DataTableFilterMeta>({
            global: { value: '', matchMode: 'contains' },
            'nome': {value: '', matchMode: 'startsWith'},
        });        

        const lazyParams = ref<LazyTableParam>(emptyLazyTableParam);

        onBeforeMount(() => {
            columns.value = [
                { key: 'actions', title: "Ações", sortable: false, minWidth: '5rem' },
                { key: 'id', title: 'Código', sortable: true, align: 'start', minWidth: '5rem' },
                { key: 'nome', title: 'Nome', sortable: true, align: 'start', minWidth: '30rem' },
                { key: 'cpfFormatado', title: 'Cpf', sortable: true, align: 'start', minWidth: '10rem' },
                { key: 'email', title: 'Email', sortable: true, align: 'start', minWidth: '10rem' },
                { key: 'telefone', title: 'Telefone', sortable: true, align: 'start', minWidth: '10rem' },
                { key: 'celular', title: 'Celular', sortable: true, align: 'start', minWidth: '20rem' },
                { key: 'setor', title: 'Setor', sortable: true, align: 'start', minWidth: '10rem' },
                { key: 'codCargo', title: 'CodCargo', type: 'number', sortable: true, align: 'start', minWidth: '10rem' },
                { key: 'cargo', title: 'Cargo', sortable: true, align: 'start', minWidth: '20rem' },
                { key: 'dataAdmissaoFormatada', title: 'Data Admissão', sortable: true, align: 'start', minWidth: '10rem' },
                { key: 'dataSaidaFormatada', title: 'Data Saída', sortable: true, align: 'start', minWidth: '10rem' },
                { key: 'ativo', title: 'Ativo', minWidth: '10rem' }
            ];
        });

        onMounted(() => {
            selectedTypeReport.value = PDFReport.value;
            exportColumns.value = columns.value.map((col: { header: any; field: any; }) => ({title: col.header, dataKey: col.field}));
        });

        const loadFuncionarios = ({ page, itemsPerPage, sortBy }) => { 
            loading.value = true;

            let sortField: string | null = null;
            let sortOrder: number | null = null;

            if (sortBy.length > 0) {
                sortField = sortBy[0].key;
                sortOrder = sortBy[0].order === 'asc' ? 1 : 0;
            }

            lazyParams.value = {
                first: page,
                rows: itemsPerPage,
                sortField: sortField,
                sortOrder: sortOrder,
                filters: { 'nome': {value: nomePesquisa, matchMode: 'startsWith'} }
            };

            funcionarioService.findAllPaginated(lazyParams.value).then((data: PaginationDTO) => {
                listaFuncionario.value = data.content;
                totalItems.value = data.totalElements;
                loading.value = false;
            });
        }      
        
        watch(nomePesquisa, () => {
            search.value = String(Date.now())
        })

        const snackBar = (msg: string, duration: number) => {
            snackbar.value.open = true;
            snackbar.value.message = msg;
            snackbar.value.timeout = duration;
        }

        const mostrarListar = () => {
            if (funcionarioDialog.value)
                return { display: 'none' };
            else
                return { display: '' };
        }

        const mostrarEditar = () => {
            if (funcionarioDialog.value)
                return { display: '' };
            else
                return { display: 'none' };
        }

        const onInsert = () => {
            funcionario.value = emptyFuncionario;
            submitted.value = false;
            funcionarioDialog.value = true;
        };

        const onEdit = (param: Funcionario) => {
            funcionario.value = { ...param };
            funcionarioDialog.value = true;
        };

        const hideDialog = () => {
            funcionarioDialog.value = false;
            submitted.value = false;
        };

        const onClean = () => {
            funcionario.value = cleanFuncionario;
        }

        const onSave = () => {
            submitted.value = true;
            /*
            if (funcionario.cpfFormatado){
                funcionario.cpf = baseUtilService.cpfFormatadoParaCpf(funcionario.cpfFormatado);
            }
            if (funcionario.dataAdmissaoFormatada){
                funcionario.dataAdmissao = baseUtilService.dataStringToDate(funcionario.dataAdmissaoFormatada);
            }
            if (funcionario.dataSaidaFormatada){
                funcionario.dataSaida = baseUtilService.dataStringToDate(funcionario.dataSaidaFormatada);
            } 
            */       

            if (funcionario.value.nome && funcionario.value.nome.trim()) {
                if (funcionario.value.id) {
                    funcionarioService.update(funcionario.value).then((obj: Funcionario) => {
                        funcionario.value = obj;

                        if (funcionario.value.id){
                            const index = funcionarioService.findIndexById(listaFuncionario.value, funcionario.value.id);
                            listaFuncionario.value[index] = funcionario.value;
                            snackBar('Funcionário Atualizado', 3000);
                        }
                    });            
                } else {
                    funcionarioService.insert(funcionario.value).then((obj: Funcionario) => {
                        funcionario.value = obj;

                        listaFuncionario.value.push(funcionario.value);
                        snackBar('Funcionário Criado', 3000);
                    });            
                }

                funcionarioDialog.value = false;
                funcionario.value = emptyFuncionario;
            }
        };

        const deleteSelected = () => {
            deleteFuncionariosDialog.value = true;
        }

        const onDelete = (param: Funcionario) => {
            deleteFuncionarioDialog.value = true;
            funcionario.value = { ...param };
        } 

        const confirmDeleteSelected = () => {            
            deleteFuncionariosDialog.value = false;
            
            let selecionados: Funcionario[] = [];
            listaFuncionario.value.forEach((item: Funcionario) => {
                selectedFuncionarios.value.forEach((id: number) => {
                    if (item.id === id){
                        selecionados.push(item);
                    }
                });        
            });

            if (selecionados.length > 0){
                listaFuncionario.value = listaFuncionario.value.filter(
                    (val: Funcionario) => !selecionados.includes(val));

                    selecionados.forEach((item: Funcionario, index: number) => {
                    if (item.id){
                        funcionarioService.delete(item.id).then(() => {

                            if (selecionados.length == (index+1)){
                                snackBar('Funcionários excluídos', 3000);
                                selectedFuncionarios.value = [];
                            }

                        });
                    }
                });

            }
        }

        const confirmDelete = () => {
            deleteFuncionarioDialog.value = false;
            if (funcionario.value.id){
                funcionarioService.delete(funcionario.value.id).then(() => {
                    listaFuncionario.value = listaFuncionario.value.filter((val: Funcionario) => val.id !== funcionario.value.id);
                    funcionario.value = emptyFuncionario;        
                    snackBar('Funcionário excluído', 3000);
                });
            }    
        }

        const onTypeReportChange = (param: { pTypeReport: SelectItemGroup }) => {            
            if (param.pTypeReport.value){
                selectedTypeReport.value = param.pTypeReport.value;
                reportParamForm.value = { reportType: param.pTypeReport.value.type, forceDownload: selectedForceDownload.value };
            }        
        }

        const onForceDownloadChange = (param: { forceDownload: boolean }) => {
            selectedForceDownload.value = param.forceDownload;
            if (selectedTypeReport.value){
                reportParamForm.value = { reportType: selectedTypeReport.value.type, forceDownload: param.forceDownload };
            }
        }

        const onExport = () => {
            funcionarioService.report(reportParamForm.value).then(() => {
                snackBar('Funcionário exportado', 3000);
            });            
        }

        const exportPdf = () => {
            const head: string[] = [];
            const data: any[] = [];

            exportColumns.value.forEach(item => head.push(item.title));
            listaFuncionario.value.forEach(item => data.push(
                [item.id, item.nome, item.cpfFormatado, item.email, item.telefone, item.celular, 
                item.setor, item.codCargo, item.cargo, item.dataAdmissaoFormatada, item.dataSaidaFormatada, item.ativo]
            ));

            exportService.exportPdf(head, data, 'funcionarios.pdf');
        }
        
        const exportExcel = () => {
            exportService.exportExcel(listaFuncionario.value, 'funcionarios');
        }    

        return { listaFuncionario, funcionario, submitted, mostrarListar, mostrarEditar, loadFuncionarios,
            selectedFuncionarios, deleteSelected, funcionarioDialog, hideDialog, onClean, nomePesquisa,
            deleteFuncionarioDialog, confirmDelete, deleteFuncionariosDialog, exportExcel, exportPdf,
            onInsert, onEdit, onDelete, onSave, onExport, onTypeReportChange, onForceDownloadChange,
            confirmDeleteSelected, itemsPerPage, columns, loading, totalItems, search, snackbar }
    }
}        
</script>

<template>
    <div class="grid">
        <div class="col-12">
            <v-snackbar v-model="snackbar.open" :timeout="snackbar.timeout" location="top">
                {{ snackbar.message }}
                <template v-slot:actions>
                    <v-btn color="red" density="compact" icon="close" @click="snackbar.open = false"></v-btn>
                </template>
            </v-snackbar>

            <div class="card px-6 py-6" :style="mostrarListar()">
                <v-card-item>
                    <v-card-title>Funcionário</v-card-title>
                </v-card-item>
                <v-card-text>
                    <ReportPanel @changeTypeReport="onTypeReportChange" @changeForceDownload="onForceDownloadChange"></ReportPanel>
                </v-card-text>

                <v-toolbar>
                    <v-btn prepend-icon="add" @click="onInsert" variant="elevated" color="green" :style="{ marginRight: '10px' }">Adicionar</v-btn>
                    <v-btn prepend-icon="delete" @click="deleteSelected" variant="elevated" color="red"
                        :disabled="!selectedFuncionarios || !selectedFuncionarios.length" :style="{ marginRight: '10px' }">Excluir</v-btn>
                        
                    <span class="spacer"></span>
                        
                    <v-btn icon="description" @click="exportExcel" variant="elevated"></v-btn>
                    <v-btn icon="picture_as_pdf" @click="exportPdf" variant="elevated"></v-btn>

                    <span class="spacer"></span>

                    <v-btn prepend-icon="upload" @click="onExport" variant="elevated" color="indigo-darken-3">Exportar</v-btn>
                </v-toolbar>

                <v-toolbar>
                    <span class="spacer"></span>
                    <v-text-field v-model="nomePesquisa" class="ma-2" density="compact" 
                        placeholder="Pesquisar nome..." hide-details style="max-width: 300px">
                    </v-text-field>
                </v-toolbar>

                <v-data-table-server
                    v-model="selectedFuncionarios"
                    v-model:items-per-page="itemsPerPage"
                    :headers="columns"
                    :items="listaFuncionario"
                    :items-length="totalItems"
                    :loading="loading"
                    loading-text="Carregando, por favor espere"
                    :search="search"
                    item-value="id"
                    show-select
                    @update:options="loadFuncionarios"
                    :sort-by="[{ key: 'id', order: 'asc' }]">

                    <template v-slot:item.actions="{ item }">
                        <v-icon class="me-2" size="small" @click="onEdit(item)">edit</v-icon>
                        <v-icon size="small" @click="onDelete(item)">delete</v-icon>
                    </template>
                    
                </v-data-table-server>
            </div>    

            <div :style="mostrarEditar()">
                <v-card-item>
                    <v-card-title>Funcionário</v-card-title>
                </v-card-item>
                <v-card-text>
                    <v-toolbar>
                        <v-spacer></v-spacer>
                        <v-btn prepend-icon="cancel" color="secondary" :style="{ marginRight: '10px' }" @click="hideDialog" variant="elevated">Cancelar</v-btn>
                        <v-btn prepend-icon="star" color="secondary" :style="{ marginRight: '10px' }" @click="onClean" variant="elevated">Limpar</v-btn>
                        <v-btn prepend-icon="check" color="primary" @click="onSave" variant="elevated">Salvar</v-btn>
                    </v-toolbar>                

                    <v-form ref="form">
                        <v-container>
                            <v-row>
                                <v-col cols="12">
                                    <v-text-field label="Descrição" v-model="funcionario.nome" required autofocus
                                        :class="{ 'text-red': submitted && !funcionario.nome }">
                                    </v-text-field>
                                </v-col>
                            </v-row>
                            <v-row v-if="submitted && !funcionario.nome">
                                <v-col cols="12">
                                    <small class="text-red" v-if="submitted && !funcionario.nome">O nome é obrigatório.</small>
                                </v-col>                                    
                            </v-row>
                            <v-row>
                                <v-col cols="12">
                                    <v-text-field label="Email" v-model="funcionario.email"></v-text-field>
                                </v-col>                                
                            </v-row>
                            <v-row>
                                <v-col cols="6" md="6">
                                    <v-text-field label="Cpf" v-model="funcionario.cpfFormatado" required
                                        :class="{ 'text-red': submitted && !funcionario.cpfFormatado }">
                                    </v-text-field>
                                    <small class="text-red" v-if="submitted && !funcionario.cpfFormatado">O Cpf é obrigatório.</small>
                                </v-col>
                                <v-col cols="6" md="6">
                                    <v-text-field label="Telefone" v-model="funcionario.telefone"></v-text-field>
                                </v-col>
                            </v-row>
                            <v-row>
                                <v-col cols="6" md="6">
                                    <v-text-field label="Celular" v-model="funcionario.celular"></v-text-field>
                                </v-col>
                                <v-col cols="6" md="6">
                                    <v-text-field label="Setor" v-model="funcionario.setor"></v-text-field>
                                </v-col>
                            </v-row>
                            <v-row>
                                <v-col cols="6" md="6">
                                    <v-text-field type="number" label="CodCargo" v-model="funcionario.codCargo"></v-text-field>
                                </v-col>
                                <v-col cols="6" md="6">
                                    <v-text-field label="Cargo" v-model="funcionario.cargo"></v-text-field>
                                </v-col>
                            </v-row>
                            <v-row>
                                <v-col cols="6" md="6">
                                    <v-text-field type="date" label="Data Admissão" v-model="funcionario.dataAdmissao"></v-text-field>
                                </v-col>
                                <v-col cols="6" md="6">
                                    <v-text-field type="date" label="Data Saída" v-model="funcionario.dataSaida"></v-text-field>
                                </v-col>
                            </v-row>
                            <v-row>
                                <v-checkbox v-model="funcionario.ativo" label="Ativo"></v-checkbox>
                            </v-row>                            
                        </v-container>
                    </v-form>
                </v-card-text>
            </div>
        
            <v-dialog v-model="deleteFuncionarioDialog" max-width="450" persistent>
                <v-card prepend-icon="warning" title="Confirme">
                    <v-card-text>
                        <span v-if="funcionario">Tem certeza de que deseja excluir <b>{{ funcionario.nome }}</b>?</span>
                    </v-card-text>                        
                    <template v-slot:actions>
                        <v-spacer></v-spacer>
                        <v-btn prepend-icon="cancel" color="secondary" :style="{ marginRight: '10px' }" 
                            @click="deleteFuncionarioDialog = false" variant="elevated">Não</v-btn>
                        <v-btn prepend-icon="check" color="primary" @click="confirmDelete" variant="elevated">Sim</v-btn>
                    </template>
                </v-card>
            </v-dialog>

            <v-dialog v-model="deleteFuncionariosDialog" max-width="450" persistent>
                <v-card prepend-icon="warning" title="Confirme">
                    <v-card-text>
                        <span v-if="funcionario">Tem certeza de que deseja excluir os funcionários selecionados?</span>
                    </v-card-text>                        
                    <template v-slot:actions>
                        <v-spacer></v-spacer>
                        <v-btn prepend-icon="cancel" color="secondary" :style="{ marginRight: '10px' }" 
                            @click="deleteFuncionariosDialog = false" variant="elevated">Não</v-btn>
                        <v-btn prepend-icon="check" color="primary" @click="confirmDeleteSelected" variant="elevated">Sim</v-btn>
                    </template>
                </v-card>
            </v-dialog>

        </div>
    </div>
</template>

<style>
.spacer {
    flex: 1 1 auto;
}
</style>import { Funcionario, emptyFuncionario } from '../api/funcionario';
import FuncionarioService from '../service/FuncionarioService';import { Funcionario, emptyFuncionario } from '../api/funcionario';
import FuncionarioService from '../service/FuncionarioService';

// frontend/hfs-frontend-material/src/app/hfsfullstack/pages/funcionario/funcionario.component.ts
import { AfterViewInit, ViewChild, Component, OnInit, Inject, ElementRef } from '@angular/core';
import { ReportParamForm } from 'src/app/base/models/ReportParamsForm';
import { ItypeReport } from 'src/app/base/services/ReportService';
import { MatSnackBar } from '@angular/material/snack-bar';
import { MatTableDataSource } from '@angular/material/table';
import { MatPaginator, PageEvent } from '@angular/material/paginator';
import { MatSort } from '@angular/material/sort';
import { SelectionModel } from '@angular/cdk/collections';
import { MatDialog } from '@angular/material/dialog';
import { FuncionarioDialogDelete } from './dialogs/funcionario.dialog-delete';
import { FuncionarioDialogMultipleDelete } from './dialogs/funcionario.dialog-multiple-delete';
import { Funcionario, cleanFuncionario, emptyFuncionario } from '../../api/funcionario';
import { FuncionarioService } from '../../service/funcionario.service';
import { ExportService } from 'src/app/base/services/export.service';
import { BaseUtilService } from 'src/app/base/util/base-util.service';
import { DataTableFilterMeta, LazyTableParam, emptyLazyTableParam } from 'src/app/base/models/LazyTableParam';
import { PaginationDTO } from 'src/app/base/models/PaginationDTO';
import { FuncionarioDataSource } from './funcionario.data-source';
import { debounceTime, distinctUntilChanged, fromEvent, merge, tap } from 'rxjs';

@Component({
  templateUrl: './funcionario.component.html',
  styleUrls: ["./funcionario.component.css"],
  providers: [FuncionarioService, BaseUtilService]
})
export class FuncionarioComponent implements OnInit, AfterViewInit {

  funcionarioDialog: boolean = false;

  listaFuncionario: Funcionario[];

  funcionario: Funcionario = emptyFuncionario;

  submitted: boolean = false;

  cols: any[] = [];

  exportColumns: any[];

  reportParamForm: ReportParamForm;

  displayedColumns: string[] = [];
  dataSource: FuncionarioDataSource;

  @ViewChild(MatPaginator) paginator: MatPaginator;
  @ViewChild(MatSort) sort: MatSort;
  selection: SelectionModel<Funcionario>;

  totalRecords: number = 0;
  loading: boolean = false;
  @ViewChild('input') inputPesquisa: ElementRef;
  valorInputPesquisa = '';

  constructor(private funcionarioService: FuncionarioService,
    private exportService: ExportService,
    private baseUtilService: BaseUtilService,
    private snackBar: MatSnackBar, public dialog: MatDialog) {
      this.reportParamForm = {
        reportType: 'PDF',
        forceDownload: true
      };

    const initialSelection = [];
    const allowMultiSelect = true;  
    this.selection = new SelectionModel<Funcionario>(allowMultiSelect, initialSelection);
  }
    
  ngOnInit(): void {
    this.cols = [
      { field: 'select', header: '' },
      { field: 'actions', header: '' },
      { field: 'id', header: 'Código' },
      { field: 'nome', header: 'Nome' },
      { field: 'cpfFormatado', header: 'Cpf' },
      { field: 'email', header: 'Email' },
      { field: 'telefone', header: 'Telefone' },
      { field: 'celular', header: 'Celular' },
      { field: 'setor', header: 'Setor' },
      { field: 'codCargo', header: 'CodCargo' },
      { field: 'cargo', header: 'Cargo' },
      { field: 'dataAdmissaoFormatada', header: 'Data Admissão' },
      { field: 'dataSaidaFormatada', header: 'Data Saída' },
      { field: 'ativo', header: 'Ativo' }      
    ];

    this.displayedColumns = this.cols.map(col => col.field);
    this.exportColumns = this.cols.map(col => ({title: col.header, dataKey: col.field}));        
    
    this.dataSource = new FuncionarioDataSource(this.funcionarioService);
    this.dataSource.loadFuncionarios().then((dto: PaginationDTO) => {
      this.listaFuncionario = dto.content;
      this.totalRecords = dto.totalElements;
    });
  }
        
  ngAfterViewInit(): void {
    // server-side search
    fromEvent(this.inputPesquisa.nativeElement,'keyup')
        .pipe(
            debounceTime(150),
            distinctUntilChanged(),
            tap(() => {
                this.paginator.pageIndex = 0;
                this.loadFuncionarioPage();
            })
        )
        .subscribe();

    // reset the paginator after sorting
    this.sort.sortChange.subscribe(() => this.paginator.pageIndex = 0);
            
    merge(this.sort.sortChange, this.paginator.page)
        .pipe(
            tap(() => this.loadFuncionarioPage())
        )
        .subscribe();    
  }

  loadFuncionarioPage() {
    this.dataSource.loadFuncionarios(
      this.inputPesquisa.nativeElement.value, this.sort.direction, 
      this.paginator.pageIndex, this.paginator.pageSize).then((dto: PaginationDTO) => {
        this.listaFuncionario = dto.content;
        this.totalRecords = dto.totalElements;
      });
  }

  isAllSelected() {
    const numSelected = this.selection.selected.length;
    const numRows = this.dataSource.data.content.length;
    return numSelected == numRows;
  }
  
  toggleAllRows() {
    this.isAllSelected() ?
      this.selection.clear() :
        this.dataSource.data.content.forEach(row => this.selection.select(row));
  }

  onInputPesquisaClick(){
    this.valorInputPesquisa = '';
    this.inputPesquisa.nativeElement.value = '';
    this.paginator.pageIndex = 0;
    this.loadFuncionarioPage();
  }

  onChangedTypeReport(typeReport: ItypeReport) {
    this.reportParamForm.reportType = typeReport.type;
  }

  onChangedForceDownload(forceDownload: boolean) {
    this.reportParamForm.forceDownload = forceDownload;
  }

  onExport() {
    this.funcionarioService.report(this.reportParamForm).then(() => {
      this.snackBar.open('Funcionário exportado', 'info', { duration: 3000 });
    });
  }

  mostrarListar() {
    if (this.funcionarioDialog)
        return {display:'none'};
    else
        return {display:''};
  }

  mostrarEditar() {
      if (this.funcionarioDialog)
          return {display:''};
      else
          return {display:'none'};
  }

  onClean() {
    this.funcionario = cleanFuncionario;
  }

  hideDialog() {
    this.funcionarioDialog = false;
    this.submitted = false;
  }

  onInsert() {
    this.funcionario = emptyFuncionario;
    this.submitted = false;
    this.funcionarioDialog = true;
  }

  onEdit(funcionario: Funcionario) {
    this.funcionario = { ...funcionario };
    this.funcionarioDialog = true;
  }

  onSave() {    
    this.submitted = true;
    this.funcionario.cpf = this.baseUtilService.cpfFormatadoParaCpf(this.funcionario.cpfFormatado);
    this.funcionario.dataAdmissao = this.baseUtilService.dataStringToDate(this.funcionario.dataAdmissaoFormatada);
    this.funcionario.dataSaida = this.baseUtilService.dataStringToDate(this.funcionario.dataSaidaFormatada);

    if (this.funcionario.nome.trim()) {
        if (this.funcionario.id) {
          this.funcionarioService.update(this.funcionario).then((obj: Funcionario) => {
            this.funcionario = obj;
            this.listaFuncionario[this.funcionarioService
              .findIndexById(this.listaFuncionario, this.funcionario.id)] = this.funcionario;

            this.listaFuncionario = [...this.listaFuncionario];
            this.funcionario = emptyFuncionario;
            this.dataSource.data.content = this.listaFuncionario;
      
            this.snackBar.open('Funcionário Atualizado', 'Sucesso', { duration: 3000 });
          });
        } else {
          this.funcionarioService.insert(this.funcionario).then((obj: Funcionario) => {
            this.funcionario = obj;
            this.listaFuncionario.push(this.funcionario);

            this.listaFuncionario = [...this.listaFuncionario];
            this.funcionario = emptyFuncionario;
            this.dataSource.data.content = this.listaFuncionario;
    
            this.snackBar.open('Funcionário Criado', 'Sucesso', { duration: 3000 });
          });
        }

    }
  }

  deleteSelected() {
    const dialogRef = this.dialog.open(FuncionarioDialogMultipleDelete, { 
      data: { 
        lista: this.listaFuncionario, 
        selecao: this.selection.selected
      } 
    });

    dialogRef.afterClosed().subscribe(result => {
      if (result){
        this.listaFuncionario = result.lista;
        this.confirmDeleteSelected();
      }
    });
  }

  onDelete(funcionario: Funcionario) {
    const dialogRef = this.dialog.open(FuncionarioDialogDelete, { 
      data: { 
        lista: this.listaFuncionario, 
        entidade: funcionario
      } 
    });

    dialogRef.afterClosed().subscribe(result => {
      if (result){
        this.listaFuncionario = result.lista;
        this.funcionario = result.entidade;
        this.confirmDelete();
      }
    });
      
  } 

  confirmDeleteSelected() {
    this.listaFuncionario = this.listaFuncionario.filter(val => !this.selection.selected.includes(val));

    this.selection.selected.forEach(async (item: Funcionario, index: number) => {
      await this.funcionarioService.delete(item.id);
      
      if (this.selection.selected.length == (index+1)){
        this.selection.clear();
        this.dataSource.data.content = this.listaFuncionario;
        this.snackBar.open('Funcionários excluídos', 'Sucesso', { duration: 3000 });        
      }
    });

  }

  confirmDelete() {
    this.funcionarioService.delete(this.funcionario.id).then(obj => {
      this.listaFuncionario = this.listaFuncionario.filter(val => val.id !== this.funcionario.id);
      this.funcionario = emptyFuncionario;     
      //this.dataSource.data = this.listaFuncionario;   
      this.snackBar.open('Funcionário excluído', 'Sucesso', { duration: 3000 });
    });
  }  

  exportPdf() {
    const head: string[] = [];
    const data: any[] = [];

    this.exportColumns.forEach(item => head.push(item.title));
    this.listaFuncionario.forEach(item => data.push(
        [item.id, item.nome, item.cpfFormatado, item.email, item.telefone, item.celular, 
        item.setor, item.codCargo, item.cargo, item.dataAdmissaoFormatada, item.dataSaidaFormatada, item.ativo]
    ));

    this.exportService.exportPdf(head, data, 'funcionarios.pdf');
  }

  exportExcel() {
      this.exportService.exportExcel(this.listaFuncionario, 'funcionarios');
  }    

}

<div class="grid">
    <div class="col-12">
        <div class="card px-6 py-6" [style]="mostrarListar()">

            <mat-card styleClass="p-mb-2">
                <mat-card-header>
                    <mat-card-title>Funcionário</mat-card-title>
                </mat-card-header>
                <mat-card-content>
                    <app-report-panel (typeReportChange)="onChangedTypeReport($event)" (forceDownloadChange)="onChangedForceDownload($event)"></app-report-panel>
                </mat-card-content>
            </mat-card>    

            <mat-toolbar styleClass="mb-4">
                <div class="my-2">
                    <button mat-raised-button color="primary" style="margin-right: 10px;" (click)="onInsert()">
                        <mat-icon>add</mat-icon> Adicionar
                    </button>
                    <button mat-raised-button color="warn" (click)="deleteSelected()" 
                        [disabled]="!selection.selected || !selection.selected.length">
                        <mat-icon>delete</mat-icon> Excluir
                    </button>
                </div>

                <span class="spacer"></span>

                <button mat-raised-button (click)="onExport()">
                    <mat-icon>upload</mat-icon> Exportar
                </button>
            </mat-toolbar>

            <mat-toolbar styleClass="mb-4">
                <mat-form-field style="width: 400px;">                    
                    <mat-label>Pesquisar pelo nome:</mat-label>
                    <input matInput placeholder="Pesquisar..." #input type="text" [(ngModel)]="valorInputPesquisa">
                    @if (valorInputPesquisa) {
                        <button matSuffix mat-icon-button aria-label="limpar" (click)="onInputPesquisaClick()">
                        <mat-icon>close</mat-icon>
                        </button>
                    }
                </mat-form-field>                

                <span class="spacer"></span>
                
                <button mat-icon-button style="margin-right: 10px;" (click)="exportPdf()">
                    <mat-icon>picture_as_pdf</mat-icon>
                </button>
                <button mat-icon-button style="margin-right: 10px;" (click)="exportExcel()">
                    <mat-icon>description</mat-icon>
                </button>        

            </mat-toolbar>

            <div class="spinner-container" *ngIf="dataSource.loading$ | async">
                <mat-spinner></mat-spinner>
            </div>

            <mat-paginator
                [length]="totalRecords"    
                [pageSize]="10" 
                showFirstLastButtons
                [pageSizeOptions]="[10,30,50,100,150,200]"
                aria-label="Selecione a página de elementos periódicos">
            </mat-paginator>

            <mat-sidenav-container fxFlex="0 1 auto">

                <mat-sidenav #sidenav position="start" mode="side" opened="false" class="width-30 p-6">
                    
                </mat-sidenav>

                <mat-sidenav-content>

                    <div class="mat-elevation-z8 m-12">
                        <div class="table-container">
                            
                            <table mat-table [dataSource]="dataSource" style="width: 100%;" matSort matSortActive="nome" matSortDirection="asc" matSortDisableClear>
                                <ng-container matColumnDef="select">
                                    <th mat-header-cell *matHeaderCellDef>
                                        <mat-checkbox (change)="$event ? toggleAllRows() : null" [checked]="selection.hasValue() && isAllSelected()"
                                            [indeterminate]="selection.hasValue() && !isAllSelected()">
                                        </mat-checkbox>
                                    </th>
                                    <td mat-cell *matCellDef="let row">
                                        <mat-checkbox (click)="$event.stopPropagation()" (change)="$event ? selection.toggle(row) : null"
                                            [checked]="selection.isSelected(row)">
                                        </mat-checkbox>
                                    </td>
                                </ng-container>
                                <ng-container matColumnDef="actions" style="width:10%; min-width:8rem;">
                                    <th mat-header-cell *matHeaderCellDef style="min-width: 140px;"> Ações </th>
                                    <td mat-cell *matCellDef="let row" style="min-width: 140px;">
                                        <div class="flex">
                                            <button mat-icon-button color="accent" style="margin-right: 10px;" (click)="onEdit(row)">
                                                <mat-icon>edit</mat-icon>
                                            </button>
                                            <button mat-icon-button color="warn" (click)="onDelete(row)">
                                                <mat-icon>delete</mat-icon>
                                            </button>
                                        </div>    
                                    </td>
                                </ng-container>
                                <ng-container matColumnDef="id">
                                    <th mat-header-cell *matHeaderCellDef mat-sort-header style="min-width: 5rem;"> Id </th>
                                    <td mat-cell *matCellDef="let element"  style="min-width: 5rem;"> {{element.id}} </td>
                                </ng-container>
                                <ng-container matColumnDef="nome">
                                    <th mat-header-cell *matHeaderCellDef mat-sort-header style="min-width: 20rem;"> Nome </th>
                                    <td mat-cell *matCellDef="let element" style="min-width: 20rem;"> {{element.nome}} </td>
                                </ng-container>
                                <ng-container matColumnDef="cpfFormatado">
                                    <th mat-header-cell *matHeaderCellDef mat-sort-header style="min-width: 10rem;"> Cpf </th>
                                    <td mat-cell *matCellDef="let element" style="min-width: 10rem;"> {{element.cpfFormatado}} </td>
                                </ng-container>
                                <ng-container matColumnDef="email">
                                    <th mat-header-cell *matHeaderCellDef mat-sort-header style="min-width: 10rem;"> Email </th>
                                    <td mat-cell *matCellDef="let element" style="min-width: 10rem;"> {{element.email}} </td>
                                </ng-container>
                                <ng-container matColumnDef="telefone">
                                    <th mat-header-cell *matHeaderCellDef mat-sort-header style="min-width: 10rem;"> Telefone </th>
                                    <td mat-cell *matCellDef="let element" style="min-width: 10rem;"> {{element.telefone}} </td>
                                </ng-container>
                                <ng-container matColumnDef="celular">
                                    <th mat-header-cell *matHeaderCellDef mat-sort-header style="min-width: 10rem;"> Celular </th>
                                    <td mat-cell *matCellDef="let element" style="min-width: 10rem;"> {{element.celular}} </td>
                                </ng-container>
                                <ng-container matColumnDef="setor">
                                    <th mat-header-cell *matHeaderCellDef mat-sort-header style="min-width: 10rem;"> Setor </th>
                                    <td mat-cell *matCellDef="let element" style="min-width: 10rem;"> {{element.setor}} </td>
                                </ng-container>
                                <ng-container matColumnDef="codCargo">
                                    <th mat-header-cell *matHeaderCellDef mat-sort-header style="min-width: 10rem;"> CodCargo </th>
                                    <td mat-cell *matCellDef="let element" style="min-width: 10rem;"> {{element.codCargo}} </td>
                                </ng-container>
                                <ng-container matColumnDef="cargo">
                                    <th mat-header-cell *matHeaderCellDef mat-sort-header style="min-width: 20rem;"> Cargo </th>
                                    <td mat-cell *matCellDef="let element" style="min-width: 20rem;"> {{element.cargo}} </td>
                                </ng-container>
                                <ng-container matColumnDef="dataAdmissaoFormatada" style="min-width: 12rem;">
                                    <th mat-header-cell *matHeaderCellDef mat-sort-header style="min-width: 12rem;"> Data Admissão </th>
                                    <td mat-cell *matCellDef="let element"> {{element.dataAdmissaoFormatada}} </td>
                                </ng-container>
                                <ng-container matColumnDef="dataSaidaFormatada">
                                    <th mat-header-cell *matHeaderCellDef mat-sort-header style="min-width: 10rem;"> Data Saída </th>
                                    <td mat-cell *matCellDef="let element" style="min-width: 10rem;"> {{element.dataSaidaFormatada}} </td>
                                </ng-container>
                                <ng-container matColumnDef="ativo">
                                    <th mat-header-cell *matHeaderCellDef mat-sort-header style="min-width: 10rem;"> Ativo </th>
                                    <td mat-cell *matCellDef="let element" style="min-width: 10rem;"> {{element.ativo}} </td>
                                </ng-container>
                            
                                <tr mat-header-row *matHeaderRowDef="displayedColumns"></tr>
                                <tr mat-row *matRowDef="let row; columns: displayedColumns;"></tr>
                            </table>

                        </div>

                    </div>

                </mat-sidenav-content>

            </mat-sidenav-container>

            <mat-divider></mat-divider>

            <div style="margin-left: 30px; font-weight: bold;">
                No total existem {{listaFuncionario ? listaFuncionario.length : 0 }} funcionários.
            </div>

        </div>

        <div [style]="mostrarEditar()">

            <mat-card styleClass="p-mb-2">
                <mat-card-header>
                    <mat-card-title>Detalhes do funcionário</mat-card-title>
                </mat-card-header>
                <mat-card-content>

                    <mat-toolbar styleClass="mb-4">
                        <span class="spacer"></span>
                        
                        <button mat-raised-button style="margin-right: 10px;" (click)="hideDialog()">
                            <mat-icon>cancel</mat-icon> Cancelar
                        </button>
                        <button mat-raised-button style="margin-right: 10px;" (click)="onClean()">
                            <mat-icon>star</mat-icon> Limpar
                        </button>
                        <button mat-raised-button color="primary" (click)="onSave()">
                            <mat-icon>check</mat-icon> Salvar
                        </button>
                    
                    </mat-toolbar>                      

                    <div class="card p-fluid">
                        <mat-form-field style="width: 100%;">
                            <mat-label>Nome</mat-label>
                            <input matInput [(ngModel)]="funcionario.nome" required autofocus
                                [ngClass]="{'ng-invalid ng-dirty' : submitted && !funcionario.nome}">
                            @if (!funcionario.nome) {
                                <mat-error>O Nome é obrigatório.</mat-error>
                            }
                        </mat-form-field>
                        <br>
                        <mat-form-field style="width: 100%;">
                            <mat-label>Email</mat-label>
                            <input matInput [(ngModel)]="funcionario.email">
                        </mat-form-field>    
                        <br>
                        <mat-grid-list cols="2" rowHeight="80px" gutterSize="20px">
                            <mat-grid-tile>
                                <mat-form-field style="width: 100%;">
                                    <mat-label>Cpf</mat-label>
                                    <input matInput [(ngModel)]="funcionario.cpfFormatado" required
                                    [ngClass]="{'ng-invalid ng-dirty' : submitted && !funcionario.cpfFormatado}">
                                    @if (!funcionario.cpfFormatado) {
                                        <mat-error>CPF é obrigatório.</mat-error>
                                    }
                                </mat-form-field>
                            </mat-grid-tile>
                            <mat-grid-tile>
                                <mat-form-field style="width: 100%;">
                                    <mat-label>Telefone</mat-label>
                                    <input matInput [(ngModel)]="funcionario.telefone">
                                </mat-form-field>        
                            </mat-grid-tile>
                            <mat-grid-tile>
                                <mat-form-field style="width: 100%;">
                                    <mat-label>Celular</mat-label>
                                    <input matInput [(ngModel)]="funcionario.celular">
                                </mat-form-field>
                            </mat-grid-tile>
                            <mat-grid-tile>
                                <mat-form-field style="width: 100%;">
                                    <mat-label>Setor</mat-label>
                                    <input matInput [(ngModel)]="funcionario.setor">
                                </mat-form-field>        
                            </mat-grid-tile>
                            <mat-grid-tile>
                                <mat-form-field style="width: 100%;">
                                    <mat-label>CodCargo</mat-label>
                                    <input type="number" matInput [(ngModel)]="funcionario.codCargo">
                                </mat-form-field>    
                            </mat-grid-tile>
                            <mat-grid-tile>
                                <mat-form-field style="width: 100%;">
                                    <mat-label>Cargo</mat-label>
                                    <input matInput [(ngModel)]="funcionario.cargo">
                                </mat-form-field>        
                            </mat-grid-tile>
                            <mat-grid-tile>
                                <mat-form-field style="width: 100%;">
                                    <mat-label>Data Admissão</mat-label>
                                    <input type="date" matInput [(ngModel)]="funcionario.dataAdmissao">
                                </mat-form-field>    
                            </mat-grid-tile>
                            <mat-grid-tile>
                                <mat-form-field style="width: 100%;">
                                    <mat-label>Data Saída</mat-label>
                                    <input type="date" matInput [(ngModel)]="funcionario.dataSaida">
                                </mat-form-field>        
                            </mat-grid-tile>
                        </mat-grid-list>
                            
                        <mat-checkbox [(ngModel)]="funcionario.ativo">Ativo</mat-checkbox>
                    </div>                
                            
                </mat-card-content>
            </mat-card>    

        </div>

    </div>
</div>
