// frontend/hfs-frontend-vue/src/system/usuario/UsuarioPage.vue
<script lang="ts">
import { ref, onMounted } from 'vue';
import { emptyUserAuthenticated } from '../../base/models/UserAuthenticated';
import keycloakService from '../../main.ts';

export default {
    setup() {
        const userAuthenticated = ref(emptyUserAuthenticated);

        onMounted(() => {
            userAuthenticated.value = keycloakService.getUserAuthenticated();
        });

        return { userAuthenticated };
    }
}
</script>

<template>
    <div class="grid">
        <div class="col-12">
            <div class="card px-6 py-6">
                <Card>
                    <template #title>Usuário logado</template>
                    <template #content>
                        <p class="m-0">
                            <b>ID: </b>
                            {{userAuthenticated.id}}
                            <br><br>
                            <b>Login: </b>
                            {{userAuthenticated.userName}}
                            <br><br>
                            <b>E-mail: </b>
                            {{userAuthenticated.email}}
                            <br><br>
                            <b>E-mail verificado: </b>
                            {{userAuthenticated.emailVerified ? 'Sim' : 'Não'}}
                            <br><br>
                            <b>Nome: </b>
                            {{userAuthenticated.fullName}}
                            <br><br>
                            <b>É administrador: </b>
                            {{userAuthenticated.isAdmin ? 'Sim' : 'Não'}}
                            <br><br>
                            <b>Papéis: </b>
                            <ul>
                                <li v-for="role in userAuthenticated.roles">
                                    {{ role }}
                                </li>
                            </ul>                        
                            <br><br>
                        </p>
                    </template>
                </Card>
            </div>
        </div>
    </div>
</template>

// frontend/hfs-frontend-react-mui/src/system/usuario/UsuarioPage.tsx
'use client';
import { useEffect, useState } from 'react';
import { UserAuthenticated, emptyUserAuthenticated } from '../../base/models/UserAuthenticated';
import keycloakService from '../../main';
import Card from '@mui/material/Card';
import CardHeader from '@mui/material/CardHeader';
import CardContent from '@mui/material/CardContent';

const UsuarioPage = () => {
    
    const [userAuthenticated, setUserAuthenticated] = useState<UserAuthenticated>(emptyUserAuthenticated);
    const [listaRoles, setListaRoles] = useState<React.JSX.Element[]>([]);

    useEffect(() => {
        setUserAuthenticated(keycloakService.getUserAuthenticated());
        
        let lista: React.JSX.Element[] = [];
        keycloakService.getUserAuthenticated().roles.forEach((role, index) => {
            lista.push(<li key={index}>{role}</li>);
        });
        
        setListaRoles(lista);    

    }, []);

    return (
        <Card>
            <CardHeader title="Usuário logado"/>
            <CardContent>
                <b>ID: </b>
                {userAuthenticated.id}
                <br></br>
                <br></br>
                <b>Login: </b>
                {userAuthenticated.userName}
                <br></br>
                <br></br>
                <b>E-mail: </b>
                {userAuthenticated.email}
                <br></br>
                <br></br>
                <b>E-mail verificado: </b>
                {userAuthenticated.emailVerified ? 'Sim' : 'Não'}
                <br></br>
                <br></br>
                <b>Nome: </b>
                {userAuthenticated.fullName}
                <br></br>
                <br></br>
                <b>É administrador: </b>
                {userAuthenticated.isAdmin ? 'Sim' : 'Não'}
                <br></br>
                <br></br>
                <b>Papéis: </b>
                {listaRoles}
                <br></br>
                <br></br>
            </CardContent>
        </Card>       
    );
};

export default UsuarioPage;
