// frontend/hfs-frontend-material/src/app/layout/config/app.config.component.ts
import { Component, Input } from '@angular/core';
import { LayoutService } from '../service/app.layout.service';
import { MenuService } from '../app.menu.service';

@Component({
    selector: 'app-config',
    templateUrl: './app.config.component.html',
})
export class AppConfigComponent {
    @Input() minimal: boolean = false;

    scales: number[] = [12, 13, 14, 15, 16];

    constructor(
        public layoutService: LayoutService,
        public menuService: MenuService        
    ) {}

    get visible(): boolean {
        return this.layoutService.state.configSidebarVisible;
    }
    set visible(_val: boolean) {
        this.layoutService.state.configSidebarVisible = _val;
    }

    get scale(): number {
        return this.layoutService.config().scale;
    }
    set scale(_val: number) {
        this.layoutService.config.update((config) => ({
            ...config,
            scale: _val,
        }));
    }

    get menuMode(): string {
        return this.layoutService.config().menuMode;
    }
    set menuMode(_val: string) {
        this.layoutService.config.update((config) => ({
            ...config,
            menuMode: _val,
        }));
    }

    get inputStyle(): string {
        return this.layoutService.config().inputStyle;
    }
    set inputStyle(_val: string) {
        this.layoutService.config().inputStyle = _val;
    }

    get ripple(): boolean {
        return this.layoutService.config().ripple;
    }
    set ripple(_val: boolean) {
        this.layoutService.config.update((config) => ({
            ...config,
            ripple: _val,
        }));
    }

    set theme(val: string) {
        this.layoutService.config.update((config) => ({
            ...config,
            theme: val,
        }));
    }
    get theme(): string {
        return this.layoutService.config().theme;
    }

    set colorScheme(val: string) {
        this.layoutService.config.update((config) => ({
            ...config,
            colorScheme: val,
        }));
    }
    get colorScheme(): string {
        return this.layoutService.config().colorScheme;
    }

    onConfigButtonClick() {
        this.layoutService.showConfigSidebar();
    }

    changeTheme(theme: string, colorScheme: string) {
        this.theme = theme;
        this.colorScheme = colorScheme;
    }

    decrementScale() {
        this.scale--;
    }

    incrementScale() {
        this.scale++;
    }

    changeMenuMode(valor: string) {
        this.menuMode = valor;
        
    };

    changeInputStyle(valor: string) {
        this.inputStyle = valor;
    };
}

<div class="grid">
    <div class="col-12">
        <div class="card px-6 py-6">

            <h5>Esquema de cor</h5>
            <div class="grid">
                <div class="col-2">
                    <button mat-icon-button class="p-link w-4rem h-2rem" (click)="changeTheme('lara-light-indigo', 'light')">
                        <mat-icon style="font-size: 1.8rem">light_mode</mat-icon>
                    </button>
                    <button mat-icon-button class="p-link w-4rem h-2rem" (click)="changeTheme('lara-dark-indigo', 'dark')">
                        <mat-icon style="font-size: 1.8rem">dark_mode</mat-icon>
                    </button>
                </div>
            </div>
        
            <h5>Escala</h5>
            <div class="grid">
                <div class="col-2">
                    <button mat-icon-button (click)="decrementScale()" class="p-button-text p-button-rounded w-2rem h-2rem mr-2" [disabled]="scale === scales[0]">
                        <mat-icon style="font-size: 1.8rem">remove</mat-icon>
                    </button>
                    <button mat-icon-button (click)="incrementScale()" class="p-button-text p-button-rounded w-2rem h-2rem ml-2" [disabled]="scale === scales[scales.length - 1]">
                        <mat-icon style="font-size: 1.8rem">add</mat-icon>
                    </button>
                </div>
            </div>
            
            <ng-container *ngIf="!minimal">
                <h5>Tipo de menu</h5>
                <mat-radio-group aria-label="Tipo de menu" [(ngModel)]="menuMode">
                    <div class="field-radiobutton">
                        <mat-radio-button id="mode1" value="static" (click)="changeMenuMode('static')"></mat-radio-button>
                        <label for="mode1">Static</label>
                    </div>
                    <div class="field-radiobutton">
                        <mat-radio-button id="mode2" value="overlay" (click)="changeMenuMode('overlay')"></mat-radio-button>
                        <label for="mode2">Overlay</label>
                    </div>
                </mat-radio-group>
            </ng-container>

            <ng-container *ngIf="!minimal">
                <h5>Estilo de entrada</h5>
                <div class="flex">
                    <mat-radio-group aria-label="Tipo de menu" [(ngModel)]="inputStyle">
                        <div class="field-radiobutton flex-1">
                            <mat-radio-button id="outlined_input" value="outlined" (click)="changeInputStyle('outlined')"></mat-radio-button>
                            <label for="outlined_input">Outlined</label>
                        </div>
                        <div class="field-radiobutton flex-1">
                            <mat-radio-button id="filled_input" value="filled" (click)="changeInputStyle('filled')" ></mat-radio-button>
                            <label for="filled_input">Filled</label>
                        </div>    
                    </mat-radio-group>
                </div>
            </ng-container>
        </div>
    </div>
</div>

// frontend/hfs-frontend-react-mui/src/layout/AppConfig.tsx
'use client';

import { useContext, useEffect, useState } from 'react';
import { LayoutContext } from './context/layoutcontext';
import { LayoutConfig } from '../types';
//import { classNames } from '../base/util/LayoutUtils';
import IconButton from '@mui/material/IconButton';
import LightModeIcon from '@mui/icons-material/LightMode';
import DarkModeIcon from '@mui/icons-material/DarkMode';
import RemoveIcon from '@mui/icons-material/Remove';
import AddIcon from '@mui/icons-material/Add';
import Radio from '@mui/material/Radio';

const AppConfig = () => {
    const [scales] = useState([12, 13, 14, 15, 16]);
    //const { layoutConfig, setLayoutConfig, layoutState, setLayoutState } = useContext(LayoutContext);
    const { layoutConfig, setLayoutConfig } = useContext(LayoutContext);
    //const { setRipple, changeTheme } = useContext(PrimeReactContext);
    /*
        const onConfigButtonClick = () => {
            setLayoutState((prevState: LayoutState) => ({ ...prevState, configSidebarVisible: true }));
        };
    
        const onConfigSidebarHide = () => {
            setLayoutState((prevState: LayoutState) => ({ ...prevState, configSidebarVisible: false }));
        };
        
        const changeRipple = (e: InputSwitchChangeEvent) => {
            setRipple?.(e.value as boolean);
            setLayoutConfig((prevState: LayoutConfig) => ({ ...prevState, ripple: e.value as boolean }));
        };
    */

    const changeInputStyle = (e: React.ChangeEvent<HTMLInputElement>) => {
        setLayoutConfig((prevState: LayoutConfig) => ({ ...prevState, inputStyle: e.target.value }));
    };

    const changeMenuMode = (e: React.ChangeEvent<HTMLInputElement>) => {
        setLayoutConfig((prevState: LayoutConfig) => ({ ...prevState, menuMode: e.target.value }));
    };

    const _changeTheme = (theme: string, colorScheme: string) => {
        //changeTheme?.(layoutConfig.theme, theme, 'theme-css', () => {
            setLayoutConfig((prevState: LayoutConfig) => ({ ...prevState, theme, colorScheme }));
        //});
    };

    const decrementScale = () => {
        setLayoutConfig((prevState: LayoutConfig) => ({ ...prevState, scale: prevState.scale - 1 }));
    };

    const incrementScale = () => {
        setLayoutConfig((prevState: LayoutConfig) => ({ ...prevState, scale: prevState.scale + 1 }));
    };

    const applyScale = () => {
        document.documentElement.style.fontSize = layoutConfig.scale + 'px';
    };

    useEffect(() => {
        applyScale();
    }, [layoutConfig.scale]);

    return (
        <div className="grid">
            <div className="col-12">
                <div className="card px-6 py-6">

                    <h5>Esquema de cor</h5>
                    <div className="grid">
                        <div className="col-4">
                            <IconButton className="p-link w-4rem h-2rem" onClick={() => _changeTheme('lara-light-indigo', 'light')}>
                                <LightModeIcon fontSize="inherit" />
                            </IconButton>
                            <IconButton className="p-link w-4rem h-2rem" onClick={() => _changeTheme('lara-dark-indigo', 'dark')}>
                                <DarkModeIcon fontSize="inherit" />
                            </IconButton>
                        </div>
                    </div>

                    <h5>Escala</h5>
                    <div className="flex align-items-center">
                        <IconButton onClick={decrementScale} className="w-2rem h-2rem mr-2" disabled={layoutConfig.scale === scales[0]}>
                            <RemoveIcon fontSize="inherit" />
                        </IconButton>
                        <IconButton onClick={incrementScale} className="w-2rem h-2rem ml-2" disabled={layoutConfig.scale === scales[scales.length - 1]}>
                            <AddIcon fontSize="inherit" />
                        </IconButton>
                    </div>

                    <h5>Tipo de menu</h5>
                    <div className="flex">
                        <div className="field-radiobutton flex-1">
                            <Radio name="menuMode" value="static" checked={layoutConfig.menuMode === 'static'} 
                                onChange={(e) => changeMenuMode(e)} id="mode1"></Radio>
                            <label htmlFor="mode1">Static</label>
                        </div>
                        <div className="field-radiobutton flex-1">
                            <Radio name="menuMode" value="overlay" checked={layoutConfig.menuMode === 'overlay'} 
                                onChange={(e) => changeMenuMode(e)} id="mode2"></Radio>
                            <label htmlFor="mode2">Overlay</label>
                        </div>
                    </div>

                    <h5>Estilo de entrada</h5>
                    <div className="flex">
                        <div className="field-radiobutton flex-1">
                            <Radio name="inputStyle" value="outlined" checked={layoutConfig.inputStyle === 'outlined'} 
                                onChange={(e) => changeInputStyle(e)} id="outlined_input"></Radio>
                            <label htmlFor="outlined_input">Outlined</label>
                        </div>
                        <div className="field-radiobutton flex-1">
                            <Radio name="inputStyle" value="filled" checked={layoutConfig.inputStyle === 'filled'} 
                                onChange={(e) => changeInputStyle(e)} id="filled_input"></Radio>
                            <label htmlFor="filled_input">Filled</label>
                        </div>
                    </div>

                </div>
            </div>
        </div>

    );
};

export default AppConfig;
