// frontend/hfs-frontend-vuetify/src/system/usuario/UsuarioPage.vue
<script lang="ts">
import { ref, onMounted } from 'vue';
import { emptyUserAuthenticated } from '../../base/models/UserAuthenticated';
import keycloakService from '../../main.ts';

export default {
    setup() {
        const userAuthenticated = ref(emptyUserAuthenticated);

        onMounted(() => {
            userAuthenticated.value = keycloakService.getUserAuthenticated();
        });

        return { userAuthenticated };
    }
}
</script>

<template>
    <div class="grid">
        <div class="col-12">
            <div class="card px-6 py-6">
                <v-card-item>
                    <v-card-title>Usuário logado</v-card-title>
                </v-card-item>
                <v-card-text>
                    <p class="m-0">
                        <b>ID: </b>
                        {{userAuthenticated.id}}
                        <br><br>
                        <b>Login: </b>
                        {{userAuthenticated.userName}}
                        <br><br>
                        <b>E-mail: </b>
                        {{userAuthenticated.email}}
                        <br><br>
                        <b>E-mail verificado: </b>
                        {{userAuthenticated.emailVerified ? 'Sim' : 'Não'}}
                        <br><br>
                        <b>Nome: </b>
                        {{userAuthenticated.fullName}}
                        <br><br>
                        <b>É administrador: </b>
                        {{userAuthenticated.isAdmin ? 'Sim' : 'Não'}}
                        <br><br>
                        <b>Papéis: </b>                        
                        <li v-for="role in userAuthenticated.roles">
                            {{ role }}
                        </li>
                        <br><br>
                    </p>
                </v-card-text>                
            </div>
        </div>
    </div>
</template>

// frontend/hfs-frontend-react/src/system/usuario/UsuarioPage.tsx
'use client';
import { Card } from 'primereact/card';
import React, { useEffect, useState } from 'react';
import { UserAuthenticated, emptyUserAuthenticated } from '../../base/models/UserAuthenticated';
//import { SessionStorageService } from '../../base/services/SessionStorageService';
import keycloakService from '../../main';

const UsuarioPage = () => {

    //const sessionStorageService = new SessionStorageService();
    
    const [userAuthenticated, setUserAuthenticated] = useState<UserAuthenticated>(emptyUserAuthenticated);
    const [listaRoles, setListaRoles] = useState<[]>([]);

    useEffect(() => {
        //setUserAuthenticated(sessionStorageService.getPersistedObj('userAuthenticated') as UserAuthenticated);
        setUserAuthenticated(keycloakService.getUserAuthenticated());
        
        let lista: [] = [];
        keycloakService.getUserAuthenticated().roles.forEach((role, index) => {
            lista.push(<li key={index}>{role}</li>);
        });     
        
        setListaRoles(lista);    

    }, []);

    return (
        <div className="grid">
            <div className="col-12">
                <div className="card px-6 py-6">
                    <Card title="Usuário logado">
                        <p className="m-0">
                            <b>ID: </b>
                            {userAuthenticated.id}
                            <br></br>
                            <br></br>
                            <b>Login: </b>
                            {userAuthenticated.userName}
                            <br></br>
                            <br></br>
                            <b>E-mail: </b>
                            {userAuthenticated.email}
                            <br></br>
                            <br></br>
                            <b>E-mail verificado: </b>
                            {userAuthenticated.emailVerified ? 'Sim' : 'Não'}
                            <br></br>
                            <br></br>
                            <b>Nome: </b>
                            {userAuthenticated.fullName}
                            <br></br>
                            <br></br>
                            <b>É administrador: </b>
                            {userAuthenticated.isAdmin ? 'Sim' : 'Não'}
                            <br></br>
                            <br></br>
                            <b>Papéis: </b>
                            {listaRoles}
                            <br></br>
                            <br></br>
                        </p>
                    </Card>       
                </div>
            </div>
        </div>
    );
};

export default UsuarioPage;
